### ISSUE TITLE
Boost under Git

### ISSUE THREAD

**Issue by zonkmachine** [vegastrike/Vega-Strike-Engine-Source#1]
I haven't tested Vega Strike from git extensively but one thing I noticed is that Boost wasn't imported along with the sources. Subversion's 'Externals' and Git's  ̈́Submodules' doesn't work exactly the same way.
On Github, boost lives over here:
https://github.com/boostorg/boost

**Comment by stephengtuggy** [comment]
Any objections to updating Boost to the latest version? As of the time of this comment, I believe that is 1.71.0.

**Comment by zonkmachine** [comment]
Maybe try and add the Boost submodule first and then update to a later version. Have you used git submodules before?

**Comment by stephengtuggy** [comment]
> Maybe try and add the Boost submodule first and then update to a later version. Have you used git submodules before?

A little bit. I have a Pull Request waiting for review already, so I think I'll wait on adding the submodule.

**Comment by stephengtuggy** [comment]
@zonkmachine I tried adding Boost as a git submodule, and it was **a mess!** Came with over 100 sub-submodules. Checked out the `master` branch by default, which is quite a few commits ahead of their latest released version (1.71.0). When I tried checking out different tags (versions), I ended up with ghost "changed files", just from the line endings not being what was expected. Pretty soon, those "changed files" started keeping me from switching version tags!

I don't think the `git submodule` approach is going to work very well here. I suggest we consider other possible approaches. Such as [this](https://github.blog/2015-06-30-scripts-to-rule-them-all/)

Or, if we _do_ decide to pull in Boost as a submodule, then I would request that we decide right up front what version to use, then stick to that for as long as possible moving forward. Preferably a more recent version than what's on SVN.

**Comment by BenjamenMeyer** [comment]
Yeah, `git submodule` leaves a lot to be desired versus `svn:externals`. Not sure there's a really good way to resolve.

Q: do we really need to use submodules? Do we really need to bring along the dependencies?

Perhaps a better approach:
- have a cached downloaded for known working versions
- have a script to install them if they're . not already in the system
- update the build system to use system libraries where possible

cmake can find installed libraries on the system, even down to the version IIRC, and you can always use it to download and build other stuff too - it can fully interact with `git`. So worse case, make a CMake fileset to:
- download from the given cache and extract to a temporary directory (`.build-deps/downloads`)
- build contents in the temporary directory (`.build-deps/[src, lib, include, etc]`)
- continue on as before but reference the new CMake set

Would be nice if that could also switch between system dependencies and the cached version to minimize downloads, but a first go of just using the cached versions would be neat by itself.

**Comment by pyramid3d** [comment]
The whole boost source directory is nearly 700MB. It is not worth linking it as a submodule. The added advantage of including the sources directly is that they are readily available for compiling upon local cloning if the git repo.
So I have compile VS successfully with boost 1.72.0 and consequently added those sources to ext/boost/1_72_0. Instructions for integrating future (or legacy) versions have been added to ext/boost/integrating.txt

**Comment by stephengtuggy** [comment]
That works too :+1: . Thanks!
