### ISSUE TITLE
Migrate from GTK2 to GTK3

### ISSUE THREAD

**Issue by nabaco** [vegastrike/Vega-Strike-Engine-Source#103]
We use GTK+2 in our code, and I propose that we migrate to GTK+3.
This will allow us to use both more modern libraries, with better support, and will ease compilation on Windows, where getting GTK+2 is somewhat an issue.

Related to #53 

For information see here:
https://developer.gnome.org/gtk3/stable/gtk-migrating-2-to-3.html

**Comment by nabaco** [comment]
Can't assign to DMJC, probably since he's still not listed as a contributor in this repo, but he's taken this task upon himself, and is nearing completion.

**Comment by BenjamenMeyer** [comment]
Yeah you have to be an org member to get assignments

**Comment by Loki1950** [comment]
Stupid question shall I add him or will you @BenjamenMeyer

**Comment by DMJC** [comment]
I've sent a pull request through.
