### ISSUE TITLE
Figure out Travis-CI deploy for releases

### ISSUE THREAD

**Issue by nabaco** [vegastrike/Vega-Strike-Engine-Source#104]
To streamline our release process, I propose that we automate the creation of some packages, and their upload to GH releases.

https://docs.travis-ci.com/user/deployment/
https://docs.travis-ci.com/user/deployment/releases/

**Comment by BenjamenMeyer** [comment]
Depends on #131

**Comment by BenjamenMeyer** [comment]
The Vega Strike Engine is having its release builds posted to GitHub. We still need to get the Asset Productions to do the same.

**Comment by stephengtuggy** [comment]
@BenjamenMeyer I believe this is now done.

**Comment by BenjamenMeyer** [comment]
@stephengtuggy verified. Thanks!
