### ISSUE TITLE
No time compression?

### ISSUE THREAD

**Issue by nabaco** [vegastrike/Vega-Strike-Engine-Source#106]
The README instructions say that F9-F10 affect time compression, but in fact it affect music volume. Is the feature even available?

**Comment by royfalk** [comment]
I suspect not. AFAIK, it's a leftover from the days before 2006 when I first played it. It was replaced by SPEC.

**Comment by stephengtuggy** [comment]
> I suspect not. AFAIK, it's a leftover from the days before 2006 when I first played it. It was replaced by SPEC.

@royfalk I think you're right.

**Comment by nabaco** [comment]
Maybe @Loki1950, @danielrh, or @pyramid3d might give some more info?

**Comment by Loki1950** [comment]
Time-compression was removed as it lead to instability corrupted physics frame mainly so an edit of the Readme is in order this was before @klaussfreire developed the autopilot this was back in version 0.4.3

**Comment by Loki1950** [comment]
You all are aware the there is an in game key map available in space just hit the "ESC" key

**Comment by vincele** [comment]
I searched for F9 or F10 in README.md and it speaks of music volume, so I think this issue can be closed now.

Looks like the fix is in 9f413737475f9555deac40f980f217f7c6902a5f

**Comment by stephengtuggy** [comment]
Thanks for pointing that out, @vincele . I'll close the issue now.

**Comment by stephengtuggy** [comment]
Fixed in #140 .
