### ISSUE TITLE
Fix up the manpages

### ISSUE THREAD

**Issue by BenjamenMeyer** [vegastrike/Vega-Strike-Engine-Source#113]
as reported by #99 the manpages are vastly out of date and need a major update.
At minimum this involves updating any URLs; but the pages should be reviewed for accuracy too.

Also, we should disable installation of any vegastrike server manpages since we've temporarily removed that.

**Comment by nabaco** [comment]
@ermo can you just write here where are the man pages located in the source code?

**Comment by ermo** [comment]
`doc/man/*.1`

**Comment by BenjamenMeyer** [comment]
I think we've done this sufficiently for the time being.
