### ISSUE TITLE
vegastrike not starting

### ISSUE THREAD

**Issue by bergamote** [vegastrike/Vega-Strike-Engine-Source#117]
Hi all and thanks for the hard work!
I managed to compile on Ubuntu 19.10, but typing `bin/vegasettings` gives me:

    Error: Failed to find Version.txt anywhere.

and typing `bin/vegastrike` returns:

    ...
    CONFIGFILE - No config found in home : /home/xxx/.vegastrike/vegastrike.config
    CONFIGFILE - No config found in data dir : /vegastrike.config
    CONFIG FILE NOT FOUND !!!
    Panic exit - no configuration

Both my ~/.vegastrike and data folders are empty. Am I missing something?

**Comment by BenjamenMeyer** [comment]
@bergamote yes, you need an asset data set to run with.

Options are:
- checkout using `git clone --recurse-submodules`
- `git clone` and then `git pull --recurse-submodules`
- `git clone` of both this repository and https://github.com/vegastrike/Assets-Production

If you use the first two options the asset data is put in the `data` directory so a direct run of `./bin/vegastrike` will just work.

If you use the last, then you need to use the clone of the https://github.com/vegastrike/Assets-Production as the working directory.

**Comment by BenjamenMeyer** [comment]
marked as a bug, as we should verify that the directions provided in https://github.com/vegastrike/Vega-Strike-Engine-Source/issues/117#issuecomment-628346847 are documented in the README.md

**Comment by bergamote** [comment]
thanks!

**Comment by ermo** [comment]
> thanks!

Does it work for you now?

**Comment by bergamote** [comment]
Actually no, `git pull --recurse-submodules` returned `Already up-to-date.`
I had to run `git submodule update --init` and that worked, cloning the assets into data.
After that the game did launch! (on the wrong screen, but that's different problem)

**Comment by BenjamenMeyer** [comment]
@bergamote thanks for the info; not all of us use the `submodule` method. We need to get that stuff documented and your experience with the commands discussed in #98 highlights one of my concerns. The feedback is greatly appreciated.

**Comment by BenjamenMeyer** [comment]
@bergamote please confirm that we can close this issue.

**Comment by bergamote** [comment]
Most definitely. And #131 sounds like a helpful proposal!
