### ISSUE TITLE
Missing Contributors in Master branch

### ISSUE THREAD

**Issue by crts-crome** [vegastrike/Vega-Strike-Engine-Source#14]
I have mentioned this issue in the forum previously, not sure whether it has been noticed or not. After the merge of the SVN repository the new Master branch does not show the Contributors any more. The contributed code changes are still present but the files themselves show 0 Contributors when selected.
Is this going to be fixed at some point?

**Comment by crts-crome** [comment]
It is not just my contributions, by the way, e.g., the changes from #7 are also no longer attributed to the contributor in the Master branch.

**Comment by pyramid3d** [comment]
Answered in the forum

**Comment by BenjamenMeyer** [comment]
@pyramid3d can you link the answer here?

**Comment by crts-crome** [comment]
Here is the link to [the answer](https://forums.vega-strike.org/viewtopic.php?f=53&t=26104&p=169930#p169930).

However, the explanation is not entirely correct, specifically this part:

> ... Dunno why they were not included when I merged the code again into master ...

My changes were, in fact, merged back into the master branch and they are still there. I am just not listed as the contributor of those changes. Apparently, during the great merge the repository got squashed, i.e., its entire history is gone. 
This is what the [current history](https://github.com/vegastrike/Vega-Strike-Engine-Source/commits/master/engine/src/cmd/unit_generic.cpp) of the affected file looks like.

I still have the version [before the great merge](https://github.com/crts-crome/Vega-Strike-Engine-Source/commits/master/src/cmd/unit_generic.cpp) in my repository.

The history of all other files has also been cut short.

Another excerpt from the answer states

> ... klauss mentioned that the bug was already fixed by him ...

Klauss said, that he remembers fixing [something similar](https://github.com/vegastrike/Vega-Strike-Engine-Source/pull/12#issuecomment-544969625). I went through the file's (unit_generic.cpp) history in the SVN repository. I did not find any changes that might have fixed that bug.

**Comment by BenjamenMeyer** [comment]
> @BenjamenMeyer Here is the link to [the answer](https://forums.vega-strike.org/viewtopic.php?f=53&t=26104&p=169930#p169930).
> 

Thanks I'll give it a read.

> However, the explanation is not entirely correct, specifically this part:
> 
> > ... Dunno why they were not included when I merged the code again into master ...
> 
> My changes were, in fact, merged back into the master branch and they are still there, [around line 6440](https://github.com/vegastrike/Vega-Strike-Engine-Source/blob/master/engine/src/cmd/unit_generic.cpp#L6440). I am just not listed as the contributor of those changes. Here is a link to the [corresponding pull request](https://github.com/vegastrike/Vega-Strike-Engine-Source/pull/12). Apparently, during the great merge the repository got squashed, i.e., its entire history is gone. 
> This is what the [current history](https://github.com/vegastrike/Vega-Strike-Engine-Source/commits/master/engine/src/cmd/unit_generic.cpp) of the affected file looks like.
> 
> I still have the version [before the great merge](https://github.com/crts-crome/Vega-Strike-Engine-Source/commits/master/src/cmd/unit_generic.cpp) in my repository.
> 
> The history of all other files has also been cut short.

Looking that's back in 2019. I'll have to take a look, see what can be done. But I'll have to dig into some of the repo history too.

Let me read up on the forum and check into the history before I say more.

**Comment by crts-crome** [comment]
> Looking that's back in 2019. I'll have to take a look, see what can be done. But I'll have to dig into some of the repo history too.

The PR is from Oct 2019, yes, but it was only merged in  7. Feb. 2020. The next day the great merge of the SVN repository began which led to squashing/deleting all previous history.

**Comment by BenjamenMeyer** [comment]
@crts-crome I understand the concern.

FTR, I've added some protections on our dev and release branches. Administrators can still override, but that really should be a rare case when we need to fix something. Noting that this shouldn't be an issue going forward. I'm not sure what I can do about the past, but if I find something I'll try to do it as I quite agree that attribution should be given.

**Comment by crts-crome** [comment]
Not sure how exactly the merge was done but there were three repositories merged into one (hence the name "Great Merge"). [This](https://forums.vega-strike.org/viewtopic.php?f=53&t=26104&p=169918#p169918) and [this](https://forums.vega-strike.org/viewtopic.php?f=0&t=51534&p=169916#p169916) forumt post may shed some light on the issue. At some point the **vegastrike-taose** repo became the new master and the old master was renamed to **0.5.2-alpha** branch. IIRC, the **alpha** branch still had the correct history. Afterwards it was somehow merged into the new master (**vegastrike-taose**) together with the SVN repo. Somewhere along the way it all got squashed into one commit and the history was lost. The earlier versions of vegastrike are now also not present in the repository. I was planning on identifying the old versions (compute hashes from the SVN repo and search for the corresponding commit in the git repo) and tag them in the git repo but that seems like a moot point now.
I do not know if it is always possible but sometimes you can undelete a deleted branch. If this can be done with the aforementioned lost **alpha** branch then the "Great Merge" might be redone, this time without losing the history - if preserving history is desired, that is.
In any case, thanks for taking the time and looking into this issue, really appreciate it.

**Comment by BenjamenMeyer** [comment]
@crts-crome thanks for the info; I'd like to be able to tag those things too just so we can easily reference them.

If we can find a hash for the branch then it might be able to be "undeleted"... not sure how git handles that but I'll add that to my list of things to check for this.

**Comment by BenjamenMeyer** [comment]
@crts-crome FYI - I created a gitter.im room for folks to collaborate in real-time on this.

https://gitter.im/vegastrike/history-trackers?utm_source=share-link&utm_medium=link&utm_campaign=share-link

**Comment by Loki1950** [comment]
I am also concerned about maintaining credit for our art assets I will be trying to contact them all from our forum db but email addresses do change at whim this will be part of my master file effort besides I'd like to get them active again

**Comment by crts-crome** [comment]
> If we can find a hash for the branch then it might be able to be "undeleted"... 

@BenjamenMeyer 
The hashes were just meant to indentify which commit in the Github repo corresponds to the release branches in the SVN repo, e.g., version 0.5.0, 0.4.3, etc. It was just something I had put on my TODO list for the undamaged Github repo. It will not help with undeleting. Sorry if it was a bit unclear.

What I meant by undeleting is the following:
I made [this branch](https://github.com/crts-crome/Vega-Strike-Engine-Source/tree/fix_ammo_bug) where I fixed a bug. Then I made a PR and after the PR was merged into the main master I deleted the branch with the path in my forked repo. During the course of our conversation here, I revisited that closed PR and noticed that it gave me the option to "undelete" that branch, which I suceessfully did.

I do not know if "undeletion" is only possible for branches that were merged via a PR or if Github keeps a copy of any deleted branch. If the latter is the case then you could look for an option to undelete the missing branch: https://github.com/vegastrike/Vega-Strike-Engine-Source/tree/0.5.2-alpha

It should be similar to my current fork of the repo which also has the history before the Great Merge.

**Comment by BenjamenMeyer** [comment]
@crts-crome there is some stuff that GitHub adds to the repositories; so it might be recoverable there when it's not otherwise able to be. So it may depend on how the merging happened - whether it happened in GitHub or outside of GitHub.

**Comment by crts-crome** [comment]
I found the last intact commit in the [commit history](https://github.com/vegastrike/Vega-Strike-Engine-Source/commits/master?after=af52cc271ddbea7d4dba54215172869b1a4970cc+139), made on Feb 7, 2020: 
https://github.com/vegastrike/Vega-Strike-Engine-Source/tree/28a6a00ab964719fa3b9ded2ba9cfe77886c20b9

That is the last commit that has its history intact.

The next commit (Feb 9, 2020, create modular directory layout) is the first commit of the Great Merge and has no history:
https://github.com/vegastrike/Vega-Strike-Engine-Source/tree/4d6548617677a65f58f62a741243894ded0af590

I have tried to restore it by creating a branch from the last intact commit and then merge that branch with the master branch, but I always end up without history. I also tried the rebase approach but that does not work either, besides I think a rebase changes commit hashes, so this may not be appropriate.

**Comment by BenjamenMeyer** [comment]
@crts-crome thanks for the info; we'll be investigating.

**Comment by stephengtuggy** [comment]
@crts-crome Thanks for doing the legwork on this. Yes, that is concerning.

**Comment by crts-crome** [comment]
Not sure if this is already known, but here is a link that lists the [contributors in the old SVN repository](https://sourceforge.net/p/vegastrike/_members/). Attribution to the **taose** contributors can probably also not be given automatically because Github does not recognize that repository as a fork. The [taose repository](https://github.com/Taose/Vegastrike-taose) has only 85 commits and it is not marked as fork of the main repo. It was probably created as a new project on Github and therefore it is also not possible to pull from it, at least I did not manage to create a PR from it. The contributors in that repo will probably have to go into a Contributors file, too, just like the SVN developers.

**Comment by BenjamenMeyer** [comment]
For the 0.6.0 release we're going to add a file listing the contributors. We may change methodology for later releases but this should satisfy the requirement for the 0.6.x branch.

**Comment by nabaco** [comment]
For the taose repo, we could try to merge it into this one, maybe even into a dummy branch. That should give the proper credit on Github.

**Comment by BenjamenMeyer** [comment]
@nabaco let's give that a try and see if it works. That's a great idea, but we'll need to use a different branch. We'll protect the branch and keep it around for long term as well.

**Comment by BenjamenMeyer** [comment]
Created `taose-master` - a direct copy of the Taose Master branch into our repository to try out @nabaco 's suggestion. We might need to do a merge of it somehow to get the contributions to show up, otherwise their contributions should at least be reflected in that branch.

**Comment by BenjamenMeyer** [comment]
we now have tooling to generate an AUTHORS file and an AUTHORS file in the repository. For 0.6.0 I'll call that sufficient, so moving anything further on this to 0.7.x.

I'd like to see a larger solution but I don't want to hold up 0.6.0 over it either.

**Comment by crts-crome** [comment]
> I am also concerned about maintaining credit for our art assets I will be trying to contact them all from our forum db but email addresses do change at whim this will be part of my master file effort besides I'd like to get them active again

@Loki1950 Have you been able to contact all artists? I would like to close this issue if everyone is OK with the solution so far.

**Comment by Loki1950** [comment]
No luck yet but no reason to keep this open still on my todo list.
