### ISSUE TITLE
Auditing Vegastrike

### ISSUE THREAD

**Issue by LifWirser** [vegastrike/Vega-Strike-Engine-Source#15]

**Comment by LifWirser** [comment]
With my past explorations of the many functions of Vegastrike, I have come to on conclusion this project would greatly benifit from a formal and through auditing of all aspects of the project.
As newly being welcomed to the vegastrike development, I am attempting to lay the foundation of proceedures which if completed will serve this project for many years to come.

For anyone who has been exposed to statisical process control there shouldn't be many surprizes. ISO 9000 series proceedure structure, descibes how to create/check/utilize said proceedures it is mostly common sense. most(all) of current programming standards were created with these types of proceedures.
 The more I consider this,I think a "Vegastrike_Auuit" repository may be a good idea to handle both proceedures and audit results. For now I am just staret new GH issues: Audit code_C++,  Audit code_python, Audit data__databases, Audit data_graphics , audit data_sounds Audit data_Documentation

**Comment by BenjamenMeyer** [comment]
Looks like you created #16 and #17 for the two aspects of this.  I'd suggest creating a Project board for it too to help track progress and finer details.

**Comment by LifWirser** [comment]
while the idae of a "Project board" sounds good I think eack audit topic will eventually need one At present I am busy just getting started on many issues, once I get some current tas compleated I can take a closer look at your "Project board".
 Of course if you feel like volutering some time to the idea ...

**Comment by BenjamenMeyer** [comment]
@LifWirser  I'd love to; but I don't have permissions for that yet.

**Comment by LifWirser** [comment]
> @LifWirser I'd love to; but I don't have permissions for that yet.
> 
If you are loking for some Vegastrike developer GH permission it's not my place to issue them.
However you can still use your GH account to develope some work that the VS team may review.Perhaps answering: What do you want from / offering to the Vegastrike team may be a place to start IMHO

**Comment by BenjamenMeyer** [comment]
@LifWirser if someone on the VS team would give me permissions I'd happily help run project boards. Not sure what permissions are needed for that; but looking to get more involved as I can find time. Right now, project boards are something easy to do for me that can slot in quickly.

**Comment by BenjamenMeyer** [comment]
Thanks @pyramid3d for the perms. I'll organize these Audit issues into a project board to track.

**Comment by BenjamenMeyer** [comment]
@LifWirser I created https://github.com/orgs/vegastrike/projects/1 to track this. I didn't have the permissions to do so directly here in this repo so it's an org wide project, which is probably good since there's 16 repositories so we can use one project for all the repositories. Presently on this repository is linked but we'll probably want to bring the others in as tasks finish up. Please review the description I gave the project board.

To link, just assign each Audit story to the project as you create them.

**Comment by pyramid3d** [comment]
I am not very familiar with the necessary project board permissions.
@BenjamenMeyer, if you could point me to the right permissions I should be able to assign them to you.

**Comment by BenjamenMeyer** [comment]
@pyramid3d I'm going to gander its some form of write permission that's needed; probably across the org as I'd need to be able to modify Issues and PRs to assign them to the Project Board, Milestones, and edit labels.

Reading up on https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/managing-an-individuals-access-to-an-organization-project-board might mean being an `owner`... or alternatively adding me to a team that has write access to all the repositories (https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/repository-permission-levels-for-an-organization#permission-levels-for-repositories-owned-by-an-organization - perhaps Maintain/Write.)

We might need to sync-up via IRC/Slack/etc to have an active discussion to figure it out. This is the first I've tried without being an owner myself.

**Comment by pyramid3d** [comment]
@BenjamenMeyer Thanks for sharing the links. I hope I have figured this out. You should now have the permissions to admin project boards. Do let me know otherwise.

**Comment by BenjamenMeyer** [comment]
@pyramid3d can confirm. Thanks!

**Comment by BenjamenMeyer** [comment]
This seems to be abandoned. We can re-open/create a new issue if we need to do this in the future.
