### ISSUE TITLE
Missing bases, error message: "LOAD FAILED"

### ISSUE THREAD

**Issue by evertvorster** [vegastrike/Vega-Strike-Engine-Source#153]
I have been doing a few cargo runs, to test the game. Right now I am running master, with the Python2 bindings. (Python 3 segfaults later in the game)

In quite a few planetary systems I see "LOAD FAILED" when cycling through major targets, looking for the next jump point. 

Obviously something is wrong/missing. I captured the console output for a normal cargo run, and sure enough, it's teeming with things that are missing. It's amazing that the game runs at all, the fault tolerance of the code is quite exemplary. 

Attaching my console output for anyone that feels like tackling this one. 
[Python2_Load_Failures_Cargo_Mission.txt](https://github.com/vegastrike/Vega-Strike-Engine-Source/files/4835335/Python2_Load_Failures_Cargo_Mission.txt)

**Comment by BenjamenMeyer** [comment]
Set a later milestone as the game works.

I can also confirm seeing this and other similar behavior.

**Comment by evertvorster** [comment]
Agreed on getting 0.6.x out the door with this bug, as it does not massively detract from gameplay. I'll poke at it when I have a chance. :)

**Comment by stephengtuggy** [comment]
@evertvorster Is this fixed as of your PR #182 ?

**Comment by evertvorster** [comment]
This is fixed completely.
