### ISSUE TITLE
Text is off the buttons in the nav computer

### ISSUE THREAD

**Issue by nabaco** [vegastrike/Vega-Strike-Engine-Source#159]
I'm filling this as to not forget, but I'm sure someone can attach a screenshot to better describe what I mean
When your enter the navigation computer, there are buttons for different maps on the right, and the text is not on the actual buttons, but rather skewered to the left.
It's both doesn't look good, and confuses the player where to press, the text or the button

**Comment by evertvorster** [comment]
I put a PR on Assets-Production that just gets rid of these buttons altogether.
Buttons are not a thing anymore, if you look at any modern UI. I don't mind the look of it, at least it is not confusing.

**Comment by BenjamenMeyer** [comment]
@Loki1950 can you confirm this should be an issue in the Assets?

**Comment by Loki1950** [comment]
The whole nav computer is very tacky and not working as intended.

**Comment by BenjamenMeyer** [comment]
@Loki1950 okay; shall we repurpose this around rebuilding the nav computer to work better?

**Comment by Loki1950** [comment]
The while we are looking at anyway yes it would be a good idea the interface is not very intuitive apart from the lac of documentation.

**Comment by evertvorster** [comment]
The nav computer does not have any more buttons, so this bug is moot.
