### ISSUE TITLE
Skip CI tag blocks merge

### ISSUE THREAD

**Issue by nabaco** [vegastrike/Vega-Strike-Engine-Source#164]
We configured in our repository that Travis-CI checks will be a mandatory condition for a PR to be merged. The issue is, when a contributor adds a [skip ci] tag into his commit (say, when editing a README), a build is not issued (as expected), but Github is still expecting for a status update from Travis-CI, which blocks the PR from being merged.

Example: https://github.com/vegastrike/Vega-Strike-Engine-Source/pull/163

I have issued a ticket on Travis-CI: https://travis-ci.community/t/github-pr-blocked-due-to-skip-ci-message/9278

But I was thinking, maybe we should change a bit our configuration. Since master is a protected branch anyway, and there is a limited number of people who can merge PRs to master, maybe we can make Travis-CI non-mandatory (configuration-wise only :) ), and instruct all the "Mergers" accordingly.

**Comment by BenjamenMeyer** [comment]
Personally I would be more in favor of disallowing the Skip tag. I understand why some want to use it, but I don't think we're so large or long in builds that we must use it.

**Comment by nabaco** [comment]
OK, sounds like an option too.
I personally like it to not burden Travis-CI when not needed, as we are receiving this as a free resource :)

**Comment by Loki1950** [comment]
As for Travis-CI being free have you seen all the robo pulls we are getting ;) this is not my area of expertise so I will Ben's lead here.

**Comment by BenjamenMeyer** [comment]
We're no longer using Travis-CI so closing this.
