### ISSUE TITLE
basecomputer.cpp uses memory-unsafe sprintf, in multiple places

### ISSUE THREAD

**Issue by stephengtuggy** [vegastrike/Vega-Strike-Engine-Source#168]
See https://stackoverflow.com/questions/3662899/understanding-the-dangers-of-sprintf .

Alternatives include:
- `snprintf`
- `boost::format` (which I think I would prefer)

**Comment by BenjamenMeyer** [comment]
As Microsoft isn't very compatible with the standard snprintf (gives a warning because it's not their special "secure" variant) I'll favor the Boost Format version so we minimize no platform changes
