### ISSUE TITLE
Audit code_python

### ISSUE THREAD

**Issue by LifWirser** [vegastrike/Vega-Strike-Engine-Source#17]

**Comment by LifWirser** [comment]
This issue is fir finding and correcting Python issues. Also dicussions on how to test and  measure performance of Python code.

some issues to be discussed here are
- finding unused/ obsolete/depreciated  Python code/files
- correcting compile errors/warnings
-incorperating  improvments

**Comment by BenjamenMeyer** [comment]
This seems to be abandoned. We can re-open/create a new issue if we need to do this in the future.
