### ISSUE TITLE
Enhancement: Use GitHub's normalized script pattern?

### ISSUE THREAD

**Issue by stephengtuggy** [vegastrike/Vega-Strike-Engine-Source#176]
I suggest that we use GitHub's normalized script pattern for open source projects, found [here](https://github.com/github/scripts-to-rule-them-all). This could make it easier for new contributors to get started with VS.

Not all of the scripts would apply -- like `server`, for instance -- but many would. I.e., the `sh` directory would become `script`. `clean` would become `setup`. And perhaps `vsbuild.sh` would just become `build`?

What do you guys think?

**Comment by nabaco** [comment]
Sounds good to me. Let's open a PR with the changes. We could use this occasion to clean out old irrelevant scripts.

**Comment by BenjamenMeyer** [comment]
Certainly work looking into.
