### ISSUE TITLE
Change mesh_tool binary name to vegastrike's naming convention

### ISSUE THREAD

**Issue by nabaco** [vegastrike/Vega-Strike-Engine-Source#178]
I just released that mesh_tools gets installed in the system along with other binaries, and in that case we want it's name to be explicitly identified with vegastrike and not as some general utility.
Unless someone thinks other wise, I we should change its name to something like "vegamesh" or "vega-meshtool".

**Comment by evertvorster** [comment]
vegastrike-meshtool

**Comment by nabaco** [comment]
Agreed. I'll try to open a PR soon, the change should be trivial

**Comment by BenjamenMeyer** [comment]
@nabaco I'll look into adding something quickly for 0.7.x; should be a simple rename of the binary for now.

**Comment by BenjamenMeyer** [comment]
So while testing this and validating the packages I noticed that the man pages were not getting packaged at all either. I'm going to fix that as part of my work.

@Loki1950 @nabaco @evertvorster Question: I also noticed we are building several other files:
-- Build files have been written to: /home/bmeyer/Devel/opensource/vegastrike/Vega-Strike-Engine-Source/build_0.7.x
[ 10%] Built target OPcollide
[ 40%] Built target engine_com
[ 92%] Built target vegastrike
[ 94%] Built target vegasettings
[ 99%] Built target vegastrike-meshtool
[100%] Built target replace
[100%] Built target asteroidgen
[100%] Built target trisort

Do we need trisort, astroidgen, replace, engine_com, OPcollide? should they be included in the packaging? Do we need to rename them too? Please advise.

I'm making the changes for 0.7.x; it'll easily port to 0.8.x.

**Comment by stephengtuggy** [comment]
The outputs of `OPcollide` and `engine_com` get bundled up as part of the `vegastrike` binary, among other things, I believe. In other words, they are libraries that contribute to the final result.

**Comment by BenjamenMeyer** [comment]
@stephengtuggy they look to be standalone binaries:
```
Vega-Strike-Engine-Source/build_0.7.x$ ls objconv/ -lah
total 12M
drwxrwxr-x 3 bmeyer bmeyer 4.0K Jan 27 02:18 .
drwxrwxr-x 7 bmeyer bmeyer 4.0K Jan 27 02:30 ..
-rwxrwxr-x 1 bmeyer bmeyer 276K Jan 27 01:44 asteroidgen
drwxrwxr-x 6 bmeyer bmeyer 4.0K Jan 27 02:18 CMakeFiles
-rw-rw-r-- 1 bmeyer bmeyer 2.1K Jan 27 00:41 cmake_install.cmake
-rw-rw-r-- 1 bmeyer bmeyer  36K Jan 27 00:41 Makefile
-rwxrwxr-x 1 bmeyer bmeyer 195K Jan 27 01:43 replace
-rwxrwxr-x 1 bmeyer bmeyer 484K Jan 27 01:44 trisort
-rwxrwxr-x 1 bmeyer bmeyer  11M Jan 27 01:43 vegastrike-meshtool
```
but if the build system re-uses them to do stuff that's fine. We might want to add a `vs-builderenv-` prefix to them in such case just to make sure we know for the future. Just a thought.

**Comment by stephengtuggy** [comment]
On another subject, I think vega-meshtool would be better than vegastrike-meshtool. The latter name has too many characters in common with the actual game engine.

**Comment by BenjamenMeyer** [comment]
@stephengtuggy I'm good either way - we just need to create some kind of naming convention and follow it.

**Comment by BenjamenMeyer** [comment]
Proposal:
- All distributed binaries should follow the pattern `vega*`
- All non-distributed binaries used in the build system should follow the pattern `vs-buildenv-*`
- All libraries should be `libvegastrike-*`
- This should be documented in the [Wiki](https://github.com/vegastrike/Vega-Strike-Engine-Source/wiki)

Are there any others?

**Comment by BenjamenMeyer** [comment]
Just realized I accidentally closed this before...must have hit the wrong button with the last comment. Sorry about that.

**Comment by BenjamenMeyer** [comment]
I've got a local branch that will implement the changes per https://github.com/vegastrike/Vega-Strike-Engine-Source/issues/178#issuecomment-769155620; I should have the PR up in the next day or so.

**Comment by evertvorster** [comment]
Just don't forget to also change the file name in the CMakeLists.txt, please.

**Comment by BenjamenMeyer** [comment]
@evertvorster I'm doing a full build, then packaging, and checking the packages for the new names and files.

**Comment by BenjamenMeyer** [comment]
Binaries have been renamed in master and in 0.7.x
