### ISSUE TITLE
Audit data__databases

### ISSUE THREAD

**Issue by LifWirser** [vegastrike/Vega-Strike-Engine-Source#18]
This area is for creating/maintaining  Vegastrike databases *.csv files.

Amoung the topics here will deal with are
creating/deleting/editing both database files adn indiviual entries
verifying all needed feilds are correct for all database entries
proper linkage to respective C++/Python code
testing database  whencreating/deleting/editing  via Vegastrike apps

**Comment by BenjamenMeyer** [comment]
This seems to be abandoned. We can re-open/create a new issue if we need to do this in the future.
