### ISSUE TITLE
Audit data_graphics

### ISSUE THREAD

**Issue by LifWirser** [vegastrike/Vega-Strike-Engine-Source#19]
This area is for creating/maintaining Vegastrike Graphics files.

Amoung the topics here will deal with are
creating/deleting/editing graphic/video files and indiviual entries
verifying all needed resolutions are correct for all graphic entries
proper linkage to respective C++/Python code
testing database when creating/deleting/editing via Vegastrike apps

**Comment by BenjamenMeyer** [comment]
This seems to be abandoned. We can re-open/create a new issue if we need to do this in the future.
