### ISSUE TITLE
audit data_sounds

### ISSUE THREAD

**Issue by LifWirser** [vegastrike/Vega-Strike-Engine-Source#20]
This area is for creating/maintaining Vegastrike sound files.

Amoung the topics here will deal with are
creating/deleting/editing  sound files 
verifying all needed sound are correct for all sound sample rates
proper linkage to respective C++/Python code and databases
testing sound when creating/deleting/editing via Vegastrike apps

**Comment by BenjamenMeyer** [comment]
This seems to be abandoned. We can re-open/create a new issue if we need to do this in the future.
