### ISSUE TITLE
Compile on Windows/mingw32; errors in engine/src/gfx/vsimage.h

### ISSUE THREAD

**Issue by stamasd** [vegastrike/Vega-Strike-Engine-Source#208]
Attempting to compile the current code in Windows under mingw32. I managed to get it configured in cmake, and have worked around boost not finding some headers. Now I get the following compile error (see attached log)
[make.2.txt](https://github.com/vegastrike/Vega-Strike-Engine-Source/files/5001028/make.2.txt)

**Comment by stamasd** [comment]
Full logs.
[CMakeOutput.log.txt](https://github.com/vegastrike/Vega-Strike-Engine-Source/files/5001049/CMakeOutput.log.txt)
[CMakeError.log.txt](https://github.com/vegastrike/Vega-Strike-Engine-Source/files/5001051/CMakeError.log.txt)
[CMakeCache.txt](https://github.com/vegastrike/Vega-Strike-Engine-Source/files/5001052/CMakeCache.txt)

**Comment by BenjamenMeyer** [comment]
So, gcc 10 32-bit... I think you're still missing some dependencies, I see an error around finding `lstat`.

It's likely that by using MSYS/MinGW you're in a weird area of support. Officially we're supporting VS2017 and native Windows builds. If you can get it work great.

Assigning to @nabaco as he has the most familiarity with building on WIndows in the new group of devs.

**Comment by BenjamenMeyer** [comment]
@stamasd can you do the following:
```
$ ./sh/clean
$ typescript build-0000
$ mkdir build-mingw
$ cd build-mingw
$ cmake ../engine
$ make
```
Before doing anything with `cmake-gui`  or `ccmake` let's see what that looks like - should be a completely fresh build.
Thanks!

**Comment by stamasd** [comment]
Okay. There is no cmake-gui on mingw anyway. Trying now.

**Comment by stephengtuggy** [comment]
In build-0000.txt, I see that right off the bat, CMake says:

```text
System is unknown to cmake, create:
Platform/MINGW32_NT-6.1-7601 to use this system, please post your config file on discourse.cmake.org so it can be added to cmake
```

That doesn't sound promising. It sounds like CMake doesn't support MinGW, at least on this Windows version.

**Comment by stephengtuggy** [comment]
@stamasd you say you got CMake configured anyway? That's pretty impressive. Maybe post your config file, like they suggest.

**Comment by stephengtuggy** [comment]
Okay, so part of what you were running into was Issue #154 , where nonexistent build config RelWithDebInfo was the default. If you get the latest from master, that should now be fixed.

**Comment by stamasd** [comment]
I was busy at work for the past few days, but now I have decided to restart this from scratch. Fresh install of msys2 and fresh checkout of the VS code as of 8/1/20. One issue I had with msys2/mingw was that the current version of boost (1.73) has dropped support for python2. I had to find and install an older version of boost (1.71.0 as of 11/2019) which still retained it. With that and some manual editing of paths to includes and libraries in ccmake, I managed again to get the VS engine configured. I'm attaching below the cmakecache and makefile generated. 

But again on compiling it runs into errors. I'm also attaching a console capture of that.
[CMakeCache.txt](https://github.com/vegastrike/Vega-Strike-Engine-Source/files/5015196/CMakeCache.txt)
[Makefile.txt](https://github.com/vegastrike/Vega-Strike-Engine-Source/files/5015197/Makefile.txt)
[typescript.txt](https://github.com/vegastrike/Vega-Strike-Engine-Source/files/5015198/typescript.txt)

**Comment by stephengtuggy** [comment]
I'm wondering if this would be relevant: https://github.com/micropython/micropython/issues/4835

Do you have an mkrules.mk file anywhere?

**Comment by stamasd** [comment]
No mkrules.mk

**Comment by stephengtuggy** [comment]
Shoot.

Well, you're running into issues between 32-bit and 64-bit, I can tell you that much. But I don't know how to resolve it at this point.

**Comment by stamasd** [comment]
I get very similar errors with mingw64.

**Comment by stamasd** [comment]
Also 
s@s-PC MSYS ~
$ find / -iname 'stddef.h'
/mingw32/i686-w64-mingw32/include/stddef.h
/mingw32/lib/gcc/i686-w64-mingw32/10.2.0/include/stddef.h
/mingw64/lib/gcc/x86_64-w64-mingw32/10.2.0/include/stddef.h
/mingw64/x86_64-w64-mingw32/include/stddef.h
/usr/lib/gcc/x86_64-pc-msys/9.3.0/include/stddef.h
find: failed to read file names from file system at or below ‘/’: No such file or directory

**Comment by stephengtuggy** [comment]
@stamasd Let's try an experiment. Try editing your CMakeLists.txt, and under [INCLUDE_DIRECTORIES](https://github.com/vegastrike/Vega-Strike-Engine-Source/blob/403ec35644e20e135bcec1f42687c9325597e87f/engine/CMakeLists.txt#L37), add as the first entry: 

```
/mingw32/i686-w64-mingw32/include
```

Or `C:/mingw32/i686-w64-mingw32/include`, whichever you think is more likely to work. Then try cleaning the project and building it again, and see what you get.

**Comment by nabaco** [comment]
Hi @stamasd, just out of curiosity, why are you trying to compile using MingW32 instead of VS2017?
Since MingW32 is not supported by CMake, I think it'll more efficient right now to try and work together on the VS2017 compilation.

**Comment by stamasd** [comment]
I haven't had power or internet for the past 6 days... catching up now.
nabaco: it's primarily because I'm curious if it's possible to have an open-source development model on Windows for the code. Also saying that mingw is not supported by cmake is not entirely true, I was able to configure the code and generate the makefiles on mingw with cmake with minimal manual edits of the paths involved. Nost of the configuration process went on automatically as intended.

**Comment by stamasd** [comment]
> 
> 
> @stamasd Let's try an experiment. Try editing your CMakeLists.txt, and under [INCLUDE_DIRECTORIES](https://github.com/vegastrike/Vega-Strike-Engine-Source/blob/403ec35644e20e135bcec1f42687c9325597e87f/engine/CMakeLists.txt#L37), add as the first entry:
> 
> ```
> /mingw32/i686-w64-mingw32/include
> ```
> 
> Or `C:/mingw32/i686-w64-mingw32/include`, whichever you think is more likely to work. Then try cleaning the project and building it again, and see what you get.

See the attacjed output. After editing I redid the cmake configure in a brand new build directory, for clean
[makeout.txt](https://github.com/vegastrike/Vega-Strike-Engine-Source/files/5047459/makeout.txt)
liness.

**Comment by stephengtuggy** [comment]
@stamasd Yeah, that's not working any better, is it?

The standard header files are throwing errors and conflicting with one another. That's not a good sign.

To be honest, I'm not sure that this mingw experiment is worth the trouble. VS2017 would probably be easier. Or clang on straight Windows, perhaps.

**Comment by stamasd** [comment]
I don't have VS2017 and can't download now, my internet is still down (cell phone connection only), maybe when it's restored in a few days. I have VS2015 installed, maybe I should give that one a go.

**Comment by BenjamenMeyer** [comment]
@stamasd VS2015 isn't fully compliant IIRC against the version of C++/C we're using so you may run into other issues, but you're welcome to give it a shot. We've standardized on VS2017 for Windows for the moment as VS2019 has issues too that we're just not ready to tackle.

**Comment by BenjamenMeyer** [comment]
@stephengtuggy is this relevant any more since we now have a build process for Windows again?

**Comment by stephengtuggy** [comment]
@BenjamenMeyer I would say that this issue probably still exists, and should probably be addressed at some point. However, now that we have the code building on Windows again, this issue becomes a low priority.

**Comment by BenjamenMeyer** [comment]
@stephengtuggy I would gander than an official Win32 build would be superior tia mingw/mingsys build. Let's support one or the other, not both - and I'd lean towards the Win32 build as the mingw tooling just adds complexity that we don't need.

**Comment by stephengtuggy** [comment]
@BenjamenMeyer Okay. So close as "Won't Fix"?

**Comment by BenjamenMeyer** [comment]
Please use the official Windows builds that are native to Windows.
