### ISSUE TITLE
Audit data_Documentation

### ISSUE THREAD

**Issue by LifWirser** [vegastrike/Vega-Strike-Engine-Source#21]
This area is for creating/maintaining Vegastrike documentation files.

Amoung the topics here will deal with are
ensure all game documents are correct and up to date
in proposed Localized additions tranlation are correct
maintaintance of all proceedur documents

**Comment by BenjamenMeyer** [comment]
This seems to be abandoned. We can re-open/create a new issue if we need to do this in the future.
