### ISSUE TITLE
Segfault on buying certain ships

### ISSUE THREAD

**Issue by stephengtuggy** [vegastrike/Vega-Strike-Engine-Source#218]
When you try to buy certain ships in the game -- either right away, or when you go to view them on the landing pad -- the game segfaults.

Ships that work:
Mule, Dostoevsky, Gawain, Progeny, Dodo, Convolution, Kiergard, Ancestor, Admonisher.

Ships that do not work (they make the game crash):
Determinant, Derivative, Vendetta, Hyena, Sickle, Robin.

**Comment by BenjamenMeyer** [comment]
Question: should this be part of the Assets? Or Engine? It sounds like it might be an assets issue, so we should probably move it to Asset Masters.

**Comment by evertvorster** [comment]
@BenjamenMeyer this should definitely be engine. 
No amount of bad data should cause a segfault. Should we find a workaround in Assets, I'll raise the issue there. 

Some more observations on this bug:
Actually buying these ships works, it is _only_ when they are _displayed in the base_ that the engine segfaults. 

I have seen these ships zooming around the universe, so the game engine obviously has no issue drawing the crashing ships normally. 

I trawled through units.csv and the meshes directory to look for something obvious that would set the ships that cause a segfault apart from the ships that don't. So far nothing has jumped out at me and I will have to look at it in closer detail. Once I find the key, it will enable us to harden the engine against this bad data.

**Comment by evertvorster** [comment]
Poking at this some more... 
At the moment it does not seem to make a difference whether the ship is in stock trim, or some modification. ie: if "whatever.milspec" crashes, "whatever.stock" will also crash the engine. 

Right now I am trying to swap out the meshes from a crashing unit to a working unit to see if it's related to the mesh file, but so far have had no luck, as the renamed meshes simply refuse to load, not causing a segfault.

**Comment by evertvorster** [comment]
Tested with various branches of the engine, from the 2020 (pre-0.6.0), 0.6.0 and current master all have the same bug.

**Comment by evertvorster** [comment]
I have now tested with a Assets with a split units.csv, and the bug is still present there, too. ;)

**Comment by evertvorster** [comment]
More testing... 
I was able to load the vigilance.bfxm as admonisher.bfxm, so it is not the mesh file that is making it crash.

**Comment by stephengtuggy** [comment]
> I have now tested with a Assets with a split units.csv, and the bug is still present there, too. ;)

Wow, really? I wonder why we didn't notice it before, then.

**Comment by evertvorster** [comment]
OK, I renamed units/vessels/Admonisher to a backup, then renamed units/vessels/Vigilance to Admonisher, then renamed the files in that directory to admonisher.bfxm and copied in admonisher-shield.bfxm from the backup directory. 

I was able to buy this "Admonisher" that is actually all the data from a "Vigilance"

The game did not crash.
It then follows that it is definitely not the meshes that is causing the segfault. 
Also, capitalization does not seem to matter.

What is it that is making these ships crash? What is the common denominator? Any guesses?

**Comment by evertvorster** [comment]
Just FYI, the game segfaults just as hard on Python2 bindings, rather than the Python 3 that I am normally running on

**Comment by evertvorster** [comment]
> > I have now tested with a Assets with a split units.csv, and the bug is still present there, too. ;)
> 
> Wow, really? I wonder why we didn't notice it before, then.

Admittedly, this is off a save file that was made with the unified csv. Maybe I should start a new game on the split, hack it for enough cash, and see if the issue is still present

**Comment by evertvorster** [comment]
OK, doubly confirmed now. I started a new campaign on a split csv dataset. Saved the file and hacked it to give me a little cash to buy nice ships. Flew over to Atraxia, and tried to buy a Vigilance.
Instant segfault, so the issue is definitely there.
