### ISSUE TITLE
BUG: Compile failure from /sh/vsbuild.sh

### ISSUE THREAD

**Issue by LifWirser** [vegastrike/Vega-Strike-Engine-Source#22]

**Comment by LifWirser** [comment]
Occurred on Intel core2 (64 bit) , Debian 9, mesa graphics from Vega-Strike-Engine-Source-0.5.3.zip

As per ~ Vega-Strike-Engine-Source-0.5.3/README.md 
I executed ~/Vega-Strike-Engine-Source-0.5.3 /sh/vsbuild.sh which ended with the following
`[100%] Linking CXX executable vegastrike
[100%] Built target vegastrike
cp: cannot stat {edited_home_dir}/build/Vega-Strike-Engine-Source-0.5.3/build/{vegastrike,vegaserver,setup/vssetup,objconv/mesh_tool}': No such file or directory`
In /bin directory where the bianaries were to be put was empty, they were found in  
~Vega-Strike-Engine-Source-0.5.3/build .
Further investigation revealed that ~/Vega-Strike-Engine-Source-0.5.3 /sh/vsbuild.sh  was writtenfor the bash shell but Debian default shell is dash is Dash

By changing the first `#!/bin/sh` to `#!/bin/bash` the script successfully completed

**Comment by stephengtuggy** [comment]
Hmm. Interesting. Good catch. So that first line is the only one that needs to change?

**Comment by LifWirser** [comment]
Actually it only needs to be changed if your.bin/sh (whish is usually a link points to a shell not completely "bash compliant" but to be safe I changed it on the repo so It can be closed but I left it open for now

**Comment by nabaco** [comment]
Issue was solved, I think we can close this bug

**Comment by stephengtuggy** [comment]
I believe this bug has been fixed, and should be closed. Any objections?

**Comment by BenjamenMeyer** [comment]
If we can verify it's fixed then yes please close it.

**Comment by stephengtuggy** [comment]
Fixed. At least in this one file. Other scripts may still need to have the same change made. (Mark to run with `bash`, not just plain `sh`.)
