### ISSUE TITLE
Compiler (gcc 10.1.0) warning in cmd/ai/hard_coded_scripts.cpp

### ISSUE THREAD

**Issue by evertvorster** [vegastrike/Vega-Strike-Engine-Source#226]
[  3%] Building CXX object CMakeFiles/engine_com.dir/src/cmd/ai/hard_coded_scripts.cpp.o
/home/evert/vsmod/git/Vega-Strike-Engine-Source/engine/src/cmd/ai/hard_coded_scripts.cpp: In function 'void Takeoff(Order*, Unit*)':
/home/evert/vsmod/git/Vega-Strike-Engine-Source/engine/src/cmd/ai/hard_coded_scripts.cpp:892:51: warning: enum constant in boolean context [-Wint-in-bool-context]
  892 |     un->Fire( (weapon_info::LIGHT || weapon_info::MEDIUM), false );
      |                                                   ^~~~~~
[  3%] Building CXX object CMakeFiles/engine_com.dir/src/cmd/ai/ikarus.cpp.o

Looks like it's complaining about the boolean operator being used on enums.

**Comment by stephengtuggy** [comment]
Hmm. I'm not sure what this one is supposed to be.
