### ISSUE TITLE
Compiler (gcc 10.1.0) warning in: src/cmd/damageable.cpp

### ISSUE THREAD

**Issue by evertvorster** [vegastrike/Vega-Strike-Engine-Source#232]
```
[  0%] Building CXX object CMakeFiles/engine_com.dir/src/cmd/damageable.cpp.o
/home/evert/vsmod/git/Vega-Strike-Engine-Source/engine/src/cmd/damageable.cpp: In static member function 'static float Damageable::totalShieldEnergyCapacitance(const Shield&)':
/home/evert/vsmod/git/Vega-Strike-Engine-Source/engine/src/cmd/damageable.cpp:354:27: warning: '*' in boolean context, suggest '&&' instead [-Wint-in-bool-context]
  354 |     return shieldenergycap*use_max_shield_value ? totalShieldVal( shield ) : currentTotalShieldVal( shield );
      |            ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~
[  1%] Building CXX object CMakeFiles/engine_com.dir/src/cmd/drawable.cpp.o
```

Why does the compiler think that these are boolean?

**Comment by evertvorster** [comment]
@royfalk Did you just create this file?
The warning there is not too clear. On line 354 there is an asterisk that github display code is eating, and the compiler is suggesting we swap it with an &&... is this the correct thing to do?

**Comment by stephengtuggy** [comment]
@evertvorster There. Fixed the GitHub display for you, by enclosing the warning in backticks.

I'm pretty sure that line of code should become:

```
     return shieldenergycap * ( use_max_shield_value ? totalShieldVal( shield ) : currentTotalShieldVal( shield ) );
```

In other words, the original coder made an incorrect assumption about operator precedence. We fix it by adding parentheses around the part that should be evaluated first.

**Comment by stephengtuggy** [comment]
And @royfalk created this file, but the code there came from someone else originally. Roy just migrated it to a different file, I believe.

**Comment by evertvorster** [comment]
So, he just cut 'n pasted it?
