### ISSUE TITLE
Compiler (gcc 10.1.0) warning in: src/cmd/drawable.cpp

### ISSUE THREAD

**Issue by evertvorster** [vegastrike/Vega-Strike-Engine-Source#233]
[  1%] Building CXX object CMakeFiles/engine_com.dir/src/cmd/drawable.cpp.o
/home/evert/vsmod/git/Vega-Strike-Engine-Source/engine/src/cmd/drawable.cpp: In member function 'bool Drawable::DrawableInit(const char*, int, Flightgroup*, const char*)':
/home/evert/vsmod/git/Vega-Strike-Engine-Source/engine/src/cmd/drawable.cpp:30:5: warning: this 'if' clause does not guard... [-Wmisleading-indentation]
   30 |     if(animationExt)
      |     ^~
/home/evert/vsmod/git/Vega-Strike-Engine-Source/engine/src/cmd/drawable.cpp:33:2: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the 'if'
   33 |  std::vector< Mesh* > *meshes = new vector<Mesh *>();
      |  ^~~
/home/evert/vsmod/git/Vega-Strike-Engine-Source/engine/src/cmd/drawable.cpp: In member function 'void Drawable::AnimationStep()':
/home/evert/vsmod/git/Vega-Strike-Engine-Source/engine/src/cmd/drawable.cpp:120:9: warning: this 'if' clause does not guard... [-Wmisleading-indentation]
  120 |         if(nextactiveMesh >= vecAnimations.at(activeAnimation)->size())
      |         ^~
/home/evert/vsmod/git/Vega-Strike-Engine-Source/engine/src/cmd/drawable.cpp:123:13: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the 'if'
  123 |             if(loopCount > 0)
      |             ^~
/home/evert/vsmod/git/Vega-Strike-Engine-Source/engine/src/cmd/drawable.cpp:103:13: warning: unused variable 'numvold' [-Wunused-variable]
  103 |         int numvold = 0;
      |             ^~~~~~~
/home/evert/vsmod/git/Vega-Strike-Engine-Source/engine/src/cmd/drawable.cpp:104:13: warning: unused variable 'numvertices' [-Wunused-variable]
  104 |         int numvertices = 0;
      |             ^~~~~~~~~~~
[  1%] Building CXX object CMakeFiles/engine_com.dir/src/cmd/movable.cpp.o

Hmm... this one looks fairly easy. :)

**Comment by evertvorster** [comment]
Partially fixing this one as well, first removing the misleading indentation. 
Not sure what to do about the unused variables. They are unused because of ifdef DEBUG_MESH_ANI, not sure where that is defined...

**Comment by stephengtuggy** [comment]
@evertvorster I'm not sure that removing the misleading indentation is the correct approach. Those lines should perhaps be moved inside the if blocks referenced. I'd have to look at the context to get a better idea which solution is correct in each of these cases.
