### ISSUE TITLE
Compiler (gcc 10.1.0) warning in: src/star_system_xml.cpp

### ISSUE THREAD

**Issue by evertvorster** [vegastrike/Vega-Strike-Engine-Source#239]
[  0%] Building CXX object CMakeFiles/engine_com.dir/src/star_system_xml.cpp.o
/home/evert/vsmod/git/Vega-Strike-Engine-Source/engine/src/star_system_xml.cpp:124:13: warning: 'bool ConfigCondition(const string&)' defined but not used [-Wunused-function]
  124 | static bool ConfigCondition( const string &cond )
      |             ^~~~~~~~~~~~~~~
[  0%] Building CXX object CMakeFiles/engine_com.dir/src/stardate.cpp.o

Oooh, this one should be easy, too.

**Comment by evertvorster** [comment]
I thought it was going to be easy, but it seems that there is a lot hanging off this unused variable. If it's not used, do we get rid of the entire block, or are we assuming that there are side effects that need to be kept?

**Comment by stephengtuggy** [comment]
@evertvorster This is actually a function. See the parentheses after the name, and the curly braces { } on the following lines?

Why don't we just comment this function out for now. There is a spot in system_factory.cpp where it used to be used, but that is commented out now too.

**Comment by evertvorster** [comment]
OK, commented it out now, let's hope this is dead code. :)

**Comment by stephengtuggy** [comment]
Turns out that `ConfigCondition()` _was_ used prior to #181 . Hmm. We might want to look at this a little more closely.

On the 0.6.x branch, `ConfigCondition()` is used [here](https://github.com/vegastrike/Vega-Strike-Engine-Source/blob/3804519b2efd7215ec8a38c048f10dd25469f604/engine/src/star_system_xml.cpp#L1245) and [here](https://github.com/vegastrike/Vega-Strike-Engine-Source/blob/3804519b2efd7215ec8a38c048f10dd25469f604/engine/src/star_system_xml.cpp#L1352). I don't this function should have been refactored out. How do we know that the condition was never met?

**Comment by evertvorster** [comment]
@stephengtuggy I agree that it was used before #181. Seeing as how this function has almost been factored out completely, can we ask @royfalk to weigh in on this?
@royfalk is this function really necessary? Could you maybe tell us what it was used for, and why almost all the use cases for it has been factored out in master?

I, for one, would like to get rid of it, as the compiler is complaining that it is not used anymore.

**Comment by royfalk** [comment]
So, condition is one of the xml keys possible within a system file. I believe I've left it in place, as I was black box refactoring without a spec. Gut feeling, we can probably remove all of it and it's not used. Something you can do is check if data is using it. Also, check with the person maintaing PU if it's used there. FInally, perhaps @Loki1950  can shed some light on them.

**Comment by stephengtuggy** [comment]
Perhaps we can comment out `ConfigCondition()` for now, but let's not delete it entirely, as we will probably want to use it again at some point in the near future.

**Comment by evertvorster** [comment]
fixed with #275
