### ISSUE TITLE
Compiler (gcc 10.1.0) warning in: src/cmd/base_interface.cpp

### ISSUE THREAD

**Issue by evertvorster** [vegastrike/Vega-Strike-Engine-Source#250]
[ 49%] Building CXX object CMakeFiles/vegastrike.dir/src/cmd/base_interface.cpp.o
/home/evert/vsmod/git/Vega-Strike-Engine-Source/engine/src/cmd/base_interface.cpp: In member function 'virtual void BaseInterface::Room::Launch::Click(BaseInterface*, float, float, int, int)':
/home/evert/vsmod/git/Vega-Strike-Engine-Source/engine/src/cmd/base_interface.cpp:1233:36: warning: self-comparison always evaluates to true [-Wtautological-compare]
 1233 |                 if (playa->faction == playa->faction)
      |                     ~~~~~~~~~~~~~~ ^~ ~~~~~~~~~~~~~~
[ 49%] Building CXX object CMakeFiles/vegastrike.dir/src/cmd/base_util.cpp.o

**Comment by vincele** [comment]
Here is a PR for that one
https://github.com/vegastrike/Vega-Strike-Engine-Source/pull/269
