### ISSUE TITLE
Compiler (gcc 10.1.0) warning in: src/cmd/music.cpp

### ISSUE THREAD

**Issue by evertvorster** [vegastrike/Vega-Strike-Engine-Source#251]
[ 44%] Building CXX object CMakeFiles/vegastrike.dir/src/cmd/music.cpp.o
/home/evert/vsmod/git/Vega-Strike-Engine-Source/engine/src/cmd/music.cpp: In member function 'void Music::_SkipRandSong(int, int)':
/home/evert/vsmod/git/Vega-Strike-Engine-Source/engine/src/cmd/music.cpp:509:5: warning: 'nonnull' argument 'this' compared to NULL [-Wnonnull-compare]
  509 |     if (this != NULL) {
      |     ^~
[ 44%] Building CXX object CMakeFiles/vegastrike.dir/src/cmd/nebula.cpp.o

**Comment by stephengtuggy** [comment]
This appears to have been fixed in #275 . Closing.
