### ISSUE TITLE
Specify the License

### ISSUE THREAD

**Issue by BenjamenMeyer** [vegastrike/Vega-Strike-Engine-Source#26]
Good open source repositories contain a file in the root called LICENSE that specifies what license they fall under. This enables everyone to know if the source is compatible with other libraries, projects, etc. Git Hub has an easy mechanism to set a known license from its list. I assume there is already one for VegaStrike and we just need to find it and put it in the right location.

This will also help enable people to contribute.

**Comment by BenjamenMeyer** [comment]
This can get filed with the Community Audit, or work that comes out of that.

**Comment by BenjamenMeyer** [comment]
Found it under `doc`... Propose to move it to the root of the repository.

**Comment by pyramid3d** [comment]
Feel free. ;-)
