### ISSUE TITLE
Provide a Contributors Guideline...

### ISSUE THREAD

**Issue by BenjamenMeyer** [vegastrike/Vega-Strike-Engine-Source#27]
It's good practice on GitHub to provide potential contributors with guidance in a file called CONTRIBUTING. This can be anything from how to ask questions, to where to find help, how we want issues filed, etc.

For reference: https://help.github.com/en/github/building-a-strong-community/setting-guidelines-for-repository-contributors

This can get filed with the Community Audit.

**Comment by pyramid3d** [comment]
The original [The Vega Strike Contributor's Guide](https://wiki.vega-strike.org/HowTo:Contribute) may get you started, though it hasn't been updated in ages.

**Comment by LifWirser** [comment]
As I have been motivated,I have been working on an outline for coding standards on my own. It is still a work in progress, so be warned.
[VS_Standards-Outline-0.1,txt](https://github.com/vegastrike/Vega-Strike-Engine-Source/files/4399861/VS_Standards-Outline-0.1.txt)

**Comment by BenjamenMeyer** [comment]
@LifWirser that's be a great edition to the Wiki section.

**Comment by nabaco** [comment]
@LifWirser This looks like a great start. Maybe we can even place in one of the repos, so it'll be a collaborative effort, and versioned :)
Regarding the C++ coding style, I think we should adapt an existing one, so we'll be able to use generally accepted tools like clang-format.
e.g. LLVM style with 4-spaces-indent.

**Comment by BenjamenMeyer** [comment]
@LifWirser  can we please get that in the repo or on the Wiki so we can collaborate on it?

**Comment by BenjamenMeyer** [comment]
We need to document the branching strategy in the Contributor guidelines too.

**Comment by BenjamenMeyer** [comment]
#127 provides the 0.6.x version for this. once that is merged we can move the milestone to a newer release or close out entirely.

As there are a few things left to  fill out in the version provided by #124 and #127 we probably should just move it *or* create new issues around the remaining items. I'm good with either.
