### ISSUE TITLE
Two unused variables in src/cmd/drawable.cpp

### ISSUE THREAD

**Issue by stephengtuggy** [vegastrike/Vega-Strike-Engine-Source#273]
/home/evert/vsmod/git/Vega-Strike-Engine-Source/engine/src/cmd/drawable.cpp:103:13: warning: unused variable 'numvold' [-Wunused-variable]
  103 |         int numvold = 0;
      |             ^~~~~~~
/home/evert/vsmod/git/Vega-Strike-Engine-Source/engine/src/cmd/drawable.cpp:104:13: warning: unused variable 'numvertices' [-Wunused-variable]
  104 |         int numvertices = 0;
      |             ^~~~~~~~~~~

Successor to #233 . (As far as I know, these two unused variable warnings remain unfixed.)

**Comment by evertvorster** [comment]
Moved the two variable initialization to the ifdef block where they are actually used. 
It seems strange to me that the preprocessor chops them out so completely when they are used in an ifdef.

**Comment by evertvorster** [comment]
This issue has been solved with PR #275
