### ISSUE TITLE
Fuel and damage indicators are not accurate upon loading a saved game.

### ISSUE THREAD

**Issue by evertvorster** [vegastrike/Vega-Strike-Engine-Source#279]
The visual indicators for fuel and damage in the HUD are not functioning correctly. 

The fuel indicator re-sets to full every time you land and take off. However, the actual amount of fuel is less and less on every flight where you have not purchased the repair & refuel. (Which always costs the same, no matter the damage or fuel used, what's up with that?)

The armor damage indicator on the HUD is a bit wonky too. If you save a game with damaged armor, when you load that game back up your armor appears to be perfect, on the HUD at least. When you cycle through the manifest it shows the damage.

**Comment by BenjamenMeyer** [comment]
Closing this in favor of #105.
