### ISSUE TITLE
Add Fedora 30-32 packaging support

### ISSUE THREAD

**Issue by stephengtuggy** [vegastrike/Vega-Strike-Engine-Source#280]
with proper RPM dependencies, filenames, etc.

**Comment by stephengtuggy** [comment]
@BenjamenMeyer do we want to try to refactor the 0.6.x CMakeLists.txt file to support RPM distributions, as I did on master? Or shall we leave well enough alone at this point?

**Comment by BenjamenMeyer** [comment]
@stephengtuggy If we have someone asking about it before we release 0.7.x then we can do it; otherwise let's just leave it alone for now.

**Comment by stephengtuggy** [comment]
OK, then I will close this issue as resolved in #278 .
