### ISSUE TITLE
Lots of error messages to the console with Python3

### ISSUE THREAD

**Issue by evertvorster** [vegastrike/Vega-Strike-Engine-Source#287]
When running VS from the console, I get a lot of error messages like this:
................
ERROR: NULL Unit used in Python script; returning default value...
ERROR: NULL Unit used in Python script; returning default value...
.................
This error message originates from engine/src/python/unit_wrapper_class.h, line 3. 
It looks like anything in this wrapper throws this error. We'll have to divide and conquer. ;)

**Comment by BenjamenMeyer** [comment]
@evertvorster  is this still an issue?

**Comment by evertvorster** [comment]
Nope, console nice and clean now.

:)


Evert Vorster
Awesome Chapters Tours
http://www.awesomechapters.com
Tel: +264 (0) 811477690

**Comment by BenjamenMeyer** [comment]
Thanks. Closing
