### ISSUE TITLE
engine/src/universe.cpp has a compile warning

### ISSUE THREAD

**Issue by evertvorster** [vegastrike/Vega-Strike-Engine-Source#297]
[ 52%] Building CXX object CMakeFiles/vegastrike.dir/src/universe.cpp.o
/home/evert/vsmod/git/Vega-Strike-Engine-Source/engine/src/universe.cpp: In member function 'virtual void GameUniverse::StartDraw()':
/home/evert/vsmod/git/Vega-Strike-Engine-Source/engine/src/universe.cpp:306:25: warning: deleting object of polymorphic class type 'StarSystem' which has non-virtual destructor might cause undefined behavior [-Wdelete-non-virtual-dtor]
  306 |                         delete star_system.back();
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~
[ 52%] Building CXX object CMakeFiles/vegastrike.dir/src/gfx/ani_texture.cpp.o

**Comment by evertvorster** [comment]
@royfalk this is a new warning. As far as I can tell, it's coming from a change that you made in the code. If I had noticed this earlier, I might have mentioned it on the PR. 
This warning looks very similar to #296, also introduced by you. 
Do you see the same warnings when you compile?
I am learning how to program in C++, and while I am making progress I am not in a place where I can fix this sort of warning yet. 
If you do decide to give these two new compiler warnings some attention, I would be very interested in how you do it, as a learning exercise on my part.

**Comment by stephengtuggy** [comment]
Probably the StarSystem destructor, `~StarSystem()`, just needs the keyword `virtual` added before it.
