### ISSUE TITLE
Add CI to VegaStrike

### ISSUE THREAD

**Issue by nabaco** [vegastrike/Vega-Strike-Engine-Source#31]
I think it might really boost development if we add CI/CD to this repository.
I have some experience with TravisCI, which is free for OpenSource projects.

I would suggest the following stages for CI integration:
- Check compilation on Ubuntu 18.04 LTS
- Check compilation on other platforms (MacOS, Windows, other Linux/UNIX distros)
- Implement code tests (I don't know if any exist already)

In the future, we can integrate CD which automates the creation of packages for different distro's upon releases, creation of documentation, etc.

**Comment by BenjamenMeyer** [comment]
Agreed; https://github.com/BenjamenMeyer/samplingEngine/blob/master/.travis.yml might provide some help on how to matrix this out. We probably want to test multiple Linux distros and may be even multiple compilers.

**Comment by nabaco** [comment]
Can someone activate the integration for this repository? The process is quite straight forward:

https://travis-ci.com/

**Comment by BenjamenMeyer** [comment]
@nabaco done

**Comment by BenjamenMeyer** [comment]
and it's `travis-ci.org` for the open source side ;)

**Comment by BenjamenMeyer** [comment]
@LifWirser I only enabled Vega-Strike-Engine-Source. If we need others it's trivial to flip them on too.

**Comment by nabaco** [comment]
@BenjamenMeyer I opened a PR, but I don't see any build status there.
Can you enable in the Travis-CI settings to run checks for PRs too?

**Comment by BenjamenMeyer** [comment]
@nabaco there won't be a build until after the first PR is merged and it finds it. IIRC travis-ci only searches branches after master has been configured, then it'll auto-pull PRs. The first PR with travis-ci is always tricky.

**Comment by BenjamenMeyer** [comment]
Actually... travis-ci.org did find it: https://travis-ci.org/github/vegastrike/Vega-Strike-Engine-Source/builds/669861119

**Comment by BenjamenMeyer** [comment]
you probably need to set it to use Ubuntu 18.04 for the base image.
