### ISSUE TITLE
GCC warning "-Wstrict-aliasing" being suppressed in cmd/collide2/Stdafx.h

### ISSUE THREAD

**Issue by stephengtuggy** [vegastrike/Vega-Strike-Engine-Source#315]
There's a `#pragma` line in this file that disables said gcc warning. If you comment out this `#pragma` line, there are a TON of new compiler warnings.

Eventually, I think we need to get to the bottom of this, and solve the underlying issue, rather than simply disabling the warning.

**Comment by BenjamenMeyer** [comment]
So `StdAfx.h` is a Windows common header for precompiled headers, and honestly we should move away from using it.
1. Precompiled headers don't really save time in anything, and end up just complicating the build.
2. It's better to have individual files be explicit and limited in what they include, only including the absolutely minimal necessary headers to build. This does mean more work and research on Windows to find the right header set as one won't simply do a "#include <windows.h>" and but this alone does far more for speeding up builds than using precompiled headers.

I know...a big change; but it'd likely be worth it in the end. This is just my recommendation. I'll leave it to the group to decide if we head this direction, but that won't likely be until 0.9.x.

$0.02 for what it's worth.

**Comment by stephengtuggy** [comment]
@BenjamenMeyer Granted all that about precompiled headers. However, it's possible that StdAfx.h is serving another important purpose here that has nothing to do with compilation speed. Namely, establishing a least common denominator of definitions and such that should be included in every file in the opcode subsystem.

On the other hand, maybe it isn't. 😉 I guess we'll have to investigate further.

**Comment by BenjamenMeyer** [comment]
@stephengtuggy there's a mixed usage of StdAfx.h in the windows world. That said, I generally find that there isn't really a true common section of headers that needs to be in every single header/implementation file. Often the issue with build times is that too much is getting built in every object file; cutting down what the compiler needs to consider when building is far more effective than trying to toss stuff together for everything.

The Windows specific headers can get a little obscure until you get familiar with them.

**Comment by stephengtuggy** [comment]
Filed a separate issue for possibly doing away with StdAfx.h. This issue -- the original one about the Strict Aliasing warnings being suppressed -- that's fixed now. Closing ticket.
