### ISSUE TITLE
Crash on program startup.

### ISSUE THREAD

**Issue by evertvorster** [vegastrike/Vega-Strike-Engine-Source#318]
I traced this one to commit: 2e0bf753985b7497f4c0878e01da65d237e836e9

Basically, what is happening on my system is that for whatever reason the starting directory initializes to an empty string. 
Bad things happen after that. 

I put in a pr that will fix this

**Comment by stephengtuggy** [comment]
I suspect that this comes from #316 combined with #209 . VS changes directory just fine, but then it can't find the data files, so it crashes.

**Comment by evertvorster** [comment]
I've merged my quick hack into master now, closing this issue. However, on my system vegastrike still crashes if not run from /usr/share/vegastrike, but does happily accept the "-d" parameter and then runs fine if you tell it where the data is. 
So, back to it's old behavior.
