### ISSUE TITLE
vegastrike not finding it's data directory automatically.

### ISSUE THREAD

**Issue by evertvorster** [vegastrike/Vega-Strike-Engine-Source#321]
On a high level, vegastrike is a game engine that works with different sets of game data. 
Currently we have a launcher that goes with the data set that changes to the proper directory and launches vegastrike.

Should we install the wing commander mod, we can launch vegastrike with the "-d" command line switch to play with that dataset, or just execute it vegastrike from the directory that the data is installed in. 

Please correct me if I am wrong, but currently when vegastrike starts up, it reads the "-d" command line parameter, and changes to that directory. Then it looks for some unknown variable in the config file with, never finds it and sends this message to the console:
DATADIR - No datadir specified in config file, using ;

Now it tries to load /universe/milky_way.xml, and core dumps if that open command fails. 

I remember it checking for the presence of Version.txt, and halted execution if not found. 

-----------------------
As a way forward, I propose that we figure out what the DATADIR variable in the config file was, and put it back in. Then we will have a solid way of knowing which directory to change to on various platforms that does not interfere with the game engine's ability to be used for data sets other than Upon the Coldest Sea.

**Comment by evertvorster** [comment]
Line 710 of vsfilesystem reads:
//NOTE : THIS IS NOT A GOOD IDEA TO HAVE A DATADIR SPECIFIED IN THE CONFIG FILE

But leaves no explanation as to why it is not a good idea. 

I guess we'll just have to put it in, and then see why this note was put there...
What I have so far, is that options.cpp is supposed to read "datadir" in the "data" section of the vegastrike.config file. 
So, I added in a line just below the commented out hqtextures in the section "data":
<var name="datadir" value="/usr/share/vegastrike"/>

So far the game engine flat out refuses to assign that variable, and I am unable to figure out why...

**Comment by BenjamenMeyer** [comment]
@evertvorster my guess (without reading code) is likely due to algorithm finding the config file and what might be expected. We can, however, fix those things to provide a better experience.

**Comment by evertvorster** [comment]
Here is a little quandary.... 
Because Vegastrike the engine can be used to run various games, should it have a default data directory?

The human thing to do is to type "vegastrike" at the command line, and the game vegastrike runs, or click on the "Vegastrike" icon in the gui, with a similar effect.

Similarly for Privateer or whatever space sim is built on top of VegaStrike the engine. 

Would it not then stand to reason that we strip out all config-finding code out of the engine, and purely specify which game to runs from a script?
We are already doing that now with "vs" from Assets-Master.

@BenjamenMeyer do you agree?

**Comment by BenjamenMeyer** [comment]
@evertvorster kind of....we probably should do the following:
- rename the binary from `vegastrike` to `vegastrike-engine` (or something along those lines)
- if the binary name at runtime is the default then just error out if the config file/location is not specified, and not try to find any config file automatically
- if the binary name is a non-default value then we use the binary name in the search to try to find the config like we do now.

Then the VS:UtCS game can create the symlink to the game (Linux, Unix) or rename the binary (Windows) to get the desired behavior.

This is probably part of the 0.9.x work as part of separating the assets from the engine more cleanly.

**Comment by stephengtuggy** [comment]
Relates to #417

**Comment by stephengtuggy** [comment]
@BenjamenMeyer Yes, I agree that something like that should be done in 0.9.x. In the interim, though, we need a better solution than what we have now. Lots of former Vega Strike players are encountering unexpected issues with the VS engine finding the assets, that they didn't run into before.

Function `InitDataDirectory()` in vsfilesystem.cpp already contains a list of directories to search for the data/assets. Perhaps the interim solution, for 0.7.x and 0.8.x, could be as simple as adding `/usr/share/vegastrike` to that list.

**Comment by BenjamenMeyer** [comment]
@stephengtuggy we could probably do the normal Unix method of checking the binary name to determine if we do the legacy or new behavior to help mitigate the issue.

**Comment by BenjamenMeyer** [comment]
Is this still an issue?
`vegastrike` should provide legacy behavior of automatically searching certain locations for the data directory; this will eventually be only generated as part of the VS:UtCS assets installation, and more under its control.

`vegastrike-engine` starts the process towards vega-strike engine requiring it to be specified.

**Comment by stephengtuggy** [comment]
@BenjamenMeyer I would consider this issue pretty much resolved at this point. @evertvorster what do you say?

**Comment by evertvorster** [comment]
Yea, I would say so.

Thanks for all the hard work you guys are putting into this, it makes my
measly contribution look terrible!

Evert Vorster
Awesome Chapters Tours
http://www.awesomechapters.com
Tel: +264 (0) 811477690

**Comment by stephengtuggy** [comment]
@evertvorster You're welcome. And your contribution is still significant.

Closing this ticket.
