### ISSUE TITLE
gl_light_state.cpp:426: void gfx_light::TrashFromGLLights(): Assertion `(GLLights[target].options&OpenGLL::GLL_ON) == 0' failed.

### ISSUE THREAD

**Issue by stephengtuggy** [vegastrike/Vega-Strike-Engine-Source#337]

**Comment by evertvorster** [comment]
This error does ring a bell. Does it happen all the time? How do you trigger it?

**Comment by stephengtuggy** [comment]
@evertvorster At first, the error was consistently reproducible, by taking the following steps:

1. Launch Vega Strike.
2. Start a new campaign.
3. Launch your ship.
4. Press the `\` key to begin accelerating to full speed.
5. Quickly press `6` to switch views.
6. While in that view, maneuver your ship around -- turning, yawing, and rolling back and forth -- and fire a few laser shots.
7. Press `1` to switch back to the normal view.
8. Get into a fight with Oswald. Fire at least one or two laser shots that hit his shields.

Then, after I made some code changes, the error stopped being consistently reproducible, and I thought it was fixed. But then it showed up again after a few minutes of gameplay.

**Comment by stephengtuggy** [comment]
@evertvorster You might have introduced this issue by mistake. But that's okay. These things happen. 😄

**Comment by evertvorster** [comment]
@stephengtuggy could you help to explain how I managed to introduce this one? I want to learn from my mistakes.

**Comment by stephengtuggy** [comment]
@evertvorster `options` is a flags value. Each bit -- each 0 or 1 in the binary representation of the number, from Least Significant Bit (LSB) to Most Significant Bit (MSB) -- means that a different option is off or on. `GLL_ON` identifies which bit is the bit for whether this particular light source is on or off. It's a bitmask enum, one of several.

This is a complicated topic, and I don't know how good a job I'm doing at explaining it. Hopefully you can do some googling of these terms to understand them better.

I think your specific mistake was assuming that lights should always be on. Actually, they're supposed to get turned off before they are deleted. Otherwise, the assert message above gets thrown, and the program halts. At least, that's how I understand it.

Given that flag enums are such an advanced topic, it's not surprising that it tripped you up.
