### ISSUE TITLE
Dev & Core communications

### ISSUE THREAD

**Issue by BenjamenMeyer** [vegastrike/Vega-Strike-Engine-Source#34]
I realize that the VS community has a long history at https://forums.vega-strike.org/ for communications. However, at least at the present the side is being a bit problematic to load. @Loki1950 mentioned contacting another forum member regarding it and hosting.

Q: would it be worth having another means of communication such as Slack (vegastrike.slack.com), IRC (FreeNode, etc), or something else too? (Discord, Gitter, Mastodon, Diaspora, etc)

@danielrh @pyramid3d @klaussfreire @Loki1950 @ministerofinformation @pheonixstorm @zonkmachine

**Comment by royfalk** [comment]
I know I would appreciate something like slack for developers to communicate.
Currently working on setting up first commit - refactor of particle.cpp.


Roy Falk

________________________________

**Comment by nabaco** [comment]
Gitter could be nice, as it allows directly referencing issues/commits/etc from Github, so it'd be nice for devs.
Slack is more popular and widely accepted among devs.
I think IRC would be more fit to talk with users.

Either way, we should also consider what are the available integrations. You could get notifications about PRs, tests, deployment, releases, etc. As well as doing action on Github through the chat system.

The main problem is that there are so many options 😁

**Comment by pyramid3d** [comment]
IRC has the problem that it is synchronous communication. Here's an example of asynchronous communication on Gitter: https://gitter.im/Worldforge/Lobby.

**Comment by BenjamenMeyer** [comment]
I'll narrow the options. Please vote using the associated icons
- [ ] gitter :heart:
- [ ] Slack :laughing:

**Comment by nabaco** [comment]
@BenjamenMeyer maybe we should just try to go with one of the options, and see how it works?

**Comment by BenjamenMeyer** [comment]
@Loki1950 @royfalk @pyramid3d @stephengtuggy any opinions on this?

**Comment by BenjamenMeyer** [comment]
I'll give folks another day to respond before moving forward with just setting something up.

**Comment by stephengtuggy** [comment]
@BenjamenMeyer I use Slack, and am very comfortable with it, FWIW.

Slack does have a good GitHub integration, also. A bot type thing. In the third-party marketplace. Maybe I can look that up for you guys, if desired.

**Comment by BenjamenMeyer** [comment]
I've used Slack (love it) and another project I'm involved with (Falcon Frameworks) uses Gitter. I also use IRC (FreeNode) still for some of my own projects.

I'm flexible and will setup what we as a group want (aside from MS Teams - let's not even go there).
Just looking to see what you all want to use.

**Comment by BenjamenMeyer** [comment]
As of right now, we have one vote for Slack and one for Gitter. I've used Slack a lot more than Gitter, but here's my current though:

- Gitter seems more light weight for users since you can sign in with your github or other federated accounts.
- Slack requires getting an invite, creating an account, etc - at least for the others I have run.
- Both seem to be good platforms, have GitHub integrations, etc.
- I'm relatively new to Gitter myself; but have had a long history with Slack. Personally I'm open to trying things out until we find what works.
- Having a low barrier to entry is probably something that is important.

Given that, is there any objection to using/trying Gitter? 
If we come to a consensus that we don't like it we can try something else too.

@stephengtuggy - do you have a strong opinion/objection?

**Comment by royfalk** [comment]
OK. Let's go with gitter.
We have three votes.
(If it turns out to be awful, we'll switch.)

**Comment by BenjamenMeyer** [comment]
Okay. I seem to be missing a permission for the VegaStrike org to enable the integration. @pyramid3d or someone will have to accept the permission grant before I can get the right setup in gitter.

**Comment by royfalk** [comment]
I'll try. What do I need to do?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by BenjamenMeyer** [comment]
@royfalk  Checked an org I fully own and it should be something under:
https://github.com/organizations/VegaStrike/settings/oauth_application_policy

I munged the URL based on my other org. If it doesn't work:
- VegaStrike Org :arrow_right: settings  :arrow_right: Third Party Access

**Comment by royfalk** [comment]
Nope. We need an owner.
@Loki1950, could you please set this up based on Benjamen's instructions above.
Thanks.

**Comment by Loki1950** [comment]
Approved @nabaco request

**Comment by BenjamenMeyer** [comment]
https://gitter.im/vegastrike/community?utm_source=share-link&utm_medium=link&utm_campaign=share-link

**Comment by BenjamenMeyer** [comment]
I've sent out invites to those in this discussion. Please add others - I obviously won't be able to know everyone that should get an invite; so if you're reading this and didn't get an invite please don't read anything into that.

**Comment by pyramid3d** [comment]
Thanks for the setup and invite on Gitter. I would have voted for Gitter in this thread but dunno how.

**Comment by BenjamenMeyer** [comment]
Since we're on gitter, and it's in the README, closing this for the time being. If we can open it up if we need to continue the conversation.

**Comment by BottledByte** [comment]
Sorry for commenting a recently closed issue, but I have an idea related to this and I do not think that new separate issue should be opened.

I think that Gitter is good solution for pure dev-related communication due to its good integration with Github. However, *secondary* communication platform might be useful. I think that Discord is a good candidate, for:
1) It has a good voice chat support, which is useful for dev and player meetings alike.
2) It is not "dev-centric" but rather "gamer-centric" platform and it is more appealing to players (Gitter has somewhat developer-like atmosphere). And games need players :)
3) It could be used for arranging/announcing community events in the future and younger people tend to respond to this platform more than to forums.

And finally, while it is *not objective*, I have read that there is going to be a developer meeting soon and I would like to take a part in it (and this project), but Zoom and I are not friends :).
It is good to see that there is an attempt to bring VS back from the dead and modernize it :+1:

**Comment by BenjamenMeyer** [comment]
@BottledByte thanks for the information. I'm not sure if we're ready to take on using two tools right now, but it's good to have that documented. Thanks!

Yes, there will be a dev meeting soon, and we'll be using Zoom at least for this first time. We'll coordinate it in Gitter. We'll see how it goes; we might need something different next time around.

**Comment by BenjamenMeyer** [comment]
Just doing a quick check of Discord (since I'm not very familiar with it); it has a similar draw back as Slack (which also has Video chats built-in) in that it has its own account system. Granted, many gamers may already have a Discord account; though I'm not sure if the overlap we need between Gamers and Developers might be right...not ruling it out, just noting what I'm finding on a quick check.

What would be really helpful for easing adoption of Discord would be if it had GitHub integration so we could use a GitHub account to make a Discord account like we do with Gitter so that devs had the choice of which kind of account to use.

**Comment by BottledByte** [comment]
@BenjamenMeyer I agree with you. Handling another separate platform now would probably not worth the effort and that the entry barrier can be too high for the devs. I just wanted to point out Discord's strengths and potential for the future.

But there is one thing about the dev meeting I have in mind.
I think that [Jitsi](https://meet.jit.si/) could be used for it instead of Zoom. It does not require an account, just like Zoom, it is more secure and less privacy invasive and can be used in browser easily.
Also, it may have lower entry barrier, as it does not require client application download (If I am right, this is required to use Zoom).
I think that it might worth checking it, *but I can not be objective in this matter, as I am an open source fan.* :)

**Comment by BenjamenMeyer** [comment]
Jitsi could be interesting to try out. I'm not tied to anything in particular - I offered up Zoom b/c I already had a free account for it.

**Comment by nabaco** [comment]
I invite everyone to a meeting today (17/04/2020) at 1PM EDT/8PM IDT in Jitsi. To stay updated in case of time changes I suggest to go to Gitter.

You are invited to join a meeting.
Join the meeting:
https://meet.jit.si/VegaStrikeRevivalKickoffMeeting

To join by phone instead, tap this: +1.512.402.2718,,1728453447#

Looking for a different dial-in number?
See meeting dial-in numbers: https://meet.jit.si/static/dialInInfo.html?room=VegaStrikeRevivalKickoffMeeting

If also dialing-in through a room phone, join without connecting to audio: https://meet.jit.si/VegaStrikeRevivalKickoffMeeting#config.startSilent=true

**Comment by nabaco** [comment]
It escaped my attention that today is Friday, so I'm moving this to Monday (20/04/2020) to fit everyone's schedule. My apologies.

**Comment by stephengtuggy** [comment]
Hey guys. Sorry I missed the meeting. I had a health issue come up. I am doing better now, though.

@BenjamenMeyer should I have a gitter invite in my email?

**Comment by BenjamenMeyer** [comment]
@stephengtuggy probably, though you are added somehow. Just hit the link in the readme.

**Comment by stephengtuggy** [comment]
@BenjamenMeyer Done. Thanks!
