### ISSUE TITLE
*** No rule to make target '/usr/local/lib/libz.so'

### ISSUE THREAD

**Issue by tnais** [vegastrike/Vega-Strike-Engine-Source#350]
Hello respected developers!

Since the .deb on the site is not up to date with Ubuntu distributions, I tried to clone and compile the source the very easy way.

But I get this very strange message:

make[2]: *** No rule to make target '/usr/local/lib/libz.so', needed by 'vegastrike'.  Stop.

What puzzles me is;

-  that I have zlib1g package installed
-  that the required library should be in "/usr/local", but zlib is not listed as a dependency that has to be built outside the distribution.

Have I done something wrong?
Stay safe and stay healty

**Comment by stephengtuggy** [comment]
Hello @tnais . So you're on Ubuntu then? Which version?

Yeah, our 0.7.0 version should be coming out very soon, with support for Ubuntu 20.04 LTS "focal", along with several other major Linux distributions. Windows and macOS support to come sometime after that.

**Comment by stephengtuggy** [comment]
One thing you can try is simply running the bash script `script/bootstrap` with sudo / root privileges. If you're on one of our supported Linux distros, this should install all the development dependencies automatically.

**Comment by stephengtuggy** [comment]
Or, you might just need to install apt package `zlib1g-dev`.

**Comment by BenjamenMeyer** [comment]
The 0.7+ releases should address this for the Package files (RPM, Deb). 0.6.x won't see anything. We're working to get 0.7.x out the door; it's gotten hung up a little with the Travis-CI to GitHub Actions migration (still have to port the Assets Production over).

We can close this once 0.7.x is released and the issue confirmed as resolved.
For source builds the `scripts/bootstrap` is really the way to resolve it.

**Comment by BenjamenMeyer** [comment]
Version 0.7.0 has been released. Please confirm this has been fixed so we can close it.
Thanks!

**Comment by BenjamenMeyer** [comment]
@tnais please confirm if this is still an issue with our latest release.

**Comment by tnais** [comment]
Sorry for being late. Will do ASAP.

**Comment by BenjamenMeyer** [comment]
@tnais Please re-open if this is still an issue.
