### ISSUE TITLE
TODO: Add support for Ubuntu 20.10 "Groovy Gorilla"

### ISSUE THREAD

**Issue by stephengtuggy** [vegastrike/Vega-Strike-Engine-Source#353]
I suggest we do this just for 0.8.x and following, since Ubuntu 20.10 may not support Python 2 (at least not without a lot of work).

**Comment by Icekhaos** [comment]
Currently, 0.7.x asks for versions 1.67.0 of the various libboosts; wouldn't it be possible to test other versions, such as those of Groovy and Hirsute, to check if this actually runs? If it does, that dependency does not need to be an equals.

**Comment by Icekhaos** [comment]
What's worse is those packages are named specifically in Ubuntu repos; couldn't we just use or on those?

**Comment by stephengtuggy** [comment]
@Icekhaos Point taken. As of 0.7.x, we're still supporting both Python 2 and Python 3. Later versions of Boost are not compatible with Python 2, so we have to depend explicitly on the older Boost version in Ubuntu 20.04, if we want Python 2 to work.

With Groovy and Hirsute, I expect that we will drop the specific Boost versions, if possible; or else go with the latest Boost version available. We will start supporting those in Vega Strike 0.8.x, which retires Python 2.

**Comment by Icekhaos** [comment]
But if the game is capable of running in Python 3 mode, why can't you just note in the package description that if someone wants to run against Python 2 to use the older depends, and have the package depends be an or between both these and latest? It would probably solve the Groovy/Hirsute problem well prior to 0.8.x. Maybe a simple config option to try with either 2 or 3?

If this runs with newest libboosts on Python 3, I see no issue with depending either on 1.67.0 *or* the newer versions found in these newer distributions.

**Comment by BenjamenMeyer** [comment]
We're close to having 0.7.x out the door; 0.8.x should be a quick turn around b/c it's 100% focused on the Py3 upgrade and we really shouldn't allow much of anything else into....though there will be some since we've had a few additional changes on master - even then, we shouldn't have the holdups we're having with 0.7.x which is more due to some of things we've decided to change since 0.5.x.

@stephengtuggy @Icekhaos please feel free to submit a PR to master to move Boost to a version that no longer supports Py2. If we get that in then we can start our testing, update platforms appropriately, etc and help get 0.8.x out the door faster once 0.7.x is fully released.

**Comment by Icekhaos** [comment]
I would if I had a clue how to file one and do what needs to be done.

**Comment by stephengtuggy** [comment]
This will take some doing. To support Ubuntu Groovy or Hirsute, first we need to establish Docker build environments for them. Before we can do **that**, we need to switch https://github.com/vegastrike/build-system-docker-images over to GH Actions. (https://github.com/vegastrike/build-system-docker-images/issues/4)

These same prerequisites are also necessary for Linux Mint support (#360 ).

**Comment by BenjamenMeyer** [comment]
Depending on work involved we might have to push to 0.9.x; will see. It's on both boards for now.

**Comment by stephengtuggy** [comment]
Update 2021-07-27: The `build-system-docker-images` repo has been switched over to GH Actions. New Docker build environments in progress; see https://github.com/vegastrike/build-system-docker-images/issues/10 , https://github.com/vegastrike/build-system-docker-images/issues/12 , https://github.com/vegastrike/build-system-docker-images/issues/14 , https://github.com/vegastrike/build-system-docker-images/issues/15 , https://github.com/vegastrike/build-system-docker-images/issues/16 , and https://github.com/vegastrike/build-system-docker-images/issues/17 .

**Comment by stephengtuggy** [comment]
Update 2021-08-04: `build-system-docker-images` complete. 0.8.x branch of `Vega-Strike-Engine-Source` now includes Groovy, among other distros. Update for 0.8.x branch of `Assets-Production` in progress.
