### ISSUE TITLE
Remove python2 build logic from CMakeLists.txt

### ISSUE THREAD

**Issue by stephengtuggy** [vegastrike/Vega-Strike-Engine-Source#364]
We will probably want to wait on this until we're sure that the python3 code is ready.

Relates to #362

**Comment by BenjamenMeyer** [comment]
moved to 0.9.x; it'll just be deprecated for 0.8.x.

To be clear: Py2 support will *not* be provided in 0.8.x by us. 0.7.x is the last official version to have Py2 support. It just so happens that 0.7.x technically supports both Py2 and Py3 (per user testing) though it only officially supports Py2. In the end, leaving Py2 support in for devs that want to build it for one reason or another would be beneficial in 0.8.x; but we won't be providing any 0.8.x builds with Py2 in it.
