### ISSUE TITLE
RPM Releases

### ISSUE THREAD

**Issue by BenjamenMeyer** [vegastrike/Vega-Strike-Engine-Source#368]
In working to get installation instructions together, I noticed that we have RPM releases for the VS:UtCS Assets (https://github.com/vegastrike/Assets-Production/releases/tag/v0.6.2), but we do not for the engine (https://github.com/vegastrike/Vega-Strike-Engine-Source/releases).

We need to get that fixed. We probably should backport the fix to 0.6.x too.

**Comment by stephengtuggy** [comment]
[Engine v0.7.0-alpha3](https://github.com/vegastrike/Vega-Strike-Engine-Source/releases/tag/v0.7.0-alpha3) includes RPMs.

**Comment by BenjamenMeyer** [comment]
We're about to retire 0.6.x, and we're working on getting 0.7.x out the door which does have RPM builds.

NOTE: At present the 0.7.0-alpha series does have the RPMs; the beta series using the GH Actions does not but we're working on getting that resolved. This can be closed once that is resolved.

**Comment by BenjamenMeyer** [comment]
Version 0.7.0 has been released. Please confirm this has been fixed so we can close it.
Thanks!

**Comment by stephengtuggy** [comment]
Verified as fixed. Closing.
