### ISSUE TITLE
On a fresh install, vegasettings does not automatically find Version.txt

### ISSUE THREAD

**Issue by stephengtuggy** [vegastrike/Vega-Strike-Engine-Source#372]
You have to run vegasettings from the directory where Version.txt is located, namely `/usr/share/vegastrike`.

**Comment by Loki1950** [comment]
Also effects 0.6.0 vssetup

**Comment by stephengtuggy** [comment]
It only seems to happen when the game was installed using the installer, as opposed to running it from source. And I just discovered that running @evertvorster 's `vsettings` script, instead of `vegasettings` directly, solves the problem. Perhaps that is what we can instruct users to do. For now at least.

I still would like to get the underlying issue with vegasettings solved though. Or else install Version.txt in the right place, so that vegasettings can find it automatically.

**Comment by BenjamenMeyer** [comment]
So this is more of a game assets issue as the assets need to instruct the engine where to find the information to run the game defined by the game assets.

#369 would help in this too as it would allow for some integration between the engine and assets for launching games beyond specifying command-line parameters.

:moneybag: FWIW

**Comment by BenjamenMeyer** [comment]
So we have some documentation on this at https://vega-strike.org/install/ now; and the packages have the the scripts that mostly solves this. Anything more will be in 0.9.x or later.

**Comment by BenjamenMeyer** [comment]
@stephengtuggy is this still an issue?

**Comment by stephengtuggy** [comment]
@BenjamenMeyer Not sure. I'll check into it and get back to you later

**Comment by stephengtuggy** [comment]
This doesn't seem to be an issue anymore. Closing.
