### ISSUE TITLE
Drop vendoring of libboost

### ISSUE THREAD

**Issue by BenjamenMeyer** [vegastrike/Vega-Strike-Engine-Source#38]
Per https://github.com/vegastrike/Vega-Strike-Engine-Source/pull/33#issuecomment-609089044
VS provides a vendored copy of libboost. Is this still necessary? Or can we assume it is available?

**Comment by Loki1950** [comment]
Since we use an internal Python interpreter 2.7 ATM libboost has been integral for the functions it provides since the beginning dropping it would mean refactoring about 80% of the code not that trivial

**Comment by BenjamenMeyer** [comment]
@Loki1950 this isn't about dropping boost from use; it's about dropping the vendored code and relying on system provided code. On Linux that should be doable; possibly on Mac too. On Window we'll have to setup CMake to download stuff in some form since Windows doesn't provide that stuff.

This is also just to raise the question. If it's not possible, then it's at least documented and we can revisit the question later if the requirements ever change.

**Comment by Loki1950** [comment]
Was not really vendored we just kept a link in our svn repo to the boost repo so we had the latest code was more for convenience for Window's builds IIRC as you mentioned no need for Linux/OSX made keeping up with it's API easier as well so we will just need to settle on the most common version in various distro but that may not be necessary for Windows may need to build a dll for linking into the code have a few old Windows binaries about cira Win7 will have look see through them

**Comment by BenjamenMeyer** [comment]
We're going to have to figure out the Windows story. Might need some off-line testing for a while.

**Comment by stephengtuggy** [comment]
Yeah, personally, I don't think Boost is outdated at all. Seems to be a very helpful and widely accepted supplement to the official C++ standards. But maybe that's just me. Would like to get more of a read on the rest of y'all's take.

**Comment by stephengtuggy** [comment]
As for including a whole separate copy of the Boost source code in our (Vega Strike) repos, I have never been a fan of that. There's got to be a better way. Although it may take some time to figure out what.

> We're going to have to figure out the Windows story. Might need some off-line testing for a while.

Yes, definitely! I spent literally two months trying to get the stupid thing to build on Windows. Grrr.

One thing that I can tell you definitely DOESN'T work: Visual Studio 2019. Use VS2017 at the latest.

Should we create a separate issue to discuss Windows builds?

**Comment by stephengtuggy** [comment]
So, question: On Ubuntu 18.10 and other working Linux build environments, I take it that including the appropriate `libboost` apt packages directly "just works"?

**Comment by BenjamenMeyer** [comment]
IIRC Boost is an official extension to Standard C++ and parts are officially in C++. So yes, I'm a fan of Boost. (Bigger fan of Qt; but that's beside the matter. And no, I'm not going to push to move to Qt.)

Per Windows, yes, let's keep that in a separate issue.

I've been running 19.04 and keep upgrading every 6 months; just swapped to 19.10 since it had some upgrade issues early on. I'll upgrade to 20.04 soon after it's out unless there's issues in the upgrades. I haven't had issues building it, but I'll certainly check to verify which boost libs it's using.

**Comment by stephengtuggy** [comment]
Separate issue filed for Windows: #53

**Comment by stephengtuggy** [comment]
> IIRC Boost is an official extension to Standard C++ and parts are officially in C++. So yes, I'm a fan of Boost. (Bigger fan of Qt; but that's beside the matter. And no, I'm not going to push to move to Qt.)

:+1:

> 
> Per Windows, yes, let's keep that in a separate issue.

Done. #53 

> 
> I've been running 19.04 and keep upgrading every 6 months; just swapped to 19.10 since it had some upgrade issues early on. I'll upgrade to 20.04 soon after it's out unless there's issues in the upgrades. I haven't had issues building it, but I'll certainly check to verify which boost libs it's using.

Sounds good, man.
