### ISSUE TITLE
Name of galaxy xml set in vegastrike.config is ignored

### ISSUE THREAD

**Issue by viktorradnai** [vegastrike/Vega-Strike-Engine-Source#389]
The universe object is created before `vegastrike.config` is parsed therefore the default galaxy name (`universe/milky_way.xml`) is hardcoded here:
https://github.com/vegastrike/Vega-Strike-Engine-Source/blob/333186e00b760eda300a4b89230ff19ce5083a50/engine/src/vsfilesystem.cpp#L713

Even though there is a setting for it in `vegastrike.config (`variables/general/galaxy`) this has no effect.

**Comment by viktorradnai** [comment]
This is the first thing that breaks when I try to run Privateer Gemini Gold with the new binary :)

**Comment by BenjamenMeyer** [comment]
This does need to be addressed. There is a bunch of config stuff to be done related to the configuration. We should try to get this in 0.7.x as it effects our sister project. If not, I'm hoping 0.8.x will be a fast turn around (focused on the Py3 conversion only) so this would be 0.9.x.

**Comment by BenjamenMeyer** [comment]
Reset this to 0.9.x; if the PRs get completed in time it'll make 0.8.x since it's on master. It would need a port to 0.7.x; if finished in master we can do that, but we'll probably move too quickly to 0.8.x for that to matter.

**Comment by stephengtuggy** [comment]
Looks like #432 and #433 addressed this issue as well, and effectively fixed it for 0.7.x and all later releases.

**Comment by BenjamenMeyer** [comment]
@stephengtuggy I concur
