### ISSUE TITLE
Community Structure

### ISSUE THREAD

**Issue by BenjamenMeyer** [vegastrike/Vega-Strike-Engine-Source#41]
From https://github.com/vegastrike/Vega-Strike-Engine-Source/pull/33#issuecomment-609089044:

> Please do that. Also, please ask @Loki1950 to add you as a contributor. I don't know your background but you seem to know your stuff. I'm going to open two issues: 1. Project History 2. Current team status. From my talk with Loki, the older generation of programmers has moved on. Loki's been around for ages but he's not a C++ dev. It might be a good idea to start talking about where we want to take this project and how we want to do it. My vote is for Loki to be the project leader/mediator.

There has been a large turn over of the devs. We need to decide who makes the decisions, who gets what authority, etc to help progress things forward.

**Comment by BenjamenMeyer** [comment]
I am presently helping to manage the stuff in Github at least from a project management view with the Project Board, issues, etc.

I've got a long history of software development in Python and C/C++ too; but relatively new to the game dev space. Willing to help out however needed.

**Comment by BenjamenMeyer** [comment]
Created the @vegastrike/core-reviewers team. I'm on it at least for now since I set it up. Feel free to remove me or say I'm official.

**Comment by pyramid3d** [comment]
> We need to decide who makes the decisions, who gets what authority, etc to help progress things forward.

I reckon it's pretty straight forward: whoever is around and takes up a task will have the authority to participate in decisions and move things forward (as in 'the true spirit of responsible open community'). Have fun at that ;-)

**Comment by nabaco** [comment]
I agree with @pyramid3d's statement.
Additionally, following @danielrh's decision and @Loki1950's announcement:
- Loki is the Project Lead
- @BenjamenMeyer is the Lead Developer

With that, I think we can close this issue

**Comment by BenjamenMeyer** [comment]
@nabaco before we close this we need to update permissions in the org to reflect the decision.

**Comment by nabaco** [comment]
I think @Loki1950 can help with that

**Comment by Loki1950** [comment]
Help with the github web interface would be appreciated it can be a bit tedious

**Comment by nabaco** [comment]
@BenjamenMeyer We have figured it out with @Loki1950. You should have full access now.

**Comment by Loki1950** [comment]
I guess we can close this issue now

**Comment by BenjamenMeyer** [comment]
permissions confirmed. Closing
