### ISSUE TITLE
'std::logic_error' - basic_string::_M_construct null not valid

### ISSUE THREAD

**Issue by stephengtuggy** [vegastrike/Vega-Strike-Engine-Source#418]
@STyx2909 reports the following with Vega Strike 0.7.0 beta 10 py3 on Ubuntu 20.04 x64:

here are my reports: 
1) running **vs** leads to the same problem about DATADIR not configured.

2) _$ vegastrike -d /usr/share/vegastrike_ does not work, it says -d (or -D) requires an argument...
**but** _$vs /usr/share/vegastrike_  brings a new though similar error (somewhat a success)
In path /home/stephan
ARG #1 = -d/usr/share/vegastrike
ARG #3 = --debug=3
GOT SUBDIR ARG = 
Found data in /usr/share/vegastrike
Using /usr/share/vegastrike as data directory
Using .vegastrike as the home directory
Found MODDIR = /usr/share/vegastrike/mods
USING HOMEDIR : /home/stephan/.vegastrike As the home directory 
CONFIGFILE - Found a config file in home directory, using : /home/stephan/.vegastrike/vegastrike.config
DATADIR - No datadir specified in config file, using : /usr/share/vegastrike
SIMULATION_ATOM: 0.01
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid

So does _$ vegastrike -d/usr/share/vegastrike_.

_Originally posted by @STyx2909 in https://github.com/vegastrike/Vega-Strike-Engine-Source/issues/417#issuecomment-774630013_

**Comment by BenjamenMeyer** [comment]
Please confirm this after #433 is merged and a new release is made again.

**Comment by BenjamenMeyer** [comment]
Version 0.7.0 has been released. Please confirm this has been fixed so we can close it.
Thanks!

**Comment by BenjamenMeyer** [comment]
@stephengtuggy are we still seeing this? Or can we close it out?

**Comment by stephengtuggy** [comment]
@STyx2909 can you please confirm whether or not this is still an issue with the latest 0.7.x release? If you're not sure, we'll probably close this ticket; it can be reopened later if needed.

**Comment by BenjamenMeyer** [comment]
might need to confirm with 0.8.x given how old 0.7.x is.

**Comment by stephengtuggy** [comment]
@BenjamenMeyer yeah, this ticket is pretty old. We might just want to close it if we don't hear back within a couple of days.

**Comment by stephengtuggy** [comment]
I have not heard anything further on this ticket in the last week, so I am closing it. Feel free to reopen if the issue reappears.
