### ISSUE TITLE
Installer fails to find ChangeLog

### ISSUE THREAD

**Issue by evertvorster** [vegastrike/Vega-Strike-Engine-Source#425]
Hi there!
On my builds, packaging is now failing to find ChangeLog. 

Here is a little of  the log:
--------------snip--------------
==> Entering fakeroot environment...
==> Starting package()...
make: Entering directory '/z1/OS/aur/vegastrike-engine-git/src/build'
make[1]: Entering directory '/z1/OS/aur/vegastrike-engine-git/src/build'
make[2]: Entering directory '/z1/OS/aur/vegastrike-engine-git/src/build'
make[2]: Leaving directory '/z1/OS/aur/vegastrike-engine-git/src/build'
[ 30%] Built target vegastrike-engine_com
make[2]: Entering directory '/z1/OS/aur/vegastrike-engine-git/src/build'
make[2]: Leaving directory '/z1/OS/aur/vegastrike-engine-git/src/build'
[ 41%] Built target vegastrike-OPcollide
make[2]: Entering directory '/z1/OS/aur/vegastrike-engine-git/src/build'
make[2]: Leaving directory '/z1/OS/aur/vegastrike-engine-git/src/build'
[ 92%] Built target vegastrike
make[2]: Entering directory '/z1/OS/aur/vegastrike-engine-git/src/build'
make[2]: Leaving directory '/z1/OS/aur/vegastrike-engine-git/src/build'
[ 94%] Built target vegasettings
make[2]: Entering directory '/z1/OS/aur/vegastrike-engine-git/src/build'
make[2]: Leaving directory '/z1/OS/aur/vegastrike-engine-git/src/build'
[ 95%] Built target vs-buildenv-replace
make[2]: Entering directory '/z1/OS/aur/vegastrike-engine-git/src/build'
make[2]: Leaving directory '/z1/OS/aur/vegastrike-engine-git/src/build'
[ 99%] Built target vega-meshtool
make[2]: Entering directory '/z1/OS/aur/vegastrike-engine-git/src/build'
make[2]: Leaving directory '/z1/OS/aur/vegastrike-engine-git/src/build'
[ 99%] Built target vs-buildenv-asteroidgen
make[2]: Entering directory '/z1/OS/aur/vegastrike-engine-git/src/build'
make[2]: Leaving directory '/z1/OS/aur/vegastrike-engine-git/src/build'
[100%] Built target vs-buildenv-trisort
make[1]: Leaving directory '/z1/OS/aur/vegastrike-engine-git/src/build'
Install the project...
-- Install configuration: "Release"
-- Installing: /z1/OS/aur/vegastrike-engine-git/pkg/vegastrike-engine-git/usr/bin/vegastrike
-- Installing: /z1/OS/aur/vegastrike-engine-git/pkg/vegastrike-engine-git/usr/bin/vegasettings
-- Installing: /z1/OS/aur/vegastrike-engine-git/pkg/vegastrike-engine-git/usr/bin/vega-meshtool
-- Installing: /z1/OS/aur/vegastrike-engine-git/pkg/vegastrike-engine-git/usr/share/doc/Vega_Strike/AUTHORS.SF
-- Installing: /z1/OS/aur/vegastrike-engine-git/pkg/vegastrike-engine-git/usr/share/doc/Vega_Strike/AUTHORS.GITHUB
CMake Error at doc/cmake_install.cmake:54 (file):
  file INSTALL cannot find
  "/z1/OS/aur/vegastrike-engine-git/src/Vega-Strike-Engine-Source/engine/../ChangeLog":
  No such file or directory.
Call Stack (most recent call first):
  cmake_install.cmake:65 (include)

make: *** [Makefile:116: install] Error 1
make: Leaving directory '/z1/OS/aur/vegastrike-engine-git/src/build'
==> ERROR: A failure occurred in package().

I'll investigate a little further, and hopefully find a fix, but this is the current status for me.

**Comment by BenjamenMeyer** [comment]
ChangeLog is a two-part file now: (1) the old change log from SF days; (2) the auto-generated changelog from git (`git log > ChangeLog`). We probably should update the CMake files to auto-generate the ChangeLog so it can get included. The auto-generated one doesn't need to be in git, so the packaging system should take charge of generating it.

**Comment by evertvorster** [comment]
@BenjamenMeyer does "make install" have the ability to make a ChangeLog file? 
I mean, I could script the git log bit into my package, but that would be specific to Arch. 

Someone running cmake, make & make install now will not get the ChangeLog, unless he or she makes the ChangeLog file beforehand. I would prefer a solution where the ChangeLog file exists in git, and is updated from time to time as problems are fixed.

**Comment by BenjamenMeyer** [comment]
@evertvorster we should be able to set something up by making a custom target in cmake to do so.

**Comment by stephengtuggy** [comment]
Hmm. That's an issue all right. Sounds like a pretty high-priority one to me.

**Comment by evertvorster** [comment]
@BenjamenMeyer Thinking about this a little more. If all the changelog is these days is a git log, why include it at all? 

My reasoning here is if someone is savvy enough to be wanting to know the recent changes in VegaStrike, then the information is available here on Github and with a plain git log.

**Comment by BenjamenMeyer** [comment]
@evertvorster historically the changeling was manually written, then as vcs systems came in folks started to automate them by using the vcs log. However the vcs log isn't always that easy to understand, so often folks out a tool around it to reformat it to something nicer.

Ideally we'd generate a log since the last release, and format it nicely along with a git hash so folks could know where the install dame from, what was fixed, new features, etc. So I'd probably start with a raw git log but then add a script to reformat it too. Might not be the best looking at first, but that's ok.

I'd also apply some filters. We don't have to report every log message, so removing things like Merge logs would be fine.

**Comment by evertvorster** [comment]
@BenjamenMeyer packagers are usually a bit hesitant to run scripts without checking to see exactly what they do. 
Like I said, making a script snippet that is Arch specific just to pass installation is not a challenge at all. But we have the opportunity to make something that will work for everybody.

**Comment by evertvorster** [comment]
@BenjamenMeyer  Stolen from the web:

git log --oneline $(git describe --tags --abbrev=0 @^)..@

**Comment by evertvorster** [comment]
@BenjamenMeyer or even:
git log $(git describe --tags --abbrev=0)..HEAD --no-merges --oneline

**Comment by BenjamenMeyer** [comment]
Yes I want something that would work for everyone.

**Comment by evertvorster** [comment]
Now that I am looking at it a little closer, there seems to be something weird. The make install finds the AUTHORS file, but not the ChangeLog file. Weird.

**Comment by BenjamenMeyer** [comment]
@evertvorster thanks for catching my mistake and fixing it in #429. We'll want to make sure that's fixed in both master and 0.7.x.
