### ISSUE TITLE
How to implement ptr_copy() (strdup equivalent) in a way that's both secure enough and cross-platform compatible?

### ISSUE THREAD

**Issue by stephengtuggy** [vegastrike/Vega-Strike-Engine-Source#430]
Code before:

```C++
char *ptr_copy(const char *string)
{
#if _XOPEN_SOURCE >= 500 || _POSIX_C_SOURCE >= 200809L
    return strdup(string);
#else
    size_t buf_size = strlen(string) + 1;
    char *alloc;
    alloc = (char *)malloc(buf_size);
    if (alloc == nullptr)
    {
        fprintf(stderr, "Out of memory\n");
        fflush(stderr);
        exit(-1);
    }
#ifdef __STDC_LIB_EXT1__
    strcpy_s(alloc, buf_size, string);
#else
    strncpy(alloc, string, buf_size);
#endif
    alloc[buf_size - 1] = '\0';
    return alloc;
#endif
}
```

My proposed rewrite:

```C++
char *ptr_copy(const char *string)
{
#if _XOPEN_SOURCE >= 500 || _POSIX_C_SOURCE >= 200809L
    return strdup(string);
#elif defined (_WINDOWS)
    return _strdup(string);
#else
    size_t buf_size = strlen(string) + 1;
    char *alloc;
    alloc = (char *)malloc(buf_size);
    if (alloc == nullptr)
    {
        fprintf(stderr, "Out of memory\n");
        fflush(stderr);
        exit(-1);
    }
    strncpy(alloc, string, buf_size);
    alloc[buf_size - 1] = '\0';
    return alloc;
#endif
}
```

Some links that may be relevant:

http://www.open-std.org/jtc1/sc22/wg14/www/docs/n2573.pdf
https://web.archive.org/web/20181230041359/http://www.open-std.org/jtc1/sc22/wg14/www/abq/c17_updated_proposed_fdis.pdf
http://www.open-std.org/jtc1/sc22/wg14/www/docs/n1570.pdf
https://en.wikipedia.org/wiki/C11_(C_standard_revision)#cite_note-21
https://stackoverflow.com/questions/372980/do-you-use-the-tr-24731-safe-functions/373911#373911
https://en.cppreference.com/w/cpp/string/byte/strncpy
https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/strdup-wcsdup?view=msvc-160
https://stackoverflow.com/a/26284172/5067822
https://man7.org/linux/man-pages/man3/strdup.3.html

See also prior discussion here: https://github.com/vegastrike/Vega-Strike-Engine-Source/pull/427#pullrequestreview-590575059

**Comment by BenjamenMeyer** [comment]
@stephengtuggy thanks! this looks good.
