### ISSUE TITLE
Accelerating with \ only works once

### ISSUE THREAD

**Issue by ichbinandy** [vegastrike/Vega-Strike-Engine-Source#449]
Hello I'm trying to build and play the version 0.7.0, but it has some quirks. One of them being, that I only can accelerate to full speed with the backslash once. If I then either stop or decelerate with minus, the backslash does not work any more.

I tried building versions 0.5 0.6 and 0.7 all with the same problem.

**Comment by BenjamenMeyer** [comment]
@ichbinandy thanks; yeah 0.5.1 is severely out of date for its dependencies. 0.6.0 primarily only differs in updating the dependencies (there were a couple other things IIRC).

**Comment by stephengtuggy** [comment]
@ichbinandy Do you have a joystick with a throttle, by any chance? If so, you might need to disable the throttle, so that it doesn't interfere with the keyboard speed controls.

Not sure if that's what you're running into; it's just a thought.

**Comment by ichbinandy** [comment]
Hi @stephengtuggy No I do not have any joystick, currently I was trying to play with a mouse in glide mode.

**Comment by stephengtuggy** [comment]
I see.

I will see if I can reproduce on my openSUSE Leap 15.2 virtual machine.

**Comment by stephengtuggy** [comment]
Well, I haven't been able to reproduce the issue so far, with Vega Strike / vsUTCS 0.7.0 on my openSUSE Leap 15.2 VM. I will probably try a few more times.

@ichbinandy Do you, perhaps, have an unusual keyboard layout?

**Comment by ichbinandy** [comment]
@stephengtuggy yes, now that you mention it, from your point of view the keyboard layout might be unusual. I use german layout

**Comment by stephengtuggy** [comment]
Ah. That's probably it. We have some [known issues](https://github.com/vegastrike/Vega-Strike-Engine-Source/issues/212#issuecomment-667680596) with non-US keyboard layouts already.

**Comment by stephengtuggy** [comment]
You might try remapping the "full speed" key to another key on the keyboard, as described in the issue ticket I linked, and see if that fixes it.

We'd better bump up the priority on the feature to remap keys more easily, though.

**Comment by BenjamenMeyer** [comment]
@stephengtuggy let's make that a requirement for 0.9.x; shouldn't be hard to do - just need a dialog that lists all our keyboard functions and then the ability to capture whatever the user presses.

**Comment by ichbinandy** [comment]
Hi @stephengtuggy thanks, remapping the key worked. 

btw inside the config file the full speed is mapped to backslash and that is written inside the xml with "\". I wonder, why this does not break the xml. I'd have expected the backslash to be escaped, so something like "\\" looks more correct.

**Comment by stephengtuggy** [comment]
Key remapping feature filed as #450

**Comment by stephengtuggy** [comment]
So @ichbinandy : Would you consider this issue fixed, in the short term by remapping the key in the config file, and in the long term by #450 ?

**Comment by ichbinandy** [comment]
Hi @stephengtuggy yes for me the remapping resolves the issue.

**Comment by stephengtuggy** [comment]
@ichbinandy Cool. I'll go ahead and close this ticket then.
