### ISSUE TITLE
Create Vega Strike wrapper macros for BOOST_LOG_TRIVIAL

### ISSUE THREAD

**Issue by stephengtuggy** [vegastrike/Vega-Strike-Engine-Source#455]
I think I agree that we need a wrapper macro or two. Maybe something like `VS_LOG_AND_FLUSH` and `VS_LOG` (without flushing). Each could take two arguments: the log level, such as `fatal` or `debug`; and the message to log. The message to log might be the result of running `boost::format` with some `%` operands. Simply enclosing the whole `boost::format` clause in an extra pair of parentheses should allow the macro to work, I think.

How does that sound?

_Originally posted by @stephengtuggy in https://github.com/vegastrike/Vega-Strike-Engine-Source/pull/453#discussion_r637330448_

**Comment by ermo** [comment]
Bonus points if it's trivial to create a rough set of commits with `sed` replacements across the code, so intent is mostly preservered and it becomes easier to review?

I like the implied semantics of `VS_LOG` and `VS_LOG_AND_FLUSH` FWIW.

**Comment by stephengtuggy** [comment]
As part of this, move the Vega Strike logging facilities to their own header file. (And .cpp file if needed. Maybe even a separate library.)

**Comment by stephengtuggy** [comment]
Global find:

```regex
BOOST_LOG_TRIVIAL\(fatal\)\s<<\s(.*);$
```

and replace with:

```
VegaStrikeLogging::VS_LOG_AND_FLUSH(fatal, $1);
```

**Comment by stephengtuggy** [comment]
Next, find all instances of `flushLogs()` across all source files, and correct them manually.

Then, find all:

```regex
BOOST_LOG_TRIVIAL\(info\)\s*<<\s*(boost::format\(.*\)\s*%.*);$
```

and replace with:

```
VS_LOG(info, ($1));
```

**Comment by stephengtuggy** [comment]
Find all:

```regex
BOOST_LOG_TRIVIAL\(trace\)\s*<<\s*(".*");$
```

and replace, carefully, with:

```
VS_LOG(trace, $1);
```

Find all:

```regex
BOOST_LOG_TRIVIAL\(debug\)\s*<<\s*(".*");$
```

and replace, carefully, with:

```
VS_LOG(debug, $1);
```

Find all:

```regex
BOOST_LOG_TRIVIAL\(info\)\s*<<\s*(".*");$
```

and replace, carefully, with:

```
VS_LOG(info, $1);
```

Find all:

```regex
BOOST_LOG_TRIVIAL\(warning\)\s*<<\s*(".*");$
```

and replace, carefully, with:

```
VS_LOG(warning, $1);
```

Find all:

```regex
BOOST_LOG_TRIVIAL\(error\)\s*<<\s*(".*");$
```

and replace, carefully, with:

```
VS_LOG(error, $1);
```

**Comment by stephengtuggy** [comment]
Unfortunately, there is still quite a bit of manual work to be done after these steps.
