### ISSUE TITLE
Port from OpenGL to Vulkan

### ISSUE THREAD

**Issue by BenjamenMeyer** [vegastrike/Vega-Strike-Engine-Source#46]
Vulkan is a newer version of OpenGL, and it'll be supported on Windows and Mac OS X too. It should also provide some higher performance. OpenGL will still be supported and advanced by Chronos (who also makes Vulkan)

How big an effort is this?
Is it worth the benefit?

**Comment by royfalk** [comment]
Only if it is a relatively small effort.
Consider that we want to ditch the whole 3d engine and port to Ogre.
I suspect that we wouldn’t be touching the low level graphics in that case and leaving it to the engine.

**Comment by stephengtuggy** [comment]
My 2 cents:

I think switching to Vulkan may be a rather large effort. (Though I don't know for sure.) But I definitely think it's worth it. Vulkan is the future, as far as I can tell. We won't be able to avoid it forever. Why not make the switch during the current push to modernize/overhaul/refactor the code?

**Comment by BenjamenMeyer** [comment]
This is really part of a larger discussion that got wrapped up in #72 and led to a lot of confusion. As that discussion involves this and updating any underlying libraries to do this, I'm closing this out in favor of #170.
