### ISSUE TITLE
Make FOV (Field of View) configurable

### ISSUE THREAD

**Issue by stephengtuggy** [vegastrike/Vega-Strike-Engine-Source#464]

**Comment by evertvorster** [comment]
Is this not already configurable?

**Comment by stephengtuggy** [comment]
@evertvorster I don't think so. Maybe I'm wrong though.

**Comment by stephengtuggy** [comment]
If there is a setting for it, which setting is it? And does it work?

**Comment by evertvorster** [comment]
[evert@Vorster ~]$ grep fov .vegastrike/vegastrike.config
        <var name="warp.fovlink.smoothing" value=".4"/>
  <var name="fov" value="37.5"/>
  <var name="base_fov" value="60.0"/>


It's the middle one, and yes, it works.

**Comment by stephengtuggy** [comment]
It does work! Sweet!
