### ISSUE TITLE
Static initialization ordering dependence for static std::map<string, string> GameConfig::variables

### ISSUE THREAD

**Issue by ministerofinformation** [vegastrike/Vega-Strike-Engine-Source#487]
std::map<string, string> variables in GameConfig.h is not guaranteed to be initialized before use in any call to 
static inline string _GetVariable(string const &section, string const &name) - such calls exist for lines such as 
Moveable.cpp:52 --
static Vector default_angular_velocity( GameConfig::GetVariable( "general", "pitch", 0.0f ),
                                        GameConfig::GetVariable( "general", "yaw", 0.0f ),
                                        GameConfig::GetVariable( "general", "roll", 0.0f));

Where GameConfig::GetVariable will call _GetVariable

This causes a crash on running due to null pointers in the std::map on (my) Windows build during the evaluation of the initializer for default_angular_velocity.

**Comment by stephengtuggy** [comment]
Would something like this be a potential solution? https://stackoverflow.com/a/17642967

**Comment by ministerofinformation** [comment]
Well, I suspect this particular issue will be fixed when the config library is finished; The example shown is actually broken even without static initialization ordering issues - it just isn't crash inducing (it will always get the default value because the config hasn't been loaded yet). While having an explicitly lazy initialization interface may be necessary in some cases,  we should avoid statics that depend on logically dynamic things wherever possible. I suspect that there will usually be another way to write most codes that isn't ordering sensitive, and we'll want to document explicitly any cases where it really needs to be done lazily.

**Comment by BenjamenMeyer** [comment]
@ministerofinformation that's one reason why we shouldn't be using statics and objects should get their configuration data at creation, which should all happen after `main` loads the configuration.

**Comment by ministerofinformation** [comment]
@BenjamenMeyer Yup. The old "standard" was always intra-method static caching in non-static methods, i.e. done on first call to the method, which would be after config load, but that left no way to guarantee that the defaults specified in two different files were set the same if it wasn't specified in the config file and no way to change the value consistently across scopes. So, centralization is just plain better, but intermediate points between the two approaches have undesirable properties :)
