### ISSUE TITLE
configuration.cpp: Undeclared identifier `M_PI` on Windows

### ISSUE THREAD

**Issue by stephengtuggy** [vegastrike/Vega-Strike-Engine-Source#494]
The Windows build still failed, with the following error:

```log
  D:\a\Vega-Strike-Engine-Source\Vega-Strike-Engine-Source\engine\src\configuration\configuration.cpp(19,42): error C2065: 'M_PI': undeclared identifier [D:\a\Vega-Strike-Engine-Source\Vega-Strike-Engine-Source\build\vegastrike-engine_com.vcxproj]
```

That looks fairly simple to fix.

_Originally posted by @stephengtuggy in https://github.com/vegastrike/Vega-Strike-Engine-Source/issues/484#issuecomment-877527376_

**Comment by ministerofinformation** [comment]
https://docs.microsoft.com/en-us/cpp/c-runtime-library/math-constants?view=msvc-160
