### ISSUE TITLE
PWCU on Windows: Crashes on startup with XML parse error

### ISSUE THREAD

**Issue by stephengtuggy** [vegastrike/Vega-Strike-Engine-Source#518]
Also tried testing with the PWCU data set on Windows, but it crashed on startup with an XML parse error. It sounds like PWCU wasn't working on Windows anyway, though, so not sure if this is a new issue either.

_Originally posted by @stephengtuggy in https://github.com/vegastrike/Vega-Strike-Engine-Source/issues/511#issuecomment-898949948_

**Comment by ermo** [comment]
I've never tested PWCU on Windows. I have no expectations of it working there.

**Comment by stephengtuggy** [comment]
@ermo I see.

**Comment by stephengtuggy** [comment]
Well, FWIW, this is fixed as of now.
