### ISSUE TITLE
On master, drop support for Ubuntu 16.04 "xenial" and Debian 9 "stretch"

### ISSUE THREAD

**Issue by stephengtuggy** [vegastrike/Vega-Strike-Engine-Source#528]
As discussed on Gitter.

This move will allow us to update our minimum supported CMake version to 3.10 or 3.11. That, in turn, should allow us to include unit tests in our CI/CD with GoogleTest.

**Comment by BenjamenMeyer** [comment]
Please make sure to update the the wiki too

**Comment by stephengtuggy** [comment]
Wiki updated.
