### ISSUE TITLE
script/bootstrap: Remove Python 2 from list of system dependencies to install

### ISSUE THREAD

**Issue by stephengtuggy** [vegastrike/Vega-Strike-Engine-Source#530]
On 0.8.x and on master

**Comment by stephengtuggy** [comment]
See also https://github.com/vegastrike/build-system-docker-images/issues/21

**Comment by stephengtuggy** [comment]
This has been done on master. I think it could also be done on 0.8.x, but not sure how high a priority that is.

**Comment by BenjamenMeyer** [comment]
@stephengtuggy we can leave 0.8.x as it is; it'll help provide transition if necessary.

0.6.x -> only Py2
0.7.x -> Py3 available but not default; Py2 default (only Py2 fully supported)
0.8.x -> Py2 available but not default; Py3 default (only Py3 fully supported)
0.9.x -> only P3

**Comment by stephengtuggy** [comment]
@BenjamenMeyer OK, sounds good. In that case, this issue can be closed.
