### ISSUE TITLE
Update Readme.md with instructions for building on Funtoo

### ISSUE THREAD

**Issue by stamasd** [vegastrike/Vega-Strike-Engine-Source#538]
As a segue to my previous issue https://github.com/vegastrike/Vega-Strike-Engine-Source/issues/510 I propose to make a small addition to Readme.md with some brief instructions for a successful compilation on Funtoo. Many distributions are listed there, but Funtoo isn't one of them (or any of the Gentoo derivatives for that matter.

In section "Compiling Vegastrike/Compiling on Linux" add in section 1:

"On Funtoo
Most dependencies are already met with a standard desktop Funtoo install. In particular, you want to make sure your "flavor" is set to desktop, and that you have a proper "mix-in" depending on the desktop manager you use. Check your current profile:
*sudo epro show*
and if you don't have the desktop flavor enabled, enable it with
*sudo epro flavor desktop*
Also enable the proper mix-in for your desktop manager; for instance xfce:
*sudo epro mix-in +xfce* (or gnome, kde etc)

The only dependency required for Vegastrike that isn't pulled in by the above steps is OpenAL. You must install this separately with:
*sudo emerge media-libs/openal*
And after that you are ready to compile."

No changes are needed anywhere else.

(to be clear, the setting of the flavor and desktop manager mix-in are standard steps done during a regular install of Funtoo, I just mentioned them here for completeness' sake; feel free to leave them out as they are in fact redundant. The only real requirement is installation of OpenAL as per the last command)

**Comment by stephengtuggy** [comment]
@stamasd Awesome! Would you mind submitting that change as a Pull Request?

**Comment by stamasd** [comment]
Haha okay. I've never made a PR on github before so let me see how that works first. Be prepared with a big fly swatter to undo any damage. :) It's a documentation change only, so hopefully that won't be needed.

**Comment by stephengtuggy** [comment]
@stamasd Sweet! Thanks.

**Comment by daviewales** [comment]
Can this be closed now?

**Comment by stephengtuggy** [comment]
> Can this be closed now?

Yes, I suppose it can. Thanks for pointing that out.
