### ISSUE TITLE
CMake error, ADD_SUBDIRECTORY not an existing directory

### ISSUE THREAD

**Issue by evertvorster** [vegastrike/Vega-Strike-Engine-Source#543]
Hi there!

I am getting an error in the configure stage of vegastrike-engine

Here is the error and a little surrounding text:
-----------snip---------
== Vega Strike Version: 0.9.0-b82d66d
!! Enabling Position Independent Executables/Shared Libraries (NOT RECOMMENDED on Ubuntu/Mint) !!
-- Check size of void*
-- Check size of void* - done
++ Python release(s) searched for : 3.9;3.8;3.7;3.6;3.5;3.4
-- Found PythonLibs: /usr/lib/libpython3.9.so (found version "3.9.6") 
++ Python library : /usr/lib/libpython3.9.so (3.9.6)
++ Python include dir : /usr/include/python3.9
++ Using System Boost
-- Could NOT find Boost (missing: Boost_INCLUDE_DIR) 
++ Using Internal Boost
++ Using Internal Boost::python3
CMake Error at CMakeLists.txt:434 (ADD_SUBDIRECTORY):
  ADD_SUBDIRECTORY given source "../ext/" which is not an existing directory.

++ boost dir: ../ext/
-- Found OpenGL: /usr/lib/libOpenGL.so   
++ OpenGL found : /usr/lib/libOpenGL.so;/usr/lib/libGLX.so;/usr/lib/libGLU.so
-- Found GLUT: /usr/lib/libglut.so  
++ GLUT found : /usr/lib/libglut.so;/usr/lib/libXmu.so;/usr/lib/libXi.so
-- Found OpenAL: /usr/lib/libopenal.so  
++ Found OpenAL
------------Snip-------------

**Comment by stephengtuggy** [comment]
That's weird. Looks like it's not finding Boost for some reason. It should use the System Boost installation, but it says it can't find it.

**Comment by BenjamenMeyer** [comment]
I think we dropped the `ext` directly when we stopped bundling dependencies. Odd...

**Comment by evertvorster** [comment]
Quite strange, and I think it's something with my install. Boost-libs was installed, and boost not.
It seems to be resolved now, and definitely nothing to do with the vegastrike.
