### ISSUE TITLE
Use `fpm` to bundle third-party dependencies across platforms?

### ISSUE THREAD

**Issue by stephengtuggy** [vegastrike/Vega-Strike-Engine-Source#55]
Another open-source project I've been involved with -- [wkhtmltopdf](https://github.com/wkhtmltopdf/packaging) -- uses something called [`fpm`](https://fpm.readthedocs.io/en/latest/) to pull in their third-party build dependencies across different platforms. `fpm` stands for "Effing Package Manager". :-P It seems to work rather well. Simplifies a lot of the process of finding all the right packages across Linux distros, macOS, Windows, etc., and downloading them all separately. Also, IIRC, it lets you keep all those third-party dependencies up to date. Which would be important for keeping security issues to a minimum.

What are you guys' thoughts?

**Comment by stephengtuggy** [comment]
Relates to #53

**Comment by stephengtuggy** [comment]
Relates to #54

**Comment by nabaco** [comment]
We should investigate that indeed.
We could also try out VCPKG, as it's more C++-dev oriented.

**Comment by pyramid3d** [comment]
There is also the https://conan.io/ package manager. A question to consider: how is the package hosting solved in the proposed solutions?

**Comment by pyramid3d** [comment]
Not sure, but Jenny may also be of help: https://github.com/bkaradzic/GENie

**Comment by BenjamenMeyer** [comment]
@pyramid3d what do you mean by package hosting? Third party libs? Or our own?

**Comment by pyramid3d** [comment]
I mean third party libs. I saw a conan setup where external libs would actually be hosted by the project, which I found a bit strange: But I understand too little about packaging tech to be able say if it is of any relevance to this topic.

**Comment by BenjamenMeyer** [comment]
@pyramid3d I'm not sure what the answer should be. We probably should have them cached some how as a fall-back, but we probably also want to rely on the third parties to provide their stuff. I'd be fully in favor of using the GitHub Packages stuff for it, but then we might run into money issues if it gets too popular without any income as there's a limited amount of "free" and then charges start.

So the best option looks to be:
- use a repo to just cache 3rd party dependencies
- try to install from 3rd party sources when possible
- if the 3rd party source is down then use our cache repo as a source

**Comment by nabaco** [comment]
In my windows compilation attempts I'm using Travis-CI caching abilities for the dependencies, and it works like a charm. Plus it really speeds up builds.
Maybe we can leverage that somehow?

Looking at Conan, I don't think we need to host anything, as it seems that everything is hosted on conan-center, but we might need to check that.

As a different option, VCPKG that I'm using now downloads the sources for each dependency, and compiles them locally. Then you can export that as a NuPKG. Maybe that can be hosted on our website/chocolatey?

The issue with binary hosting is that we need different binaries for each compiler/platform that we support.

**Comment by BenjamenMeyer** [comment]
@nabaco we should primarily only host source packages; exception might be providing some pre-built Windows binaries to save time. All other platforms a source tarball should be sufficient if it's not provided via a local packager.

**Comment by BenjamenMeyer** [comment]
For Linux systems we should use their respective package managers.
For Windows, we seem to be using vcpkg.
For Mac...not sure what we should use there.

I don't think we need to have a single tool unless there's one that easily bridges all the above - using package managers on a platform where applicable, etc.

@stephengtuggy should we close this out?

**Comment by stephengtuggy** [comment]
@BenjamenMeyer Yeah. Closing it out.
