### ISSUE TITLE
Possible alternate locations for .vegastrike subfolder on Windows

### ISSUE THREAD

**Issue by stephengtuggy** [vegastrike/Vega-Strike-Engine-Source#550]
On Windows, Vega Strike puts .vegastrike subfolder under `C:\Users\<user name>\Documents`. IMHO, this is less than ideal. I would like to see us put `.vegastrike` directly under the user's profile folder, i.e. `C:\Users\<user name>\.vegastrike`.

If we're going to make this change, we had better make it soon, because it won't be backwards compatible. After the change, any existing Windows users will "lose" their Vega Strike data. It will be in a different folder.

Note that I think legacy Vega Strike (v0.5.1r1 and prior) put the data under C:\Program Files or something strange like that. We won't be able to keep **that** same folder path, whatever we do. But with 0.8.x and onward, I would like to see us get it right.

**Comment by stephengtuggy** [comment]
Another possibility is that we should put the `.vegastrike` folder under `C:\Users\<user name>\AppData`, then either `Local` or `Roaming` underneath that. Between Local and Roaming, I'm not sure which is the best choice.

See discussion of this general issue on StackOverflow [here](https://stackoverflow.com/questions/57019/where-should-cross-platform-apps-keep-their-data?rq=1) .

**Comment by stephengtuggy** [comment]
To end up with:

- `C:\Users\<user name>\.vegastrike`: Change the following in vsfilesystem.cpp to use `CSIDL_PROFILE` instead of `CSIDL_PERSONAL`:

```c++11
    // Get user's home directory the MS way
    if (SUCCEEDED(SHGetFolderPathA(NULL,
                                CSIDL_PERSONAL,
                                NULL,
                                0,
                                szPath)))
```

- To end up with `C:\Users\<user name>\AppData\Roaming`: Use `CSIDL_APPDATA`
- To end up with `C:\Users\<user name>\AppData\Local`: Use `CSIDL_LOCAL_APPDATA`

**Comment by royfalk** [comment]
I generally think it should be under some kind of appdata folder. I'll comment on specific implementation when I review it, but am fine with using a windows specific API as per s/o post.

**Comment by stephengtuggy** [comment]
@royfalk Sounds good.

I'm thinking we go with `CSIDL_LOCAL_APPDATA`. That will most closely match the existing behavior of having the generated star systems, etc. be unique to a specific machine.

**Comment by ministerofinformation** [comment]
Seems good to me.

**Comment by ermo** [comment]
In the ideal scenario, the documentation will be able to list "your profile data is saved to `%appdata%/.vegastrike`" along with a screenshot showing what to type into the address bar of Windows Explorer.

IME using both the correct API _and_ an well-known path is a boon re. usability and documentation in general.

**Comment by BenjamenMeyer** [comment]
`%appdata%` is the correct location; whether it's the Roaming App Data or not really shouldn't matter for us as that is more to do with ActiveDirectory and storing data on a shared server (typically corporate type installs, not so much a home install).

Also, we can use `%appdata%/vegastrike/` since we don't need to hide the directory on Windows - it's already effectively hidden by being under `%appdata%`.

**Comment by stephengtuggy** [comment]
Using `CSIDL_LOCAL_APPDATA` would equate to `%LOCALAPPDATA%\vegastrike`. That's what I would like to go with. I do think you're right, @BenjamenMeyer , that we don't necessarily need the dot at the front of .vegastrike any more.

**Comment by stephengtuggy** [comment]
As I'm thinking about this some more, `%appdata%` is probably a little more well-known than `%localappdata%`. I guess we could go with that. What do you guys say? Shall we take a vote?

Thumbs up if you agree that Vega Strike's per-user data should live under `%appdata%` on Windows. Also known as `CSIDL_APPDATA`, also known as `C:\Users\<user name>\AppData\Roaming`. Thumbs down if you disagree.

**Comment by stephengtuggy** [comment]
Regarding removing the dot in front of `.vegastrike`, so that it becomes simply `vegastrike`, that's a little more complicated, now that I think about it. That part of the path lives in a different variable, `VSFileSystem::HOMESUBDIR`, I believe. We would have to create a special case for Windows for that variable. And then *another* special case for PWCU, which currently uses `.pu`. I don't think it's worth it to make this change, personally.

**Comment by BenjamenMeyer** [comment]
@stephengtuggy thanks for the analysis - I'm personally good with either version of `%appdata%`; as to `.vegastrike` vs `vegastrike` we can revisit that at another time; though it would be good to resolve it for Windows _before_ we make an official Windows release again.

**Comment by ermo** [comment]
> As I'm thinking about this some more, `%appdata%` is probably a little more well-known than `%localappdata%`. I guess we could go with that. What do you guys say? Shall we take a vote?
> 
> Thumbs up if you agree that Vega Strike's per-user data should live under `%appdata%` on Windows. Also known as `CSIDL_APPDATA`, also known as `C:\Users\<user name>\AppData\Roaming`. Thumbs down if you disagree.

To me it doesn't really matter whether it's `%localappdata%` or `%appdata%`. The important thing is that it can be specified as a variable in the documentation (so either is good for me). My vote is meant to convey this.

I do see several games saving their data under `%userprofile%/Documents/foo/bar`, including screenshots FWIW.

Does Microsoft have any actual recommendations/best practices re. this that we can lean on? If not, go with whatever feels the least wrong to you is my take.

**Comment by stephengtuggy** [comment]
So it sounds like there aren't strong opinions either way. OK. The one that feels "least wrong" to me is `%localappdata%`. :-)

And @BenjamenMeyer you're welcome.

**Comment by BenjamenMeyer** [comment]
> > As I'm thinking about this some more, `%appdata%` is probably a little more well-known than `%localappdata%`. I guess we could go with that. What do you guys say? Shall we take a vote?
> > Thumbs up if you agree that Vega Strike's per-user data should live under `%appdata%` on Windows. Also known as `CSIDL_APPDATA`, also known as `C:\Users\<user name>\AppData\Roaming`. Thumbs down if you disagree.
> 
> To me it doesn't really matter whether it's `%localappdata%` or `%appdata%`. The important thing is that it can be specified as a variable in the documentation (so either is good for me). My vote is meant to convey this.

:+1: 
 
> Does Microsoft have any actual recommendations/best practices re. this that we can lean on? If not, go with whatever feels the least wrong to you is my take.

Applications should store local system data in the non-Roaming profile application data space (`CSIDL_LOCAL_APPDATA/FOLDERID_LocalAppData`) and data that can be migrated between computers in the Roaming profile (`CSIDL_APPDATA/FOLDERID_RoamingAppData`).

Install time, common user data should be stored at `CSIDL_COMMON_APPDATA/FOLDERID_ProgramData`; but I don't think we have anything in this story for that. If we were to pre-generate the universe data instead of having it locally generated then it would certainly go in this location.

See https://docs.microsoft.com/en-us/windows/win32/shell/csidl for more information on the Windows provided variables.

**Comment by royfalk** [comment]
I'm sorry but I'm with @BenjamenMeyer. I don't have any preference one way or the other. Also, I'm on Linux and have been for almost twenty years now. I think whatever you prefer is fine.

**Comment by ermo** [comment]
> Applications should store local system data in the non-Roaming profile application data space (`CSIDL_LOCAL_APPDATA/FOLDERID_LocalAppData`) and data that can be migrated between computers in the Roaming profile (`CSIDL_APPDATA/FOLDERID_RoamingAppData`).
> 
> Install time, common user data should be stored at `CSIDL_COMMON_APPDATA/FOLDERID_ProgramData`; but I don't think we have anything in this story for that. If we were to pre-generate the universe data instead of having it locally generated then it would certainly go in this location.
> 
> See https://docs.microsoft.com/en-us/windows/win32/shell/csidl for more information on the Windows provided variables.

At the risk of muddying the waters further, that links shows that the CSIDL nomeclature is the pre-Vista way of doing things?

The current best practices for Vista and up is apparently to use https://docs.microsoft.com/en-us/windows/win32/shell/known-folders :

> Windows Vista introduces new storage scenarios and a new user profile namespace. To address these new factors, the older system of referring to standard folders by a CSIDL value has been replaced. As of Windows Vista, those folders are referenced by a new set of GUID values called Known Folder IDs.
>
> The Known Folder system provides these advantages: (...)

**Comment by stephengtuggy** [comment]
@ermo Looks like you're right. I'll look into that a little further.

**Comment by stephengtuggy** [comment]
So it looks like, in order to use the Known Folder system, an application has to support Unicode. Which Vega Strike doesn't yet. (The specific call we would need to make would be to the `SHGetKnownFolderPath` function, which returns a Unicode string.) I guess we'll need to continue using the CSIDL nomenclature for now, then.

**Comment by stephengtuggy** [comment]
https://docs.microsoft.com/en-us/windows/win32/api/shlobj_core/nf-shlobj_core-shgetknownfolderpath

**Comment by BenjamenMeyer** [comment]
https://docs.microsoft.com/en-us/windows/win32/shell/knownfolderid
- FOLDERID_RoamingAppData
- FOLDERID_LocalAppData

https://docs.microsoft.com/en-us/windows/win32/shell/known-folders
https://docs.microsoft.com/en-us/windows/win32/shell/how-to-extend-known-folders-with-custom-folders
per above we could even define our own as part of the VS install since while the CSIDL versions could not be extended, the newer version can be, in which case we could define:
- VS_ASSET_DATA
- VS_USER_HOME

Any how...extending it would be interesting...but that's probably for a later story - just pointing out the new possibilities.

Per https://github.com/vegastrike/Vega-Strike-Engine-Source/wiki/Platform-Support we support Win10+ so we can do most anything.

**Comment by BenjamenMeyer** [comment]
@stephengtuggy probably depends on which function you use to look it up; though since it's already platform dependent code we could just do a WTOMCBS conversion on the result to convert out of Windows Unicode.

**Comment by stephengtuggy** [comment]
@BenjamenMeyer the `SHGetKnownFolderPath` function is unusual among Win32 functions, in that it only has a …W version, not a …A version. So `SHGetKnownFolderPathW`. At least according to the documentation I found.

Are we guaranteed to be able to convert the Unicode return value to a `std::string`? Or perhaps we could just switch to using Boost Filesystem `path` instances everywhere (instead of `string`s), and be done with it.

**Comment by BenjamenMeyer** [comment]
@stephengtuggy you can take the Windows Unicode value and run it through `wctombcs()` to get a value valid for std::string. That is guaranteed.
 https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/wcstombs-wcstombs-l?view=msvc-160

**Comment by stephengtuggy** [comment]
@BenjamenMeyer Good to know.
