### ISSUE TITLE
Announce the return from the dead of this project

### ISSUE THREAD

**Issue by royfalk** [vegastrike/Vega-Strike-Engine-Source#58]
I've been playing this game since 2005 or so and development tapered off around 2010 or a bit later. So much so that there are posts in https://forums.vega-strike.org/ asking whether the project is still alive. 
We need to boldly claim it is and start communicating with the users. I saw there was a post there about moving to github. 

To Do:
- Announce something in the forums
- Announce something in the website
- Announce something in the wiki
- A call to volunteers (see below)

In their own issues:
- Polish the forums GUI. It's a blast from the 90's but we can do better today.
- Start updating the website, perhaps automatically. Remove old stuff like compilation instructions that are wrong or links to SVN.
- Consider moving the wiki here?
- Manual testing by testers of weekly releases (no need for nightly build yet).

I'm sure there's more but mostly, I don't want to release 0.6 or whatever and not have people play it.

**Comment by BenjamenMeyer** [comment]
@royfalk I agree. I've played a variant (Privateer Gemini) in the past. I've tried to get involved here in the last few years just haven't had time, so I'm excited to see this all moving right now.

1. Yes, I'd love to move the Wiki here. The Wiki's in Git are git version controlled, you can check them out just like any repo for quick migrations, etc.
2. I'd like to hold off on an announcement until we have some of the discussions settled out, but yes, let's not forget to do that. My concern is hindering momentum by too many cooks in the kitchen. Certainly if there's any old-guard or folks that know the system well please invite them in so we can get knowledge transfers (if they can't stick around) or additional help from knowledgeable folks too. But let's get some things standardized and basic decisions (#41, #34, may be a few others) done so we have places we can start directing people.
3. Forums...I'm not sure how much forums are used any more. Our decision in #34 might end up changing that significantly. There's certainly a need to stabilize the server running the forums, wikis, etc - it doesn't seem to respond 50+% of the time right now (not good).
4. Website.... GitHub Pages might solve some of that for us; especially if we don't need the forum any more.
5. Compilation directions...we need that to be in the repo itself, a good README file that we can link in the Wikis. Git repos tend to keep a lot of that stuff in repo so it's easy to diffuse with the source.

**Comment by pyramid3d** [comment]
Use available infrastructure as much as possible. It would be beneficial to gain access to the old servers (forum, web, wiki) and archive everything. Daniel still should have the power to grant that access.
As far as knowledge transfer goes, all my brain is put into the wiki, though I am happy to help answer the one or other question as much as possible.
I am glad to see this project move again. Keep on flying!

**Comment by BottledByte** [comment]
As @bmorel mentioned on Gitter, [https://freegamedev.net](https://freegamedev.net) is nice place for this project revival notice and I can only agree with the idea.
Furthermore, there is an option to use [https://social.freegamedev.net/channel/planet](https://social.freegamedev.net/channel/planet) RSS channel for this project. As far as I know, it is possible to link it directly with Github Releases, so on each release, there is no need to mention it there *by hand*.
And [LibreGameWiki](https://libregamewiki.org/) should not be overlooked, as it is possible to announce releases there (0.5.3 was announced this way) and present some further information about the project (like "where to find us") there might be a good idea. VS is already there, but the info is somewhat old and some links there are dead now.

**Comment by BenjamenMeyer** [comment]
We need to be sure to update https://en.wikipedia.org/wiki/Vega_Strike too when we do that announcement.

**Comment by BenjamenMeyer** [comment]
This certainly needs to be done as part of the 0.6.x release:
- [ ] Twitter
- [ ] Facebook Group
- [ ] Pluspora
- [ ] Vega Strike Forums
- [ ] FreeNode IRC #vegastrike 

And where ever else we can think of to make noise.

**Comment by BenjamenMeyer** [comment]
Thanks @evertvorster 
https://www.awesomechapters.com/2020/06/20/vega-strike-in-week-25-of-2020/

**Comment by evertvorster** [comment]
Arch Linux already supports several branches of Vega Strike Source code. 
Packages in AUR now:

Data:
**vegastrike-git**   (Game data for Vega Strike, will require you to pick an engine)
**privateer_wcu-git** (Game data for Privateer Gemini Gold remake, will require you to pick an engine)

Engines:
**vegastrike-engine-stable-git**  (Vega Strike engine, follows last version of previous branch, currently: stable_2020)

**vegastrike-engine-release-git** (Vega Strike engine, follows latest released branch, currently 0.6.x)

**vegastrike-engine-git** (Vega Strike engine, follows git master, Python 3 enabled)

**vegastrike-py2-engine-git** (Vega Strike engine, follows git master, Python 2 enabled)

The data packages can be installed concurrently, but only one engine can be installed at any time. 
Feel free to mention this when you do the release announcements. ;)

**Comment by Loki1950** [comment]
@evertvorster Privateer Gemini Gold was a complete fork with an attendant long flame war at it's inception and make many changes to the engine as they only supported the Privateer data set they developed their version independently and left the project completely the Privateer data set we use is the Privateer Universe one not PGG at all and I doubt that it would be compatible with the current engine at all they would very much dispute our use of the name.

**Comment by BenjamenMeyer** [comment]
yeah, the PWCU repo is Privateer Wing Commander Universe: Parallel Universe. I don't know how close it is to Gemini Gold. @ermo  might be able to speak more to that as he knows the history of that side more. Either way... I wouldn't mention Gemini Gold at all.

**Comment by evertvorster** [comment]
@Loki1950  Oops, my bad. 
Looks like Gemini Gold is a sore spot, and I won't mention it again. Thanks for the pointer!
I suppose my confusion came in because I played the original Privateer from Origin, and was not really involved in the remakes.

At least I named the package correctly. Moreover, the privateer_wcu runs on an unmodified Vega Strike engine, which is a good thing.

**Comment by Loki1950** [comment]
That and the fact they have a new release they dropped a few months back even announced it on our forum which is a bit on the provocative side.

**Comment by evertvorster** [comment]
I have updated the Wikipedia article to reflect the fact that development on this fantastic project has re-started. 

https://en.wikipedia.org/wiki/Vega_Strike

I registered at Wikipedia especially for this, so if you feel the need to add, update or in any way modify the Vega Strike page in Wikipedia, but don't feel bothered to do the hoop-jumping exercise of registering and learning HTML to edit it, just let me know what you would like to see. I'll promise to make a best effort on a good edit on your behalf.

**Comment by BenjamenMeyer** [comment]
We have the social accounts now - most of them; Alpha 7 has been promoted to Beta 1; and we've got a release date set to 2020/10/01 for 0.6.x so need to get an announcement together. We need several:

- [ ] Twitter (160 characters)
- [ ] Facebook, MeWe, PlusPora

At this point, we'd need to plan out something for YouTube so I suggest we skip YouTube for the moment. Filed #329 for that aspect; assigned to 0.9.x to give us time to do it.

**Comment by BenjamenMeyer** [comment]
Proposed announcement:
```
It is with great pleasure that the Vega Strike Development Team announces the release of Vega Strike 0.6.0.

Join our protagonist Deucalion in adventures around the universe as a bounty hunter, mercenary, or merchant flying through the
stars. Meet the Aera and Rlaan. Battle with the Confederation. Run alongside Pirates. Or just buy and sell as a merchant while your
explore. The universe and the adventure is yours.

What's change?

Since our last release in 2012 of Vega Strike 0.5.1 we've made a few minor changes for 0.6.0. With a mostly new development team leading
the way we've updated the dependencies to work on the newer systems, and fixed a few necessary bugs in the process. Development has also
moved from our old home at Source Forge (https://sourceforge.net/projects/vegastrike/) to our new home at Git Hub (https://github.com/vegastrike).

Want to help out?

There's lots to do. We're working diligently update Vega Strike. Version 0.6.0 is just our first step, showing it can still be done.
We've already got several releases planned in the process of continuing to update our dependencies and fix bugs; you can see our Road Map at
https://www.vega-strike.org/roadmap/. There's needs all around from coding, story development, art work, documentation, and even just generally helping the community.

The development team is active at https://gitter.im/vegastrike/community and we'd love to hear from you.

You can also find the community at https://forums.vega-strike.org/.
```

**Comment by royfalk** [comment]
Join our protagonist Deucalion in adventures around the universe as a bounty hunter, mercenary, or merchant flying through the
stars. Meet the _deadly_ Aera and _mysterious_ Rlaan. Battle with the Confederation. Run alongside Pirates. Or just buy and sell as a merchant while ~~your~~ _you_ explore. The universe and ~~the~~ adventure ~~is~~ _are_ yours.

What's ~~change~~ changed?

Since our last release in 2012 of Vega Strike 0.5.1 we've made a few minor changes for 0.6.0. With a mostly new development team leading the way we've updated the dependencies to work on the newer systems, and fixed a few necessary bugs in the process. Development has also moved from our old home at Source Forge (https://sourceforge.net/projects/vegastrike/) to our new home at Git Hub (https://github.com/vegastrike).

Want to help out?

There's ~~lots~~ _a lot_ to do. We're working diligently _to_ update Vega Strike. Version 0.6.0 is just our first step, showing it can still be done.
We've already got several releases planned in the process of continuing to update our dependencies and fix bugs; you can see our Road Map at https://www.vega-strike.org/roadmap/. ~~There's needs all around~~ _We need everything_ from coding, story development, art work, documentation, and even just generally helping the community.

**Comment by stephengtuggy** [comment]
I think it would be good to have multiple people test 0.6.0 Beta 1 in the next day or two, just to have some assurance that it's not completely busted. 😄

**Comment by BenjamenMeyer** [comment]
@stephengtuggy proposing #331 going forward, but yes I'd love to have some more folks test it. Same with the final release before we do the announcements.

**Comment by BenjamenMeyer** [comment]
We've made all the announcements about 0.6.0 being released. Closing.
