### ISSUE TITLE
FCMP is poorly documented...

### ISSUE THREAD

**Issue by evertvorster** [vegastrike/Vega-Strike-Engine-Source#590]
Reading through the flight manual, I realized that the ` (tilde) key turns on and off the FCMP. 

When pressing ESC, this option is not on the list of buttons, and I might be speaking under correction here, but I don't believe that Oswald mentions this in his tutorial, as he really does not go into fighting techniques that much. 

Is this button supposed to be an easter egg?

**Comment by stephengtuggy** [comment]
You're not wrong. I've been wondering for ages how to turn off the FCMP. Couldn't find a key shortcut documented anywhere. Now I know, so thanks.

**Comment by BenjamenMeyer** [comment]
FYI - it's also https://github.com/vegastrike/Assets-Production/blob/master/documentation/Vega_Strike_Players_Guide.pdf
