### ISSUE TITLE
FCMP:ON does weird things... 

### ISSUE THREAD

**Issue by evertvorster** [vegastrike/Vega-Strike-Engine-Source#591]
I do believe that this thing is the reason our autopilot acts so weird when it nears the end of it's journey. 

From my limited understanding, and initial play testing, this should only reduce ship's speed. 
ie: when turning the vessel, FCMP is supposed to counter the inertia that the vessel already has, by firing retro thrusters or something, reducing the velocity of the vessel in the direction it was already traveling. This is supposedly to enable easier flight, and to mimic other space flight simulators.

However, this is not the case, if you keep your eye on vessel speed while maneuvering near installations, you will see that the vessel speed actually goes up, beyond the set speed. This could be what is throwing off the autopilot!

If I remember correctly, when I first began play-testing VS last year, this was not the case, and the autopilot was not crazy.

**Comment by stephengtuggy** [comment]
@evertvorster when you say the autopilot is `crazy` or `acts weird`, can you be more specific? What exactly does it do? I think I know what you are talking about, but I would like to make sure we are on the same page.

**Comment by evertvorster** [comment]
Oh, of course I can be more specific. 

When nearing the destination, I expect the autopilot to switch off the SPEC, and then once it's near enough, hand over control of the ship to me. It should be doing this flying in a straight line, only deviating from this straight line to avoid collisions. 
That is what I would consider normal. 


What is actually happening, is that when nearing the destination, the autopilot seems to be doing it's obstacle avoidance thing while still in SPEC. However, once SPEC switches off and before it hands over control to me, it is not flying in a straight line anymore. It would erratically fly in almost any direction. This is most definitely not obstacle avoidance, as the path is clear between the ship and the destination. 
There is some video of this behavior somewhere online. I am currently on a 20kbps internet link, so anything beyond text is simply out of the question, and I can't go look it up. 

It's the sort of flight path I would take if my brakes had failed and I was trying to not hit the destination... However, the ship is still many thousands of meters away from the target, and auto pilot is still engaged. 

I did mention the speed increase beyond the set point while the ship is maneuvering. 
I hope this helps?

**Comment by stephengtuggy** [comment]
@evertvorster Yes, that's very clear, thank you.

**Comment by evertvorster** [comment]
Now that I am playing this again, there seems to be a little more insight into this bug. 
I did some spot reading of the manual, as well as try to look for where FCMP and Vega Strike are mentioned together on the internet. 

This is what I gleaned so far:
FCMP stands for flight computer. (Or flight compensation) Your flight computer uses the ship's thrusters to turn your inputs into momentum. It does not seem to affect the roll thrusters, those work all the time, no matter what mode FCMP is in.
In general, your FCMP enforces the top speed for your craft in combat mode, and allows you to change direction as if you are flying an aircraft in an atmosphere. You can turn it off, and then it does not use the thrusters at all, allowing you to slide past a foe and strafe it. I played with it a little, and indeed that is what it does. 
My testing was as follows. Stop the ship, then turn off FCMP. Now set a speed, and you will see that you are able to turn, but the craft does not move. When you turn on FCMP, the craft then speeds up to match the top speed. 

So, FCMP is supposed to be on unless you want to do sliding maneuvers. I'll close this bug, as FCMP ON/OFF does seem to do what it is supposed to.
