### ISSUE TITLE
Use CMake 3.14 PIE logic when available?

### ISSUE THREAD

**Issue by stephengtuggy** [vegastrike/Vega-Strike-Engine-Source#599]
Understood that we don't want to move to 3.14 yet as our minimum supported CMake version. However, in those cases where we do have CMake 3.14 available, I think we should use the PIE support that it natively provides. (An `IF...ELSE` kind of thing.)

**Comment by royfalk** [comment]
If I understand correctly (based on https://access.redhat.com/blogs/766093/posts/1975793), this hardens the executable against certain attacks. I'm not sure if this is necessary for us, but I don't mind. 
I agree with @BenjamenMeyer about introducing it in 0.9.

**Comment by BenjamenMeyer** [comment]
> If I understand correctly (based on https://access.redhat.com/blogs/766093/posts/1975793), this hardens the executable against certain attacks. I'm not sure if this is necessary for us, but I don't mind.

It's not at the moment; but it will be once we reintroduce the networking functionality.
