### ISSUE TITLE
Getting message "Assumed exit on unit..."

### ISSUE THREAD

**Issue by stephengtuggy** [vegastrike/Vega-Strike-Engine-Source#6]

**Comment by LifWirser** [comment]
Message is old troubleshooting from Python, it doers not seem to affect gameplay.
SUGGEST: add to Audit_Python issues

**Comment by nabaco** [comment]
Related to #17

**Comment by stephengtuggy** [comment]
I believe this is now fixed, and can be closed. I'm not getting this message anymore.

**Comment by BenjamenMeyer** [comment]
@stephengtuggy can we please confirm this is fixed and close it out if it is?

**Comment by stephengtuggy** [comment]
It's fixed. Closing.
