### ISSUE TITLE
When the ship is destroyed, the pilot should auto-eject some of the time.

### ISSUE THREAD

**Issue by royfalk** [vegastrike/Vega-Strike-Engine-Source#600]
Currently, it looks like the pilot auto-ejects all/most of the time. This does not appear to be the correct behavior.

**Required**

1. Find the old code and figure out the correct ratio.
2. Find the new code and fix the ratio to match.

**Comment by stephengtuggy** [comment]
I really can't die in this game now. At least not without immediately and automatically respawning in a new pilot eject capsule. And I don't even see the "you have died" screen. (See comment on #602 .)

So the code is definitely broken. We'll have to figure out how to fix it.

**Comment by stephengtuggy** [comment]
And the old code was: https://github.com/vegastrike/Vega-Strike-Engine-Source/blob/e72b292a39324aad22ea2294beb36994f6e9fcc5/engine/src/cmd/unit_generic.cpp#L6894-L6907

**Comment by stephengtuggy** [comment]
Judging by the way it was used previously, I think `player_autoeject` should be interpreted as `is_player_autoeject_allowed`. (Maybe we should even rename it to that.)

In the old version of the code, the logic was 

"If Player Auto-Eject is allowed AND a random number falls into the right range, then auto-eject."

In the more recent version of the code, the logic became 

"If Player Auto-Eject is allowed OR a random number falls into the right range, then auto-eject."

Do you see the problem? Auto-ejecting effectively became unconditional. Chances are now 100% that it will happen. (Apart from some funky config modification or other.)
