### ISSUE TITLE
build.sh errors out if the starting path has spaces in it

### ISSUE THREAD

**Issue by stephengtuggy** [vegastrike/Vega-Strike-Engine-Source#606]
We need to wrap $BUILD_DIR in both braces {} and quotes "", ideally, to solve this problem.

**Comment by BenjamenMeyer** [comment]
We should use `${VAR}` for any numeric variables; and `"${STRING_VAR}"` for any string variables.
The shell supports both; and we can use `-ge` , `-lt, `-eq`, etc on the numerics (typically integer).

**Comment by stephengtuggy** [comment]
Fixed in #607 and #613 .
