### ISSUE TITLE
Vega Strike Settings does not provide the actual settings

### ISSUE THREAD

**Issue by BenjamenMeyer** [vegastrike/Vega-Strike-Engine-Source#609]
From the Vega Strike Forum: https://forums.vega-strike.org/viewtopic.php?f=1&t=51640

You can see the issue with the settings in this image:
https://forums.vega-strike.org/download/file.php?id=2686&t=1&sid=b1bedc73d801313c2781581af457d0e1

They've tried to save the settings; but vegastrike refuses to load properly.
Some more diagnostics are required.

They are running version 0.7.0.

**Comment by stephengtuggy** [comment]
![Vega-Strike_in_activities_menu](https://user-images.githubusercontent.com/13305766/143510299-a7742fca-542d-487b-b423-872a109554b1.png)

**Comment by stephengtuggy** [comment]
![Vega-Strike_Config](https://user-images.githubusercontent.com/13305766/143510310-3f003161-4685-4e1b-b554-37a0f4e23939.jpg)

**Comment by stephengtuggy** [comment]
![Vega-Strike_Broken-Config](https://user-images.githubusercontent.com/13305766/143510324-72470fce-9507-4251-97f1-8c8cb3301b6d.png)

**Comment by Loki1950** [comment]
Comment from the reporter said he was getting permission denied messages

**Comment by BenjamenMeyer** [comment]
if it's just a permissions issue, then we should try to report that as well, both in the engine and in the settings.

**Comment by stephengtuggy** [comment]
Permission denied messages are expected when running `find` on one's entire directory tree. These can probably be safely ignored. (I probably should have mentioned that sooner.)

What I'm really interested in is what non-error results came back.

**Comment by stephengtuggy** [comment]
At this point, my hunch is that the OP has one or more copies of vegastrike.config containing invalid syntax, somewhere in one of the paths that Vega Strike searches for that file. If we can find the errant file and correct its contents, then hopefully vsettings will start working.

**Comment by BenjamenMeyer** [comment]
Possibly, but we should confirm they have permission to the .vegastrike directory and the config files under it

**Comment by stephengtuggy** [comment]
OP confirms that the issue was fixed by renaming / deleting the empty vegastrike.config in their home directory.
