### ISSUE TITLE
Locating the `taose` code

### ISSUE THREAD

**Issue by BenjamenMeyer** [vegastrike/Vega-Strike-Engine-Source#61]
There is fork that utilizes a branch named `taose` which according to @LifWirser is suppose to be available here. Let's find it and ensure the branch is tracked properly.

@LifWirser  is https://github.com/Taose/Vegastrike-taose it?

**Comment by zonkmachine** [comment]
is https://github.com/Taose/Vegastrike-taose it?

Yes. Announcement here: https://forums.vega-strike.org/viewtopic.php?f=8&t=27852

**Comment by BenjamenMeyer** [comment]
Cool. We can certainly check against it and reference it as we bring things up.

**Comment by zonkmachine** [comment]
And maybe bumping @Taose works too?

**Comment by pyramid3d** [comment]
Don't bother. It is a very old code forked even before the move of the main code from svn to github. The history is lost on that fork but I can confirm that it does not contain any changes over the past 10 years or so.

**Comment by ermo** [comment]
This can be closed, can't it?

**Comment by BenjamenMeyer** [comment]
I think so - we've found it, documented it, and been told it's already been integrated into the source we're working with.

Closing unless there's something I'm missing - in which case, please re-open.
