### ISSUE TITLE
Who should be in the Core group?

### ISSUE THREAD

**Issue by BenjamenMeyer** [vegastrike/Vega-Strike-Engine-Source#62]
Who should be in the core development and reviewers group?

Requirements:
- be active
- review PRs
- be in the chat channels (once established) on a regularly basis
- answer questions
- help establish the rules for contributions, etc.

**Comment by BenjamenMeyer** [comment]
I'd like to start off by nominating the following:
- @LifWirser 
- @stephengtuggy 
- @Loki1950 
- @pyramid3d

**Comment by royfalk** [comment]
Note that @Loki1950, by his own admission, doesn't know C++.

I'd separate this into two roles: reviewer and dev.
I'd nominate @BenjamenMeyer as additional reviewer. He has the experience and bandwidth to do this. He also seems willing to do this. 

Even though I joined the team at the same time as Stephen, I prefer not to be an official reviewer for one simple reason. I am an experienced programmer but not an experienced C++ one. I may well miss something when reviewing and approve bad code that would be obvious to anyone else.
Also, I came here to get some coding done, with minimum overhead.

One concern I have is bandwidth. Of the reviewers, @BenjamenMeyer is the most active. If we see PR's not handled in a timely fashion, perhaps add @nabaco. This depends on his level of expertise and willingness to review.

**Comment by nabaco** [comment]
Hi @royfalk, as willing as I am to review PRs, I have the same problem that you do. I'm mostly a C programmer, and am quite new to C++ **and** this project.

Though I would like to say that reviewing PRs doesn't necessarily requires knowledge of C++. Once PRs will begin coming from outside of the core group, there will PRs for python, documentation, art, music, etc. So the question is, @BenjamenMeyer, what do you consider as "core" dev/reviewer?

I think, as stated above, the most important thing for anyone in the "core" group is to be active, so even if he lacks the professional knowledge for that specific PR, he'll know whom to tag to have a look.

**Comment by BenjamenMeyer** [comment]
@royfalk  thanks for the nomination; if enough folks agree (especially @LifWirser) I'll accept.

@nabaco that's mostly a question to the community; generally it's what I outlined above and also merge responsibility.

@royfalk as @nabaco pointed out - there's a lot of stuff here. Right now we're mostly focused on the C++ code, but expertise in other areas will be important too. Even as we work on the C++ side we'll need to know how that impacts the Python side and other things. The core team will need to get familiar with all of those things over time, but may start out from different areas of expertise - especially if we can't get some of the long term contributors to join in.

**Comment by stephengtuggy** [comment]
I believe @LifWirser indicated that he was feeling the need to take a step back from the project, and "fade into the background" (if I recall his words correctly). I suggest that we honor his request, and allow him to do just that.

As for myself, I really appreciate the invitation to be a member of the core group. I will consider it and get back to you guys, hopefully within a day or two.

Like @BenjamenMeyer mentioned, I think the key criteria here is active participation. Languages can be learned -- especially if you are reviewing others' code on a regular basis. I would say the key is to participate, and to do so in a mature way as individuals and as a community -- like @pyramid3d articulated so well on the forums a couple months back.

Thanks, guys!

**Comment by stephengtuggy** [comment]
Oh, one other thing: I would like membership in the "core" group to be flexible, and somewhat subject to change. As other contributors join the community (hopefully) and begin taking a more active role -- showing both maturity and the ability to contribute positively on a technical level -- I would like the invitation to be extended to them as well.

I am a big fan of inclusivity, myself. :sunglasses:

**Comment by stephengtuggy** [comment]
And I would like to nominate @BenjamenMeyer as well. :+1:

**Comment by BenjamenMeyer** [comment]
@stephengtuggy  yes, I see it as a group that will change over time. As things mature we'll come up with a method of making that change (voting, proposals, etc.). I've seen a few different models by different communities:

- Community nominates with open membership
- Community has a small set that rotates based on votes and time frames
- Static membership, community votes when folks step down to add new members
- Assigned membership by existing members (invited in).

Right now we just need a group to help move things along. We can decide later which model we want to use going forward.

**Comment by stephengtuggy** [comment]
Can this issue be closed?

**Comment by BenjamenMeyer** [comment]
@stephengtuggy yes. I'll file an issue on the other stuff and close this one, linking it here first.

**Comment by BenjamenMeyer** [comment]
#110 to carry on the questions from https://github.com/vegastrike/Vega-Strike-Engine-Source/issues/62#issuecomment-612096105. We're not ready to answer those questions, but we are ready to close this issue.

**Comment by pyramid3d** [comment]
I am flattered by the nomination, though I do not see myself as a core member. Should there be an alumni group created, that's where I would be ;-)

**Comment by BenjamenMeyer** [comment]
@pyramid3d I think we'll cover that in the `Historic Owners` group being proposed at https://gist.github.com/BenjamenMeyer/07d9c1bf7aaf88c74adbf7a0b186dd6f#historic-owners, though perhaps `alumni` is a better name?
