### ISSUE TITLE
Enabling `-funsafe-math-optimizations` causes weird game behavior

### ISSUE THREAD

**Issue by stephengtuggy** [vegastrike/Vega-Strike-Engine-Source#622]
I don't normally use any of the CPU tuning CMake options. When I do, however, the game does strange things. Especially in the "9k idle, 1k fighting" scenario, where going into SPEC mode apparently makes you travel infinitely fast. (At least, judging by the lengths of the star streaks on the screen.)

IIRC, a year or so ago I was able to narrow down the cause of this "infinite speed" issue to the `-funsafe-math-optimizations` compile switch specifically. I suggest that we take that out of each of the CPU tuning options in CMakeLists.txt. The inaccuracies it creates are not worth the little bit of extra performance it might give us.

**Comment by BenjamenMeyer** [comment]
Most of the current CPUs probably don't need the additional compiler flags like were done with the K6, Pentium, and older flags. Compilers probably get it right more often than not any more.

**Comment by BenjamenMeyer** [comment]
Let's try to address this for 0.8.x - should be a simple change and then some moderate testing to verify - if we can. if not, leave a comment and we'll address in 0.9.x
