### ISSUE TITLE
`build.sh`: Cap # of CPU cores used to build the code?

### ISSUE THREAD

**Issue by stephengtuggy** [vegastrike/Vega-Strike-Engine-Source#629]
Shall we set a maximum number of CPU cores to build Vega Strike with? Like, say, 8? (So that the build process doesn't take up too much RAM.)

**Comment by BenjamenMeyer** [comment]
it would be good to have an option for it if people want to use it; generally CMake/Make should do the right thing, but it's still useful to have.

**Comment by stephengtuggy** [comment]
Well, in `build.sh`, we actually specify the number of threads for CMake/Make to use, based on the number of CPU cores detected. Maybe we should just take that part out?

**Comment by BenjamenMeyer** [comment]
we should test `build.sh` and see what does better since it's used by our CI so we should make sure it respects any limits the CI systems have or otherwise be respectful of the CI systems. Devs should be able to easily override it for other behavior; though personally I use `cmake` directly.

**Comment by stephengtuggy** [comment]
When I don't specify the number of cores to use, cmake uses 4 cores on my 6-core system. I think that's a good load level. We should probably just let cmake figure out how many threads to use in build.sh, too.

**Comment by stephengtuggy** [comment]
So this didn't work. When I tried taking out the `-j` flag, cmake built multiple targets in parallel, but the targets that took the longest -- vegastrike-engine_com and vegastrike-engine -- were built only one or two files at a time. The overall result was a much slower build process than usual on my hardware.

**Comment by stephengtuggy** [comment]
I think I will go back to specifying `-j` with the number of CPU cores detected, but cap the number at 8 or so, like the title of this ticket originally suggested.

@royfalk I'm interested to hear your thoughts on this.

**Comment by stephengtuggy** [comment]
Here's what my draft code looks like in `build.sh`:

```bash
MAX_THREADS_TO_BUILD_WITH=8
NUM_THREADS_TO_BUILD_WITH=$(getconf _NPROCESSORS_ONLN)
if [ ${NUM_THREADS_TO_BUILD_WITH} -gt ${MAX_THREADS_TO_BUILD_WITH} ]
then
    NUM_THREADS_TO_BUILD_WITH=${MAX_THREADS_TO_BUILD_WITH}
fi

VERBOSE=1 cmake --build "${BUILD_DIR}" -j ${NUM_THREADS_TO_BUILD_WITH}
```

**Comment by stephengtuggy** [comment]
The above works on my system. Now to see if it works with other hardware configurations.
