### ISSUE TITLE
Fix compilation with OGRE

### ISSUE THREAD

**Issue by nabaco** [vegastrike/Vega-Strike-Engine-Source#63]
I see that there are two compilation options that are explicitly disabled, due to broken compilation. One of the is compilation with **OGRE**. The current code base is set to compile with an older version of OGRE, but some APIs have changed since, so the code needs to be adapted.

Additionally, looking at different posts on the forum and the wiki, it's unclear to me whether the project ever actually managed to run with OGRE. So it'd be nice to understand what is the status of OGRE integration. Maybe we need to reintegrate from scratch, rather then using the old codebase?

**Comment by royfalk** [comment]
My hazy recollection is of an early alpha attempt. 
My vote is to refactor out. When we stabilize the code, we can start fresh.

**Comment by Loki1950** [comment]
ATM to only mesher uses the Ogre libs for creating/converting to our binary mesh format it's a cli tool and used by pyramid's UnitConveter which is a asset creation/management app

**Comment by nabaco** [comment]
Closing the issue since OGRE is not really integrated, so it's not worth fixing right now.

**Comment by Loki1950** [comment]
Which leaves us with a broken mesher utility so no maintenance of the assets

**Comment by klaussfreire** [comment]
> Which leaves us with a broken mesher utility so no maintenance of the assets

Mesher should build fine without Ogre. Ogre support is optional, or should be.

**Comment by nabaco** [comment]
From what I've seen mesher compiles just fine, though I haven't used it to test functionality.

**Comment by Loki1950** [comment]
Thx for checking I will building later this afternoon and testing mesher with unitconveter the Python GUI that pyramid3D wrote
