### ISSUE TITLE
Upgrade SDL to SDL2

### ISSUE THREAD

**Issue by royfalk** [vegastrike/Vega-Strike-Engine-Source#632]
SDL 2.0 is a major update to the SDL 1.2 codebase with a different, not backwards-compatible[15] API. It replaces several parts of the 1.2 API with more general support for multiple input and output options. Some feature additions include multiple window support, hardware-accelerated 2D graphics, and better Unicode support.

SDL 1.2 is really really old. Probably more than a decade.

**Comment by BenjamenMeyer** [comment]
@royfalk do we want to do this for 0.9.x? Or 0.10.x? given our time one 0.8.x we can probably do it for 0.9.x.

**Comment by stephengtuggy** [comment]
@royfalk This is done, isn't it?

**Comment by BenjamenMeyer** [comment]
yes, 0.9.x is using SDL2.
