### ISSUE TITLE
Game incorrectly says "No Drive" after buying and outfitting Determinant

### ISSUE THREAD

**Issue by stephengtuggy** [vegastrike/Vega-Strike-Engine-Source#636]
During play testing, I bought a Determinant and upgraded it with a Jump Drive, among other things. Yet the game refuses to recognize that I have a jump drive. It shows up in the parts list, but when I look at the Info tab, it says, "No outsystem jump drive present." And when I launch into space, and try to fly through a jump point, it just says, "No Drive."

This is definitely a problem. I need to figure out what's going on before I merge this PR.

_Originally posted by @stephengtuggy in https://github.com/vegastrike/Vega-Strike-Engine-Source/issues/633#issuecomment-1003761934_

**Comment by evertvorster** [comment]
Hey there... So, I bought a milspec Franklin, and run into the same bug. 

Then a stock Dovetesky, same thing.

**Comment by evertvorster** [comment]
Just FYI, this VS was compiled from git master, pulled today.

**Comment by stephengtuggy** [comment]
Crap. OK. Thanks for letting us know. I think I'll start looking into it.
