### ISSUE TITLE
Fix compilation with FFMPEG

### ISSUE THREAD

**Issue by nabaco** [vegastrike/Vega-Strike-Engine-Source#64]
I see that there are two compilation options that are explicitly disabled, due to broken compilation. One of the is compilation with **FFMPEG**. The current code base is set to compile with an older version of FFMPEG, but some APIs have changed since, so the code needs to be adapted.

Since I'm new to the project, I don't really know what ffmpeg was used for in the past (maybe replace OpenAL?), and what was the status of it's integration, so it'd be nice to get an understanding of that too.

**Comment by royfalk** [comment]
I think I did that as part of my failed attempt to refactor the game. 
Take a look at my SVN fork repo. I remember working on these files and hitting and fixing the same issue.

**Comment by Loki1950** [comment]
Use of ffmpeg was to do in game cut scenes though it has not been implemented a all so for now non critical

**Comment by nabaco** [comment]
Closing the issue as irrelevant. When the time comes, we'll reintegrate FFMPEG from scratch, if deemed appropriate.
