### ISSUE TITLE
Access violations on Windows 11 x64 -- graphics-related (stride size?)

### ISSUE THREAD

**Issue by stephengtuggy** [vegastrike/Vega-Strike-Engine-Source#677]
I'm having lots of problems with the game crashing on Windows 11. Usually, it seems to be due to an access violation either in graphics-related code or in the graphics card driver itself. I suspect that at least some of these are related to incorrect assumptions about the size of a pointer and/or stride size. It appears that on x64 (Windows 11 at least), pointers are **128-bit**.

I'm going to make this a priority to try to get fixed. ~It makes the game pretty nearly unplayable on Windows at the moment.~

**Comment by stephengtuggy** [comment]
Update: I don't know why I said it makes the game unplayable. It doesn't seem that bad at present. Except when running the "9k idle, 1k fighting" scenario. That scenario reliably causes the game to crash on Windows.

**Comment by stephengtuggy** [comment]
Looks like I fixed this issue today! Having unrelated issues with another part of the code, though.

**Comment by BenjamenMeyer** [comment]
@stephengtuggy can you please confirm this is fixed so we can close it out?

**Comment by stephengtuggy** [comment]
@BenjamenMeyer I'm not sure that this is fixed. And I don't have a Windows 11 installation available currently. Would someone else be able to test this on Windows 11, and confirm whether it is fixed or not?

**Comment by stephengtuggy** [comment]
I now have access to a Windows 10 x64 installation again, which is probably close enough. And I am not seeing this issue any longer. Closing.
