### ISSUE TITLE
Fedora/RHEL packages missing assets

### ISSUE THREAD

**Issue by jp-bennett** [vegastrike/Vega-Strike-Engine-Source#682]
Just the file sizes are suspicious, but all the .rpm versions of the release are missing assets, making for an unplayable game.

**Comment by stephengtuggy** [comment]
Hi @jp-bennett . Thanks for filing a bug. The assets are intentionally separated out into their own package now: https://github.com/vegastrike/Assets-Production/releases/tag/v0.8.0 Let me know if you still have questions after downloading that.

**Comment by stephengtuggy** [comment]
OK, glad that solved your problem. Cheers
