### ISSUE TITLE
The game can crash with a vector-out-of-bounds exception in `hashers` cleanup code

### ISSUE THREAD

**Issue by stephengtuggy** [vegastrike/Vega-Strike-Engine-Source#685]
Known Issues: The game crashed just now, after I left my ship on autopilot for about 20 minutes. It hit a vector-out-of-bounds exception on [this line](https://github.com/stephengtuggy/Vega-Strike-Engine-Source/blob/fa144c9184c71f2741a9e2cc286d1d033f520ab5/engine/src/gfx/mesh_gfx.cpp#L442). Hopefully I will have this fixed within another couple of PRs or so. At least we're catching it now, rather than blithely going on into unallocated memory or something of the sort.

_Originally posted by @stephengtuggy in https://github.com/vegastrike/Vega-Strike-Engine-Source/issues/683#issuecomment-1128397673_

**Comment by LifWirser** [comment]
20 mins on autopilot , autopilot should drop close enough to relevent nav point. Assuming you didn't crash you most likely were at "system boundery" . an overflow of somekind would be reasonable

**Comment by stephengtuggy** [comment]
Perhaps I did reach the system boundary. The game still shouldn't crash. The game should almost never crash. At least not without providing some sort of "soft landing," as #681 discusses.

**Comment by BenjamenMeyer** [comment]
@stephengtuggy is this still an issue? Can we defer to 0.10.x? Or do we need to close it for releasing 0.9.x?

**Comment by stephengtuggy** [comment]
@BenjamenMeyer I am definitely of the opinion that this needs to be fixed before releasing 0.9.x.

**Comment by BenjamenMeyer** [comment]
> @BenjamenMeyer I am definitely of the opinion that this needs to be fixed before releasing 0.9.x.

Do we have a plan for fixing it?
It has been in there for several releases already; so probably not a deal breaker. Just want to make sure we have some kind of plan before we commit to delaying 0.9.0 further on account of it.

**Comment by stephengtuggy** [comment]
I think I have a relatively small change that I can try. I will try to get to it tomorrow.

**Comment by stephengtuggy** [comment]
I'm pretty sure that this particular source of crashes is now fixed.
