### ISSUE TITLE
Use CMake generator expressions

### ISSUE THREAD

**Issue by stephengtuggy** [vegastrike/Vega-Strike-Engine-Source#693]
In our main CMakeLists.txt file, why don't we use [CMake generator expressions](https://cmake.org/cmake/help/latest/manual/cmake-generator-expressions.7.html), rather than variables specific to Debug, Release, etc.? This is the current recommended practice. And CMake 3.13 and later support it.

**Comment by BenjamenMeyer** [comment]
Looks like that's something newer in the CMake 3 series; certainly something we can start taking advantage of.
