### ISSUE TITLE
Update /relocate VSE/engine /doxygen.config

### ISSUE THREAD

**Issue by LifWirser** [vegastrike/Vega-Strike-Engine-Source#705]
In VSE-0.8.x /engine/doxygen.config is out of date (corrected by " doxygen -u doxygen.config" . Also in [VSE_dir]/doc/ DOCUMENTATION doxygen is refered to with no links or other info.

Seperately I'd like to move "doxygen.config to doc dir as well as resulting output. This requires editing doxygen appropiately to adjust relative dirs.

finally it seema possible to use doxyged on python code and xml in assets pkg. so adding these files to doxygen.config may be usefull.

keeping setup files for other profilers/debuggers in /doc (at least seperate from code helps keep code/data filetrees clean).

**Comment by BenjamenMeyer** [comment]
Python code should use Sphinx; but we do need to refactor the general structure some. For one, I'd like to pull CMakeLists.txt up to the project root which would make a bunch of things easier overall; I'd also like to modularize it more for easier maintenance across all the branches. Doxygen should be integrated into CMake too.

**Comment by LifWirser** [comment]
My thought would be a {app-name} dir and an (app-name}.read-me, so no matter what you use you can place for VS/local scripts and output
 As for Sphinux.I just lokked at website, so my guess would be a "Sphinx" dir and readme in /doc. Unless you want somewhere else. You could do your "docker" file or any other IDE here as well. Right now I am going to see what menues can be made for gdb/doxygen - that will keep me busy for a while

**Comment by LifWirser** [comment]
Here is anupdated doxygenConfig.
If in VSE/doc directory and place this in it the it can be run via "doxygen ./doc/doxygen/doxygenConfi"

REQUIRES: doxygen and graphvis for graphics
Output is in /doc/doxygen/html look for index.html/home/enon/build/Vega-Strike-Engine-Source-0.8.x/doc/doxy
[doxygenConfig.TXT](https://github.com/vegastrike/Vega-Strike-Engine-Source/files/8987331/doxygenConfig.TXT)


``thi is one of the graphic callgraphics\
![select_8cpp_a0ddf1224851353fc92bfbff6f499fa97_cgraph](https://user-images.githubusercontent.com/59220964/175830551-b212689d-4599-41b3-88dc-560322cee901.png)

**Comment by LifWirser** [comment]
Oh BTW, if you add {relative path to Assets} after "INPUT                  = ./engine/( ../Assets-Production-0.8.x/). doxygen will run through assets as well

**Comment by LifWirser** [comment]
This is still a work in progress. I found 2 examples of how to incorperate into Cmake, but haven't yet worked on.

BTW when I ul-ed doxygenConfig I had to add ".txt" to filename for gh issues to accept file  and did not edit post to reflect this 8^(

I'll git master  and put in a pull req for the doxygen.config and maybee gdb scripts as well. . Dont expect any work untill week or two after 4th.
 one detail, is putting this in {VSE}/doc alright or is there another location to put it in?

**Comment by BenjamenMeyer** [comment]
hand editing the config is just fine; we don't need anything fancy in there right now; integration with cmake is more important so it works with the rest of our tool chain.

**Comment by LifWirser** [comment]
PR #719 contains the basics for implementing.

There is/are file for incorperating doxygen into cmake build systems - a seperate issue should be written when ready to be worked on

**Comment by LifWirser** [comment]
further news isee PR #719
