### ISSUE TITLE
units.json still relies on units.csv

### ISSUE THREAD

**Issue by royfalk** [vegastrike/Vega-Strike-Engine-Source#707]
It seems the code in _csv.cpp_ is reading the csv twice. 

`
 CSVTable::CSVTable(VSFileSystem::VSFile &f, const string &root) {
    std::string data = f.ReadFull();
    std::string filename = f.GetFilename();

    UnitCSVFactory factory;
    if (filename == "units_description.csv" ||
            filename == "master_part_list.csv") {
    } else if (filename == "units.csv") {
        UnitJSONFactory::ParseJSON(f.GetFullPath());
    } else {
        factory.ProcessCSV(data, true);
    }

    this->rootdir = root;
    Init(data);
 }
`

Once in the first line into data. The second time in ParseJSON.
The first line is used in Init(data) and is required. 
This means that we still rely on units.csv and it should be refactored.

**Comment by BenjamenMeyer** [comment]
ParseJSON shouldn't be reading the CSV, only the JSON data.
If neither can be read, then an error should be generated; so looks like some refactor is in order.

**Comment by royfalk** [comment]
This issue has been solved some time ago. 
Specifically https://github.com/vegastrike/Vega-Strike-Engine-Source/commit/cb5f5a6adb1b99cb4245c1a2ec94e2b4d8d3e2cc fixed it.
