### ISSUE TITLE
String-management wrapper around `PyRun_SimpleString`?

### ISSUE THREAD

**Issue by stephengtuggy** [vegastrike/Vega-Strike-Engine-Source#710]
Perhaps we need a wrapper around `PyRun_SimpleString` to manage the `strdup`/`free` functionality?
Also, it's possible `strdup` could return a `nullptr` - unlikely but possible.

_Originally posted by @BenjamenMeyer in https://github.com/vegastrike/Vega-Strike-Engine-Source/pull/709#discussion_r913864011_

**Comment by BenjamenMeyer** [comment]
Example from the commented about code above:
```
    std::string python_snippet_to_run_1("import sys\nprint(sys.path)\n");
    VS_LOG(info, (boost::format("running %1%") % python_snippet_to_run_1));
    char *temppython = strdup(python_snippet_to_run_1.c_str());
    PyRun_SimpleString(temppython);
    Python::reseterrors();
    free(temppython);
```

**Comment by stephengtuggy** [comment]
I was thinking of maybe calling it something like `VegaPyRunString`, since `VS` can always potentially be mistaken to mean "Visual Studio." Other than that, I agree with the proposal.
