### ISSUE TITLE
Game crashes on savegame load.

### ISSUE THREAD

**Issue by evertvorster** [vegastrike/Vega-Strike-Engine-Source#720]
Compiled from sources pulled from git master on 2022-07-25. (Both engine and assets)

Terminal output:
```

[evert@Vorster logs]$ vs
Starting Vega Strike...

Registering codec ogg
.
Legacy Mode: TRUE
Saving current directory (/home/evert/.vegastrike/logs) as DATA_DIR
 In path /home/evert/.vegastrike/logs
Vega Strike  
See http://www.gnu.org/copyleft/gpl.html for license details.

ARG #1 = -d/usr/share/vegastrike
Using data dir specified on command line : /usr/share/vegastrike
GOT SUBDIR ARG = 
Found data in /usr/share/vegastrike
Using /usr/share/vegastrike as data directory
Using .vegastrike as the home directory
Found MODDIR = /usr/share/vegastrike/mods
USING HOMEDIR : /home/evert/.vegastrike As the home directory 
CONFIGFILE - Found a config file in home directory, using : /home/evert/.vegastrike/vegastrike.config
LoadGameConfig: Found game config at '/home/evert/.vegastrike/vegastrike.config'
LoadXML called with filename '/home/evert/.vegastrike/vegastrike.config'
DATADIR - No datadir specified in config file, using : /usr/share/vegastrike
Force galaxy to /usr/share/vegastrike/universe/milky_way.xml
SIMULATION_ATOM: 0.01
log directory : '/home/evert/.vegastrike/logs'
['/usr/lib/python310.zip', '/usr/lib/python3.10', '/usr/lib/python3.10/lib-dynload']
['', '/usr/share/vegastrike/modules/builtin', '/usr/share/vegastrike/modules/quests', '/usr/share/vegastrike/modules/missions', '/usr/share/vegastrike/modules/ai', '/usr/share/vegastrike/modules', '/usr/share/vegastrike/bases', '/usr/lib/python310.zip', '/usr/lib/python3.10', '/usr/lib/python3.10/lib-dynload']
Engine Version: 0.9.0.c3ce9dcde 
Asset API Version: 1
::: What's in VS object ['AdjustRelation', 'Cargo', 'EngineVersion', 'GetAdjacentSystem', 'GetContrabandList', 'GetDifficulty', 'GetFactionIndex', 'GetFactionName', 'GetGalaxyFaction', 'GetGalaxyProperty', 'GetGalaxyPropertyDefault', 'GetGameTime', 'GetJumpPath', 'GetMasterPartList', 'GetNumAdjacentSystems', 'GetNumFactions', 'GetRelation', 'IOmessage', 'LoadMission', 'LoadMissionScript', 'LoadNamedMissionScript', 'LookupUnitStat', 'PythonAI', 'SafeEntrancePoint', 'SetAutoStatus', 'SetDifficulty', 'SetGalaxyFaction', 'SetTimeCompression', 'StopAllSounds', 'StopTargettingEachOther', 'TargetEachOther', 'Unit', '__doc__', '__loader__', '__name__', '__package__', '__spec__', 'acos', 'addObjective', 'addParticle', 'adjustFGRelationModifier', 'adjustRelationModifier', 'adjustRelationModifierInt', 'asin', 'atan', 'cacheAnimation', 'clearObjectives', 'cos', 'eraseObjective', 'exp', 'getCompleteness', 'getCurrentPlayer', 'getCurrentSaveGame', 'getFGRelationModifier', 'getMissionOwner', 'getNewGameSaveName', 'getNumPlayers', 'getNumUnits', 'getOwner', 'getPlanetRadiusPercent', 'getPlayer', 'getPlayerX', 'getRandCargo', 'getRelationModifier', 'getRelationModifierInt', 'getSaveDir', 'getSaveInfo', 'getScratchUnit', 'getScratchVector', 'getStarDate', 'getStarTime', 'getSubVariable', 'getSystemFile', 'getSystemName', 'getTargetLabel', 'getUnit', 'getUnitByName', 'getUnitList', 'getVariable', 'hideSplashScreen', 'isCitizen', 'isSplashScreenShowing', 'isserver', 'launch', 'launchJumppoint', 'loadGame', 'log', 'micro_sleep', 'musicAddList', 'musicLayerLoopList', 'musicLayerPlayList', 'musicLayerPlaySong', 'musicLayerSetHardVolume', 'musicLayerSetSoftVolume', 'musicLayerSkip', 'musicLayerStop', 'musicLoopList', 'musicPlayList', 'musicPlaySong', 'musicSetHardVolume', 'musicSetSoftVolume', 'musicSkip', 'musicStop', 'networked', 'newGetPlayer', 'numActiveMissions', 'playAnimation', 'playAnimationGrow', 'playSound', 'playSoundCockpit', 'popSystem', 'precacheUnit', 'pushSystem', 'receivedCustom', 'saveGame', 'sendCustom', 'setCompleteness', 'setMissionOwner', 'setObjective', 'setOwner', 'setScratchUnit', 'setScratchVector', 'setTargetLabel', 'showSplashMessage', 'showSplashProgress', 'showSplashScreen', 'sin', 'sqrt', 'systemInMemory', 'tan', 'terminateMission', 'timeofday', 'un_iter', 'vsConfig'] :::
::: Engine Version 0.9.0.c3ce9dcde :::
::: Asset API Version 1 :::
Loading active missions True
  IS NOW AT  Special/Empty

Launching bases for Special/Empty
Adding news
New selection: 2
libpng warning: Interlace handling should be turned on when using png_read_image
terminate called after throwing an instance of 'json::parsing_error'
  what():  Input was not an array
/usr/bin/vs: line 28: 34166 Aborted                 (core dumped) vegastrike -d"${VEGASTRIKE_SHARE_DIR}" "$1"
[evert@Vorster logs]$ 
```

Log output:
```
[evert@Vorster logs]$ cat vegastrike_2022-07-26_04_50_33.654259.log
[2022-07-26 04:50:33.654226]:  File is a directory ! 
[2022-07-26 04:50:33.654340]:  File is a directory ! 
[2022-07-26 04:50:33.654348]:  File is a directory ! 
[2022-07-26 04:50:33.654353]:  File is a directory ! 
[2022-07-26 04:50:33.782814]: 
ERROR: NULL Unit used in Python script; returning default value...
[2022-07-26 04:50:33.782851]: 
ERROR: NULL Unit used in Python script; returning default value...
[2022-07-26 04:50:33.784334]: CreateVideoTexture could not find preintro.ogv
[2022-07-26 04:50:33.784375]: CreateVideoTexture could not find intro.ogv
[2022-07-26 04:50:41.090065]:  File is a directory ! 
[2022-07-26 04:50:41.090155]:  File is a directory ! 
[2022-07-26 04:50:41.090163]:  File is a directory ! 
[2022-07-26 04:50:41.090169]:  File is a directory ! 
[2022-07-26 04:50:41.090175]:  File is a directory ! 
[evert@Vorster logs]$ 
```

And, finally, a video clip:

https://user-images.githubusercontent.com/12045269/180913480-d9f8666b-3f68-4a8d-8951-e71ff8364b0b.mp4

**Comment by evertvorster** [comment]
Of course running on Arch Linux, as nature intended.

**Comment by stephengtuggy** [comment]
Yikes. That's not good.

**Comment by stephengtuggy** [comment]
@evertvorster So far, I have not been able to reproduce this issue. Which configuration did you compile the code in? Debug? Release? `ENABLE_PIE` ON or OFF? Legacy GL mode, or GLVND?

It looks like you ran the game from the `~/.vegastrike/logs` directory. I wonder if that made any difference. Maybe I'll try that.

**Comment by stephengtuggy** [comment]
I think I know what the problem is. Evert, you're running the game from the installed assets, which are missing the latest file converted to JSON: master_part_list. The above PR should fix this.

**Comment by evertvorster** [comment]
How is it possible that the game started depending on something before that something even was in assets?
I'll test it once the PR is merged. Thanks for the quick fix.

**Comment by stephengtuggy** [comment]
The file was present in the assets **as they are in source control.** Just not in the assets **as installed,** because it wasn't listed in CMakeLists.txt.

**Comment by stephengtuggy** [comment]
And you're welcome :-)

**Comment by evertvorster** [comment]
That would definitely explain it.
In Hindsight it may not be such a good idea to point the game engine at source control, and rather only at what is installed through CMakeLists?

**Comment by BenjamenMeyer** [comment]
@evertvorster since you're operating off master you'll hit things like that as they change. You shouldn't be hitting those issues using the release versions, which with 0.8.x should be more feasible for you now. So perhaps time to split the AURs for a `stable` pointing at the latest release and `unstable` for latest source? 💸

**Comment by BenjamenMeyer** [comment]
Assuming https://github.com/vegastrike/Assets-Production/pull/96 does solve this, then that means the VS Engine may have a bug around find the CSV now as it should fall back trying the CSV when the JSON isn't found. We should be supporting both still, but it should prefer the JSON if the JSON is available.

**Comment by evertvorster** [comment]
@BenjamenMeyer there is a branch following the latest release, but that's boring. 
I'd rather play with master, and find these types of bugs early. At least it's an easy fix, and it slipping through does point to a weakness in the testing methods used so far. So, it's a win all round. :)

**Comment by stephengtuggy** [comment]
@evertvorster PR merged. Can you retest? Thanks!

**Comment by BenjamenMeyer** [comment]
let's keep this open until we can confirm it's fixed, and that the code is properly falling back to the CSV

**Comment by evertvorster** [comment]
Hi there!
Yes, so I just installed Assets again, this time with the PR merged, and am able to load a save game and fly around. 
This means that the correct file is now in place. 

Of course, without a change to the game engine, it won't work if this json file is renamed or moved. This could be a simple test done when/if the engine gets patched to fall back gracefully. 

I am quite happy to close this ticket now, if all agree. Because Assets and Engine are released together, I don't think that the fallback is such a huge priority. In a while, this will be long forgotten, and then the code to fallback would just be an unnecessary stub.

**Comment by stephengtuggy** [comment]
I filed the CSV fallback issue separately, as #724 . Is everyone good with closing this ticket, and continuing the fallback discussion in #724 ?

**Comment by evertvorster** [comment]
I am going to pull the plug on this issue, as it is fixed. ;)

**Comment by BenjamenMeyer** [comment]
> I filed the CSV fallback issue separately, as #724 . Is everyone good with closing this ticket, and continuing the fallback discussion in #724 ?

Thanks - that's sufficient to document it here
