### ISSUE TITLE
Savegames, when loaded, are missing the player's ship

### ISSUE THREAD

**Issue by stephengtuggy** [vegastrike/Vega-Strike-Engine-Source#747]
When I load a savegame that was generated using a recent build of Vega Strike, my ship is gone.

Savegames generated using previous builds do not have this problem.

**Comment by stephengtuggy** [comment]
This bug was probably introduced in September or October.

**Comment by LifWirser** [comment]
I have noticede the following as of 11-24-22
1. all cargo in newly saved game "disappears when reloaded
2. 2 allship assets/upgrade also disappear when loaded
3. 3 as above all ship inflight displays indicating fuel ,nave speed also have vanished
4. 4 load fron save point created before recompile do not suffer some problems
5. new save games are about simular in size to older save s however seem to be clutered with data from systems not yet traveled to

**Comment by stephengtuggy** [comment]
@LifWirser thanks for the additional observations. Those are helpful.

**Comment by stephengtuggy** [comment]
OK, I have narrowed it down further: This bug was introduced in #736 .

**Comment by BenjamenMeyer** [comment]
@stephengtuggy may be good to use `git bisect` then to narrow further

**Comment by royfalk** [comment]
The issue is that Unit::WriteUnitString relies on unitTables global variable. 
The new code relies on UnitCSVFactory::units.
I hope I'll fix this in the next few days.

**Comment by stephengtuggy** [comment]
@royfalk That would be great, thanks.
