### ISSUE TITLE
Main Menu, various other pre-rendered screens not rendering

### ISSUE THREAD

**Issue by stephengtuggy** [vegastrike/Vega-Strike-Engine-Source#766]
Known issue: main menu, various other pre-rendered screens not rendering, except for a solid background color. (They are still clickable, however.) (Yeah, this one's kind of a big deal.)

_Originally posted by @stephengtuggy in https://github.com/vegastrike/Vega-Strike-Engine-Source/issues/754#issuecomment-1454808602_

**Comment by evertvorster** [comment]
Just ran into this one while trying out the latest changes to the master branch. 

It's pretty debilitating, not being able to see what you are doing. I tried clicking on random places on the screen, but so far have been unable to get anything like game play.

**Comment by evertvorster** [comment]
Mouse cursor in flight does not render either

**Comment by evertvorster** [comment]
When pressing "Esc" in flight does not bring up that screen either..

**Comment by stephengtuggy** [comment]
Yep, it's a doozy, all right. I'm thinking that this issue should be the top priority to fix.

**Comment by evertvorster** [comment]
Since this bug is against git master, the game is pretty much unplayable until this issue is fixed.

**Comment by evertvorster** [comment]
Hmm, maybe this is a better place for my little video clip of what the current master looks like on my machine:


https://github.com/vegastrike/Vega-Strike-Engine-Source/assets/12045269/1acee12d-efd1-40d4-a183-7b006466eace

**Comment by stephengtuggy** [comment]
This issue should be fixed now, at least on `master`.

**Comment by BenjamenMeyer** [comment]
Can we confirm this is fixed on the 0.9.x branch and on master?

**Comment by stephengtuggy** [comment]
@BenjamenMeyer I'm fairly confident that this is fixed on 0.9.x and later. I think this ticket can be closed.

**Comment by stephengtuggy** [comment]
This problem was only present with the PR 754 code.

**Comment by BenjamenMeyer** [comment]
Closing
