### ISSUE TITLE
When bolts are fired, game crashes

### ISSUE THREAD

**Issue by stephengtuggy** [vegastrike/Vega-Strike-Engine-Source#768]
Known issue: When bolts are fired, game crashes while trying to process them / update their physics. (Fix in progress.)

_Originally posted by @stephengtuggy in https://github.com/vegastrike/Vega-Strike-Engine-Source/issues/754#issuecomment-1454809238_

**Comment by stephengtuggy** [comment]
I think this was specific to the PR 754 code. @BenjamenMeyer we can probably remove it from the 0.9.x board.

**Comment by BenjamenMeyer** [comment]
@stephengtuggy done; would you consider this closed then?

**Comment by stephengtuggy** [comment]
Yes. Closing.
