### ISSUE TITLE
README - Bootstrapping instructions are incorrect/incomplete

### ISSUE THREAD

**Issue by stephengtuggy** [vegastrike/Vega-Strike-Engine-Source#79]
The current README makes it sound like installing the dependencies is optional if you run the `vsbuild.sh` script. Which is not the case.

Installing (`apt`) dependencies is a required step, either way. *Then*, one either runs `vsbuild.sh`, or does the equivalent manually. Am I missing something here?

Also, I am not sure that the list of `apt` dependencies given is complete, either. Here is my list:

```
sudo apt install git cmake cmake-curses-gui python-dev build-essential automake autoconf libpng16-16 libpng-dev libpng-tools libjpeg62-turbo-dev libexpat1-dev libgtk2.0-dev libopenal-dev libogg-dev libvorbis-dev libgl1-mesa-dev libsdl1.2-dev libavcodec-dev libavcodec-extra libavformat-dev libavresample-dev libavutil-dev libavdevice-dev libpostproc-dev freeglut3-dev libxmu-dev libxi-dev libboost-python1.67-dev
```

Note that I developed/tested the above on Debian 10 64-bit.

**Comment by Loki1950** [comment]
There is also cmake-gui which uses qt5

**Comment by BenjamenMeyer** [comment]
I typically just use CMake without the GUI; for simpleness we probably just want to list `cmake` but then note that there are available GUI options which may require additional dependencies.

**Comment by BenjamenMeyer** [comment]
Also, an easy way to test this is to use a Docker image. Then one can test various distros to capture the requirements from them. The main Linux ones I would do:

- CentOS or Fedora
- Debian or Ubuntu

Optional:
- Arch
- Gentoo
- OpenSuSE (similar to CentOS but different as their RPM chain differs from Red Hat's).

We should also document a Mac configuration (HomeBrew dependencies?). We can wait on Windows until someone can actually build it; but the dependencies shouldn't be vastly different - just the installation method.

**Comment by nabaco** [comment]
Related to #78, #53, #40.

**Comment by nabaco** [comment]
@stephengtuggy Any chance you can make a PR with those changes?

**Comment by stephengtuggy** [comment]
@nabaco Working on it.
