### ISSUE TITLE
Some macOS builds failing due to Python version conflicts

### ISSUE THREAD

**Issue by stephengtuggy** [vegastrike/Vega-Strike-Engine-Source#812]
(Python 3.11 vs. Python 3.12.) Boost Python is apparently trying to use the wrong one, or something.

**Comment by stephengtuggy** [comment]
See https://github.com/vegastrike/Vega-Strike-Engine-Source/actions/runs/6826816090/job/18567546408

**Comment by stephengtuggy** [comment]
This fix is now complete, at least for 0.8.x and 0.9.x.

**Comment by BenjamenMeyer** [comment]
> This fix is now complete, at least for 0.8.x and 0.9.x.

@stephengtuggy okay, at least temporarily assigned to 0.10.x (master); feel free to close if you think it's not applicable there.

**Comment by stephengtuggy** [comment]
Yep, it's fixed on 0.10.x as well. Closing.
