### ISSUE TITLE
GH Action `Scorecards Supply-Chain Security` failing because Debian version used is so old

### ISSUE THREAD

**Issue by stephengtuggy** [vegastrike/Vega-Strike-Engine-Source#814]
See https://github.com/vegastrike/Vega-Strike-Engine-Source/actions/runs/6975677063/job/18983122107 . The version of the `Scorecards supply-chain security` GitHub Action we are using is so old that it tries to use Debian stretch. `apt-get update` fails, since Debian stretch updates are no longer available.

We probably just need to disable this GitHub action on our repo. At least as a short-term fix.

**Comment by BenjamenMeyer** [comment]
@stephengtuggy which GH action is it?

**Comment by BenjamenMeyer** [comment]
@stephengtuggy  yeah - we're significantly out of data, version 1.0.1 and they are up to v 2.3.1.

I think it's certainly a valuable resource for us so we should update and re-enable it.

https://github.com/marketplace/actions/ossf-scorecard-action
