### ISSUE TITLE
Is it possible to disable the unit tests when compiling?

### ISSUE THREAD

**Issue by evertvorster** [vegastrike/Vega-Strike-Engine-Source#850]
Hi there, gang. 

I am currently behind a pretty slow and flaky internet connection, and would like to test the latest changes to the vegastrike engine. 
Unfortunately, during the configuration stage of the build, the unit tests almost always fails to download, and that takes the whole build with it. 

Is there any way of telling the build process not to do the unit tests?

Any help would be appreciated!

**Comment by stephengtuggy** [comment]
Hi, @evertvorster ,

Good to hear from you. Yes, there is a way to do that, actually. You can set the CMake options/variables `INSTALL_GTEST `and `USE_GTEST` both to `OFF`. You can do this by appending `-DINSTALL_GTEST=OFF -DUSE_GTEST=OFF` to the CMake command line.

Hope this helps!

**Comment by evertvorster** [comment]
Awesome, this works beautifully. I have added it to the Arch AUR package.
