### ISSUE TITLE
Scaling on Wayland confuses the fullscreen.

### ISSUE THREAD

**Issue by evertvorster** [vegastrike/Vega-Strike-Engine-Source#856]
When playing on Wayland, and having the monitors fractionally scaled, the fullscreen option does not work anymore, as it tries to display at the native resolution rather than the scaled resolution. 

I know this is way outside of the issues we are dealing with, but adding in this report to collect more issues of the same type in one place until we have a developer that can get our screen output code whipped into shape. 

About my system:
```
Operating System: Arch Linux 
KDE Plasma Version: 6.0.4
KDE Frameworks Version: 6.1.0
Qt Version: 6.7.0
Kernel Version: 6.8.8-arch1-1 (64-bit)
Graphics Platform: Wayland
Processors: 32 × 13th Gen Intel® Core™ i9-13900HX
Memory: 62.5 GiB of RAM
Graphics Processor: Mesa Intel® Graphics
Manufacturer: TUXEDO
Product Name: PD5x_7xSNC_SND_SNE
```

**Comment by BenjamenMeyer** [comment]
Thanks. We can't do this in 0.9.x; so 0.10.x at earliest

**Comment by evertvorster** [comment]
Yeah, I think that this issue will be fixed when we move on to a more modern renderer sometime in the future. 

The current workaround is to use a web page that shows your current resolution, as they are fooled just as hard by the scaling. 
With that resolution in hand, you can then make a custom resolution to be used by Vega Strike. 
In my case with a multi-monitor setup, Vega Strike might pop up on the wrong monitor, but you can drag the full screen display on to the right monitor by holding down the windows key and then click and drag the screen to the proper monitor. 

Once you have all that in place, the game runs great.
