### ISSUE TITLE
VS in fullscreen mode pops up on the wrong screen.

### ISSUE THREAD

**Issue by evertvorster** [vegastrike/Vega-Strike-Engine-Source#863]
With the 0.8.x version of the engine, VS in fullscreen mode pops up on Monitor 0 (Primary monitor)

With the git master version, it pops up on the leftmost screen, no matter which monitor is set to be the primary monitor.

I believe the default for SDL is to fullscreen on monitor 0, and I am not sure what changed between the two game versions to effect this change in behaviour. 

Pie in the sky forward looking best fix would be to read the display configuration while starting up, and compare it with the last display configuration that was set. If there is a difference, maybe have a popup window with the detected displays and a simple interface to pick one to be used. Then, save this configuration for the next time. 

With the quickest Google search, I found two interesting links on how to manipulate the SDL startup window:
https://discourse.libsdl.org/t/getting-display-information-before-creating-a-window/21146

and

https://stackoverflow.com/questions/41745492/sdl2-how-to-position-a-window-on-a-second-monitor

**Comment by evertvorster** [comment]
Ooh, an even better link:
https://discourse.libsdl.org/t/sdl-createwindow-on-multiple-screens/19875

**Comment by BenjamenMeyer** [comment]
hmmm..curious if we can fix this in our SDL2 usage now...
@evertvorster thanks for the links

**Comment by royfalk** [comment]
Does it open on your left screen by any chance? 
Can you try switching the screens virtually and see if that works?
Not a workaround so much as a way to figure out the bug.

**Comment by royfalk** [comment]
@evertvorster , I don't have two monitors. 
If I write some fix, can you test it?

**Comment by evertvorster** [comment]
Hi there!
I'll have two monitors in a week when I am home. VegaStrike does pop up on the left, as you mentioned. 

I'm studying Python in my spare time (I don't have much of that luxury now, but later maybe) and might overhaul the configuration part of VegaStrike as a project.

**Comment by royfalk** [comment]
#876 should hopefully fix this.

**Comment by evertvorster** [comment]
OK, testing with the config.json file in place, the game starts up.
Unfortunately, this configuration option seems to be getting ignored. 
I have tried various screens from 0 to 3, and it always pops up on the leftmost monitor. 

I'm still using Wayland.

**Comment by royfalk** [comment]
I checked and it's actually worse. config.json isn't loaded because the attempt is made before we switch from the build branch to the data folder. To be continued in #895 .

**Comment by royfalk** [comment]
Are you testing master or my latest PR (#895 )?

**Comment by evertvorster** [comment]
Hi there! 
Yes, I have been testing that PR, and made some comments on the PR from a play ability perspective. The most serious is that SPEC on the initial Llama does not work properly. In fact, there are a few bugs that stem from the fact that the initial Llama is special. 

It's one of those nice to have things that you mentioned somewhere else...
It does, however add a lot of complexity that I honestly don't think adds that much to the game. 
The whole system of milspec and hunter and other modifiers to standard ships seems very convoluted and fragile.

This could be an area where we could have a discussion on what the best way forward for VegaStrike should be, both from a playability and a support perspective.

**Comment by royfalk** [comment]
I want to be clear - has this issue been reopened because the PR is breaking it? Or is it already in master?

It's important so I'll know which branch to look at for the bug. As for the rest, as it is still in PR, keep the discussion there. We'll figure out a solution to all these issues.

**Comment by evertvorster** [comment]
Ah, I see the miscommunication here. 
This issue has been reopened because it is happening again in master. 

It also happens with the PR, but that is sort of expected.

**Comment by royfalk** [comment]
OK. As it has been merged already, there's no point in opening a separate branch for this. I'll just fix this as part of #895 or the upcoming PR.

**Comment by evertvorster** [comment]
How does one specify the monitor to be used in config.json?

**Comment by royfalk** [comment]
Answered in #36 .
If there are any new questions, let's focus them in #36.
Closing.
