### ISSUE TITLE
Convert README to Markdown format

### ISSUE THREAD

**Issue by stephengtuggy** [vegastrike/Vega-Strike-Engine-Source#9]
For open source projects on GitHub, a nice, well-formatted, up-to-date README can be very important. Projects with a good README.md file tend to attract more contributors. So I propose to convert Vega Strike's README to README.md (Markdown format instead of plain text) as a starting point. We can then go on to update it with more current, accurate content.

**Comment by Loki1950** [comment]
Looks good to go from me Stephen

**Comment by stephengtuggy** [comment]
@Loki1950 Cool. Can you go to [the Files Changed tab of the Pull Request](https://github.com/vegastrike/Vega-Strike-Engine-Source/pull/10/files), click on Review Changes, then leave your review? Thanks!
