### ISSUE TITLE
Llama.begin is not upgraded in game when purchasing the first repair and refuel.

### ISSUE THREAD

**Issue by evertvorster** [vegastrike/Vega-Strike-Engine-Source#916]
Just noticed this as well, and not in play testing pull request #896 

When starting a new campaign, and immediately purchasing the refuel and repair for your ship, set speed for the flight control computer is supposed to change from 120 to 125. That does not seem to happen anymore. 

I tested by saving a game, and loading that. 

Just for clarity, I am testing the latest master branches of Assets and Engine.

**Comment by evertvorster** [comment]
This is still happening on a new game.

**Comment by royfalk** [comment]
We can absolutely have the ship start as damaged. Simply change "x" to "x/y" where y is less than x.
Two issues:
1. Right now, if something is damaged, you can't sell or upgrade anything else.
2. If you do this, we'll start seeing the bugs in the damage area. e.g. Drive isn't a component in the manifest yet, so the function to fix it isn't accessible in the game.

**Comment by evertvorster** [comment]
Hi there!
Thanks for your patience while I tested this. 

On my local copy of vegastrike, I edited /usr/share/vegastrike/units/ships.json. 

In llama.begin, I removed the field "Default_Speed_Governor": "120",
and also "Afterburner_Speed_Governor": "120", (In the beginning of the game you don't have an afterburner, and it is highly unlikely that you will have one before the first repair.)

Then, in llama.blank I set this line "Default_Speed_Governor": "120/125",
When having this, the governor speed is 120. After a repair, it is still 120. This is when starting a new campaign. 

However, you also said that the second value should be less than the first value.
So, I set it to 125/120  Now, the llama you get when starting a new campaign has a governor speed of 125 before repairing it, and also after repairing it. 

It would appear that the current master does not have the game logic to read the second value in this pair of values.

**Comment by royfalk** [comment]
So, I think you missed the way the game builds a unit from ships.json.

Consider
```
a
-b
 -c
```
The game takes a and puts it into a dictionary/map - a data structure of key/value.
The game then creates a copy of a and overwrites every key in a that is also in b.

>In llama.begin, I removed the field "Default_Speed_Governor": "120", and also "Afterburner_Speed_Governor": "120"

That means that llama.blank will default to 0 kph speed.

>Then, in llama.blank I set this line "Default_Speed_Governor": "120/125",

This is the right way. However, we can't actually fix it yet. As I said above, we need to create a drive component (that can't be sold) to be represented. Then, we could click on it and click _repair_. Alternatively, we could add code to 'general repair' for now, to call the function to fix the drive (and other similar components).

**Comment by evertvorster** [comment]
Having a catch-all for now would be the least amount of work, right?
In the future we could move out components as the need arises. 

What I get from your message is that this code is not implemented yet, and so putting a Default Speed Governor of 120/125 just won't work for now?

**Comment by royfalk** [comment]
> Having a catch-all for now would be the least amount of work, right?

Yes. The other option is where I want to go, but there are several steps I need to finish before.

> What I get from your message is that this code is not implemented yet, and so putting a Default Speed Governor of 120/125 just won't work for now?

...However, driver is still not a visible component so it can't be fixed. (we should open a bug on that in any case).

This should be a real easy fix. Expect this by the weekend.

**Comment by evertvorster** [comment]
Hi there!

Just tested this again. Now it does work, but to have the game play properly we still need to make that change to ships.json in Assets. 

For this to work properly for me, I removed the lines Afterburner_Speed_Governor and Default_Speed_Governor from llama.begin, and modified Default_Speed_Governor in llama.blank to read 120/125. 

However, should anyone buy a llama later in the game, would it not mean that they also have a speed governor set to 120/125 on a brand new ship? 

Would it not make more sense to just edit Default_Speed_Governor in llama.begin? 
Since that is the only time you ever get a beginning llama, that is the only time that it should have a governor set to less than the fully fixed up version?

I have tested simply modified Default_Speed_Governor to read 120/125 in llama.begin, and indeed that behaves as expected. 
However, Afterburner_Speed_Governor still reads 120. Setting that to 120/125 makes it so that I cannot purchase a repair/refuel. Simply removing that line from llama.begin gives me an overdrive governor of 125, which seems to be an acceptable solution. 

You won't be able to actually get to a place where you can purchase an afterburner in the game before purchasing an afterburner, so having that speed a bit higher is no big deal, as it will be correct for when you do have an afterburner.
