### ISSUE TITLE
Path to submit bugs without having a GitHub account

### ISSUE THREAD

**Issue by BenjamenMeyer** [vegastrike/Vega-Strike-Engine-Source#96]
We track all our bugs in GitHub Issues - and rightly so as that's where development is.
However, we need to have some documented methods that folks can communicate bugs with us where someone with GitHub access enters it on their behalf should they not have (and not want to have) a GitHub account of their own.

Some potentials:
- [x] in the forums (for folks that have a forum account)
- [x] mailing list
- [x] Gitter/IRC conversation

We already have two of the three methods; but we should make sure to have a `mailing list` as well, even if it's just a simple postfix list to forward to a few key people involved in the project.

**Comment by nabaco** [comment]
+1 for a mailing list. It could also help accepting patches from people who prefer not to use Github.

But I think the main method should be the forum. Once we move to Discourse, it has integration into Github that will make such things easier.

**Comment by BenjamenMeyer** [comment]
Note: we need the mailing list to make ti easy for Linux packages and man pages to document an easy place to submit stuff as an email address is preferred in those cases

**Comment by nabaco** [comment]
So what's the status on it? What are the depenedencies?

**Comment by BenjamenMeyer** [comment]
Asking our email admin about what we're using (via gitter); haven't gotten a response yet.

Some mail servers have email list support built-in (Postfix, Exim) while others require addition packages. I'd rather have a tool (mailman, majordomo, etc) configured to integrate with our mail server to support it so we don't have to manually manage the mailing list, but we can get something static, manually managed up quickly.

**Comment by BenjamenMeyer** [comment]
We have a couple email accounts on our server; I primarily have access right now.

**Comment by BenjamenMeyer** [comment]
Satisfactorily complete for 0.6.x; moving any more work to 0.7.x.

**Comment by stephengtuggy** [comment]
@BenjamenMeyer Can we close this issue? If more work is needed, perhaps we can open a new ticket?

**Comment by BenjamenMeyer** [comment]
@stephengtuggy I'd like to keep it open for the mailing list configuration. I've moved the target to 0.7.x for that.

**Comment by BenjamenMeyer** [comment]
We now have a mailing list for things; just need to update documentation.

**Comment by BenjamenMeyer** [comment]
Pretty sure this is now done since a bunch of documentation has been updated, both in 0.7.x and in master.
