### ISSUE TITLE
Linux Desktop Integration

### ISSUE THREAD

**Issue by BenjamenMeyer** [vegastrike/Vega-Strike-Engine-Source#97]
We should provide Desktop Integration via the Free Desktop Entry Specification. This is basically a text file of the name `VegaStrike.desktop` (or similar) that we could ultimately drop in `/usr/share/applications` which would then allow Vega Strike appear on the launcher menus of the various desktop environments (KDE, GNOME, etc).

For reference see https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html

**Comment by nabaco** [comment]
Agreed. But I think we should start dealing with that once we figure out the packaging side of things.

**Comment by pyramid3d** [comment]
https://github.com/vegastrike/Assets-Production/blob/f3309d0d63218341c0bce5bf966522b66a8866d6/vegastrike.desktop

**Comment by BenjamenMeyer** [comment]
@pyramid3d thanks; we probably should have a default one with the Core Engine repo too at least as reference; asset repos can then make one specific for the games they for.

**Comment by Loki1950** [comment]
Thx for putting this in my face ;) missed it's creation and as @nabaco mentioned it is something we need to do for packaging even on the way back machine having to add VS to the menu manually was a bit of a chore

**Comment by BenjamenMeyer** [comment]
We now have icons and short cuts for VS and the configuration tool as part of VS:UtCS. I think we can close this out for now.
