### ISSUE TITLE
Proposal: Streamline naming of binaries

### ISSUE THREAD

**Issue by ermo** [vegastrike/Vega-Strike-Engine-Source#99]
On Windows, VS is habitually associated with Visual Studio and any binary that contains `setup` is considered an installation package of some sort.

And since Windows now supports arbitrary length names and isn't confined to the ye olde 8.3 format, I therefore propose renaming the Vega Strike binaries as follows:

**Option A**

- `vegastrike` -> `vegastrike` (no change)
- `vegaserver` -> `vegastrike-server`
- `vssetup`-> `vegastrike-settings`

Another, simpler alternative (in terms of lines of code etc. changed) is:

**Option B**

- `vegastrike` -> `vegastrike` (no change)
- `vegaserver` -> `vegaserver` (no change)
- `vssetup`-> `vegasettings`

**Comment by BenjamenMeyer** [comment]
agreed; we should change them. It might be good to make them parameters so that downstream projects compiling the engine can set:
- executable names
- configuration file

While this isn't as relevant on Linux (namely due to symlinks), on Windows/Mac (given how packaging on those platformsworks) is probably more important to do so that the executable can match the downstream game and not cause user confusion.

**Comment by nabaco** [comment]
@BenjamenMeyer I totally agree about making this a parameter, though I think this needs some investigation about the consequences of such a change (binary size and such).

Out of curiosity, why are we considering this a bug?

**Comment by BenjamenMeyer** [comment]
@nabaco because of how the name effects Windows users

**Comment by ermo** [comment]
I'm working on a local branch where I've only renamed `vssetup` to `vegasettings`.

This keeps the current convention of `vegastrike`/`vegaserver`/`vegasettings` and makes for a less intrusive patch.

**Comment by ermo** [comment]
> agreed; we should change them. It might be good to make them parameters so that downstream projects compiling the engine can set:
> 
>     * executable names
> 
>     * configuration file
> 
> 
> While this isn't as relevant on Linux (namely due to symlinks), on Windows/Mac (given how packaging on those platformsworks) is probably more important to do so that the executable can match the downstream game and not cause user confusion.

Making the name configurable should be a separate PR IMHO.  The diff is already big enough.

**Comment by ermo** [comment]
Note that I'm including some beginning edits to the man page (which is *completely* out of date).

Fixing up the man page properly is a separate job best handled by the web assets team as it has lots of links to various resources etc. I did a quick clean-up, but someone else needs to get on this ASAP for 0.6.x.

@nabaco?

**Comment by BenjamenMeyer** [comment]
@ermo filed #113 for the manpage update; thanks for the find!

**Comment by BenjamenMeyer** [comment]
> > agreed; we should change them. It might be good to make them parameters so that downstream projects compiling the engine can set:
> > ```
> > * executable names
> > 
> > * configuration file
> > ```
> > 
> > 
> > While this isn't as relevant on Linux (namely due to symlinks), on Windows/Mac (given how packaging on those platformsworks) is probably more important to do so that the executable can match the downstream game and not cause user confusion.
> 
> Making the name configurable should be a separate PR IMHO. The diff is already big enough.

I'm find with that; let's make sure there's an issue filed to track it.
